### ISSUE TITLE
Foreign key issue with part table of part table

### ISSUE THREAD

**Issue by tdincer** [datajoint/datajoint-python#1003]
The second multiple parts example in this tutorial no longer works: https://docs.datajoint.org/python/computation/03-master-part.html

The following piece of code throws a `DataJointError: Foreign key reference ElectrodeResponse could not be resolved` error.

<img width="442" alt="Screen Shot 2022-03-22 at 1 18 38 PM" src="https://user-images.githubusercontent.com/13665472/159549068-45a12950-28be-48e2-a048-b983681f3c3b.png">

Alternatively the following lines run without any error.
<img width="433" alt="Screen Shot 2022-03-22 at 1 26 59 PM" src="https://user-images.githubusercontent.com/13665472/159550553-ba2b59c2-00dc-447c-8702-7501f9e6a697.png">

but this time `ArrayResponse.ElectrodeResponse.ChannelResponse()` is not accessible and the command returns the following error:  `AttributeError: 'NoneType' object has no attribute 'non_blobs'`.

**Comment by dimitri-yatsenko** [comment]
Double-nested part tables should not be supported. 

The following reference should work 
```
-> master.ElectrodeResponse
```
or 
```
-> ArrayResponse.ElectrodeResponse
```

**Comment by tdincer** [comment]
Thank you!
