### ISSUE TITLE
convert nosetests to pytest

### ISSUE THREAD

**Issue by A-Baji** [datajoint/datajoint-python#1011]
### Description
nose does not support python 3.10
https://github.com/nose-devs/nose/issues/1099
https://nose.readthedocs.io/en/latest/#note-to-users

**Comment by miraclemore** [comment]
install nose-py3 instead of nose on Python3.10

**Comment by jverswijver** [comment]
Seems like it is much easier to test python logging with pytest than with nosetest, another reason why we should consider switching to pytest.

**Comment by ethho** [comment]
Fixed in #1142.
