### ISSUE TITLE
Update references to table "relations"

### ISSUE THREAD

**Issue by iamamutt** [datajoint/datajoint-python#1042]
https://github.com/datajoint/datajoint-python/blob/b0f5dc4a27bddfc24598173797b1638f0df2adeb/datajoint/schemas.py#L174

https://github.com/datajoint-company/datajoint-utilities/pull/23#discussion_r926152017

**Comment by sculley** [comment]
Please assign me this issue, thanks!

**Comment by sculley** [comment]
I believe #1059 is ready to merge now right?
