### ISSUE TITLE
Add parameter to chunk transactions in Computed tables

### ISSUE THREAD

**Issue by zhenruiliao** [datajoint/datajoint-python#1046]
### Problem
Sometimes I will be autopopulating a large computed table, possibly thousands of entries and in parallel, which may take several days. By default this seems to happen in one transaction -- however, this means that if any individual `make` fails or the operation is interrupted for some reason, the entire transaction is lost. 

### Requirements
Add a `chunk_size=` parameter to `.populate()` allowing a transaction to be fired off once for every N insert calls. If this parameter is not specified, the default is the current default, attempt to perform the entire autopopulate in one transaction 

### Justification
Adding this feature would allow finished work to be saved incrementally in a single autopopulate call. This would make autopopulating tables more error-tolerant and scalable to computationally intensive pipelines, and would reduce the amount of human intervention or supervision needed to run such pipelines. 

### Alternative Considerations
Simply passing `suppress_errors=True` does not solve this issue as sometimes the interruption happens external to python -- for instance, if the transaction hangs, or a crash happens, or the database connection is lost. 

A workaround would be wrapping populate calls in a for-loop or a while-loop and passing `max_calls`, or using constraints to limit the size of each transaction, but these constraints (like `200 < id <= 300`) may have no semantic meaning in the operation being performed. Both of these solutions require manual transaction management by the user.

**Comment by guzman-raphael** [comment]
@zhenruiliao Thank you for submitting an issue! Just reviewed your great write-up but had some follow-up questions.

Which DJ Python version are you using? Asking since the one I tested does not behave as you described. If an individual `make` call fails, the previous successful ones should have been committed by default as the transaction is around each individual `make`. Could you share a sample, minimal code that illustrates what you mean?

Another common use-case where it would not commit results from a long processing `make` is if your `make` runs for longer than the configured timeout on MySQL server. For those cases, we recommend either increasing the timeout on the server for all (if it makes sense) or simply increasing the timeout for your particular session.

For instance, take a look at the following snippet:

```python
import datajoint as dj

print(f'DJ Python version: {dj.__version__}')
schema = dj.Schema('raphael_populate')

@schema
class Parent(dj.Lookup):
    definition = """
    id: int
    """
    contents = [
        (1,),
        (2,),
        (3,),
        (4,),
    ]

@schema
class Child(dj.Computed):
    definition = """
    -> Parent
    ---
    square: int
    """

    def make(self, key):
        if key['id'] == 3:
            raise ValueError('Equals 3.')
        self.insert1(dict(key, square=key['id']**2))

# default
try:
    Child.populate()
except ValueError:
    print(Child())
Child.delete_quick()

# skip errors
status = Child.populate(suppress_errors=True)
print(f'status: {status}')
print(Child())
Child.delete_quick()
```

Results in:
```
DJ Python version: 0.13.7
*id    square    
+----+ +--------+
1      1         
2      4         
 (Total: 2)

[2022-08-24 13:06:20,759][ERROR]: Equals 3.
status: [({'id': 3}, 'ValueError: Equals 3.')]
*id    square    
+----+ +--------+
1      1         
2      4         
4      16        
 (Total: 3)
```

**Comment by dimitri-yatsenko** [comment]
@zhenruiliao. To clarify, DataJoint's populate launches a separate transaction for every `make` call. This ensures that the entire body of `make` is executed as an atomic, consistent, isolated, and durable operation. One and only one `make` call is included in each transaction.  Splitting `make` calls into separate transactions would break the purpose of the transaction, which is to ensure that the entire call is executed consistently and completely or not at all.

**Comment by guzman-raphael** [comment]
Closing as resolved but please feel free to reopen if there is more to contribute on this.
