### ISSUE TITLE
Cannot access tutorial, SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by FlorianNeurosci** [datajoint/datajoint-python#1047]
### Description
I hope that this is the correct place for the bug.
I cannot access the tutorial website due to expired certificate. I get this error message:
Websites prove their identity via certificates, which are valid for a set time period. The certificate for tutorials.datajoint.io expired on 7/27/2022.

Hope it can be fixed soon, thanks in advance!

**Comment by kabilar** [comment]
Hi @FlorianNeurosci, you can access the tutorials at https://tutorials.datajoint.org or interactive tutorials at https://codebook.datajoint.io.  Thank you.

**Comment by FlorianNeurosci** [comment]
Those links work. so it seems to be just the tutorial link link on this website then. 
Thanks a lot!

**Comment by kabilar** [comment]
Thank you for the report.  That will be addressed in this pull request: https://github.com/datajoint/datajoint.org/pull/21

**Comment by yambottle** [comment]
We also made a redirect page [tutorials.datajoint.io](tutorials.datajoint.io) to [tutorials.datajoint.org](tutorials.datajoint.org)
