### ISSUE TITLE
Hidden Attributes

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#1060]
### Problem

Implement support for hidden attributes. These attributes will be prefixed with an underscore and not displayed.  DataJoint may store metadata like creation timestamps, usernames, etc in the hidden attributes. U

### Requirements
* DataJoint will support hidden attributes in tables. Any attribute whose name begins with a `_` will not be displayed and will not appear as part of the reverse-engineered table definition. 
* DataJoint declaration will allow declaring such attributes for internal purposes but the user API will be prohibited (by default) from using them.
* Hidden attributes will not participate in joins. 
* Hidden attributes will not be included in results of user queries

### Justification
* The singleton tables in #113 will be supported by a hidden attribute
* Automated metadata such timestamps, data versions, checksums, and usernames will use hidden attributes

**Comment by CBroz1** [comment]
@A-Baji - Do you have a sense of your timeline for #1091? I think it could be really useful for something I'm working on

**Comment by A-Baji** [comment]
> @A-Baji - Do you have a sense of your timeline for #1091? I think it could be really useful for something I'm working on

Hey Chris! I think that PR has just been waiting for a review from @dimitri-yatsenko. If any changes are requested feel free to PR to me with the fixes as I'm not currently working on any of the open source projects.

**Comment by dimitri-yatsenko** [comment]
Fixed in #1091
