### ISSUE TITLE
dj.table.insert() datajoint.errors.DataJointError: Attempt to insert rows with different fields.

### ISSUE THREAD

**Issue by yambottle** [datajoint/datajoint-python#1069]
### Description
Trying to insert a list of dict with subset of the fields:
table defination:
```
A: int
---
B=NULL: float
C=NULL: float
D =NULL: float
```
 
```
records = [{"A":1, "B": 1.1}, {"A":2, "C":2.1}]

# error: datajoint.errors.DataJointError: Attempt to insert rows with different fields.
table.insert(records)

# no error
for record in records:
    table.insert1(record)
```
Expected table content:
| A | B | C | D |
|---|---|---|---|
| 1 | 1.1 | nan | nan |
| 2 | nan | 2.1 | nan 

### Reproducibility
Include:
- OS (MACOS)
- Python Version 3.9
- MySQL Version 8.0
- MySQL Deployment Strategy (remote)
- DataJoint Version 0.13.8
- Minimum number of steps to reliably reproduce the issue
```
import datajoint as dj
schema = dj.Schema("bug_reproduce")
@schema
class table(dj.Manual):
    definition = """
    A: int
    ---
    B = NULL: float
    C = NULL: float
    D= NULL: float
    """

records = [{"A":1, "B": 1.1}, {"A":2, "C":2.1}]

# error: datajoint.errors.DataJointError: Attempt to insert rows with different fields.
table.insert(records)

# no error
for record in records:
    table.insert1(record)
```
- Complete error stack as a result of evaluating the above steps
```
Traceback (most recent call last):
 .............
    table.insert(records)
  File "/opt/anaconda3/envs/dj/lib/python3.9/site-packages/datajoint/table.py", line 409, in insert
    rows = list(
  File "/opt/anaconda3/envs/dj/lib/python3.9/site-packages/datajoint/table.py", line 410, in <genexpr>
    self.__make_row_to_insert(row, field_list, ignore_extra_fields)
  File "/opt/anaconda3/envs/dj/lib/python3.9/site-packages/datajoint/table.py", line 895, in __make_row_to_insert
    check_fields(row)
  File "/opt/anaconda3/envs/dj/lib/python3.9/site-packages/datajoint/table.py", line 885, in check_fields
    raise DataJointError("Attempt to insert rows with different fields.")
datajoint.errors.DataJointError: Attempt to insert rows with different fields.
```

### Expected Behavior
| A | B | C | D |
|---|---|---|---|
| 1 | 1.1 | nan | nan |
| 2 | nan | 2.1 | nan 

### Additional Research and Context
Found logic bug in the [check_fields](https://github.com/datajoint/datajoint-python/blob/3b6e845885f074396d6981585f6bb2e1b4d5cea9/datajoint/table.py#L907-L908)
It shouldn't be `if insert_fields != defined_fields`, instead it should be `if insert_fields is the subset of defined_fields`, and I'm not sure if this would handle the default NULL case.

**Comment by dimitri-yatsenko** [comment]
This has to do with how `insert` statements work. You must specify all the fields you are inserting. We infer the field names from the first record and then assert that all subsequent once are the same.

An alternative solution could be to through all the records first to collect all fields names and then fill in the missing ones with `DEFAULT` in each record. It's not too difficult to implement but it requires an extra sweep through the data. The data could be coming from a generator, so an extra sweep may require more processing/memory.

I would not consider this a bug. The behavior is as specified. We require that all dicts in a sequence must have the same fields at insert.
