### ISSUE TITLE
Submit datajoint to PyPI

### ISSUE THREAD

**Issue by FloFra** [datajoint/datajoint-python#11]
Once all the new features are added, I think datajoint should be submitted to PyPi, so it can be installed by just typing ```pip install datajoint```.

More information on how to submit a package to the PyPi repostory can be found [here](https://packaging.python.org/en/latest/tutorial.html#uploading-your-project-to-pypi).

This will also require us to think about how we are going to version the python interface of datajoint. I guess it would be the easiest to just use the same major and minor version number as in matlab to show SQL data structure compatibility.

**Comment by eywalker** [comment]
Test submission to PyPI is now complete, and DataJoint version 0.1.0.dev3 is now made available for install with `pip install datajoint`. Will work on streamlining the release process on PyPI.

**Comment by eywalker** [comment]
I have now implemented `make` based routine for uploading packages to PyPI. Will wait for #111 to be fixed and pulled in before I rebase my changes.

**Comment by eywalker** [comment]
Support for PyPI is now integrated, and DataJoint can be installed via `pip install datajoint`. Makefile has been added to semi-automate the process of uploading new package to PyPI.
