### ISSUE TITLE
A method for altering the definitions of tables with data

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#110]
I propose to have a single `alter` method in `dj.Relation`.  It will take the current definition and update the table definition.  

This will require computing the difference between the current definition and the new definition and generating alter commands to update the definition. 

Two methods:
`preview_alter(self)` -- shows the required changes
`alter(self, data_loss_ok=False, preview_only=False)` -- executes the changes

**Comment by fabiansinz** [comment]
Agreement from my side.

**Comment by dimitri-yatsenko** [comment]
This may be helpful: https://github.com/djrobstep/migra
