### ISSUE TITLE
Broken image/diagram in docs: design/diagrams/#example

### ISSUE THREAD

**Issue by CBroz1** [datajoint/datajoint-python#1101]
[This file](https://github.com/datajoint/datajoint-python/blob/master/docs/src/design/diagrams.md) and [this file](https://github.com/datajoint/datajoint-python/blob/master/docs/src/design/tables/tiers.md) reference [this diagram](https://github.com/datajoint-company/datajoint-docs/blob/main/src/images/concepts-table-tiers-diagram.md). Because these are now in separate repos, the rendered site ([e.g.](https://datajoint.com/docs/core/datajoint-python/0.14/design/diagrams/#example))  fails to load the image

**Comment by CBroz1** [comment]
It's also the case that most of the links on this page are broken

**Comment by kabilar** [comment]
Thanks @cbroz1.  Today, we just completed a migration of the DataJoint Python [legacy docs](https://docs.datajoint.org/python/) to the [new docs](https://datajoint.com/docs/core/datajoint-python/) in https://github.com/datajoint/datajoint-python/pull/1096.  Most links on the pages should now be fixed.  In future updates to the new docs, we will be updating all diagrams with the styling/notation of `dj.Diagram`.

**Comment by CBroz1** [comment]
Thanks @kabilar
