### ISSUE TITLE
insert and insert1

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#114]
Currently, `Relation.insert` inserts one tuple whereas `Relation.batch_insert` inserts a collection of tuples from an iterable.

I propose that these be renamed to `insert1` and `insert`, respectively. This will make them symmetric with `fetch`/`fetch1`.

**Comment by fabiansinz** [comment]
Agreed.

On 07/05/2015 12:02 AM, Dimitri Yatsenko wrote:
>
> Currently, |Relation.insert| inserts one tuple whereas
> |Relation.batch_insert| inserts a collection of tuples from an iterable.
>
> I propose that these be renamed to |insert1| and |insert|,
> respectively. This way make |insert|/|insert1| symmetric with
> |fetch|/|fetch1|.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datajoint/datajoint-python/issues/114>.
>

-- 
Dr. Fabian Sinz
contact info: http://goo.gl/o87zXC

**Comment by fabiansinz** [comment]
I fixed that in my local version already. You don't need to change it. I'll make a pull request once @dimitri-yatsenko tests are in.

**Comment by dimitri-yatsenko** [comment]
fixed in 3806c75d
