### ISSUE TITLE
implement table modifying functions

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#115]
We are still missing the following functions, which are provided in Matlab

```
  dj.Table/addAttribute
  dj.Table/alterAttribute
  dj.Table/dropAttribute

  dj.Table/addForeignKey
  dj.Table/dropForeignKey

  dj.Table/addIndex
  dj.Table/dropIndex

  dj.Table/setTableComment
```

Once that is done, update the help page `2015-05-05-modifyingtables.md` in datajoint.github.io.

**Comment by dimitri-yatsenko** [comment]
This were removed in preparation of implementing a single `update` method in issue #110.  Closing.
