### ISSUE TITLE
How to log/print in computed table

### ISSUE THREAD

**Issue by Hegelim** [datajoint/datajoint-python#1166]
Suppose I have defined some computed table schema that looks like the following
```
def make(self, key):
        source = self.key_source

        # Debugging key source
        logging.info(f"Key Source: {source}")
        logging.info(f"Key: {key}")

        key_dict = (source & key).fetch1()
        logging.info(key_dict)
        logging.debug(key_dict)
        print(key_dict)
```
Suppose this is for class A, and I want to run A().populate(). I have tried logging/print/logging to file, but none of them work. How to properly log/print/debug?

**Comment by CBroz1** [comment]
Those logging.info and print statements should be visible when called by default. If not, that's more likely an issue with how the populate is being called (jupyter, ipython, etc. config), and not an issue with datajoint

logging's [FileHandler](https://docs.python.org/3/library/logging.handlers.html#filehandler) ([demo](https://docs.python.org/3/howto/logging-cookbook.html#logging-cookbook)) should be able to add logging to a file in addition to the standard printout. Doing so could be a sanity check that the code is running

**Comment by dimitri-yatsenko** [comment]
Is this still an issue?  This seems like a logger configuration issue, not datajoint specific. We plan to close this issues unless we get a clarification.

**Comment by dimitri-yatsenko** [comment]
Please re-open if this is still an issue.
