### ISSUE TITLE
InternalError: (1054, "Unknown column 'nan' in 'field list'") when writing 'nan' to double field

### ISSUE THREAD

**Issue by leongatys** [datajoint/datajoint-python#118]
Hi guys,
I try to write some data that has some 'nan' entries into a field with datatype double and get the following error: InternalError: (1054, "Unknown column 'nan' in 'field list'"). 
Alex said in the matlab version writing nan's into tables works, so this seems to be python specific. I googled the problem and it seems that this could be a problem with pymysql/pandas.
Below is the complete error traceback: 
InternalError                             Traceback (most recent call last)
<ipython-input-4-00226f6f60da> in <module>()
      4         if stim_id < 1750:
      5             schemata.EstimatedResponses().insert({'stim_id': stim_id, 'subject_id': 0,
----> 6                                                'voxel_id': vox_id, 'response': resp['dataTrnS1'][stim_id,vox_id]})
      7         else:
      8             schemata.EstimatedResponses().insert({'stim_id': stim_id, 'subject_id': 0,

/usr/local/lib/python3.4/dist-packages/datajoint/relation.py in insert(self, tup, ignore_errors, replace)
    195         sql += " INTO %s (%s) VALUES (%s)" % (self.from_clause, attribute_list, value_list)
    196         logger.info(sql)
--> 197         self.connection.query(sql, args=args)
    198 
    199     def delete(self):

/usr/local/lib/python3.4/dist-packages/datajoint/connection.py in query(self, query, args, as_dict)
    106         # Log the query
    107         logger.debug("Executing SQL:" + query)
--> 108         cur.execute(query, args)
    109         return cur
    110 

/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py in execute(self, query, args)
    132             query = query % self._escape_args(args, conn)
    133 
--> 134         result = self._query(query)
    135         self._executed = query
    136         return result

/usr/local/lib/python3.4/dist-packages/pymysql/cursors.py in _query(self, q)
    280         conn = self._get_db()
    281         self._last_executed = q
--> 282         conn.query(q)
    283         self._do_get_result()
    284         return self.rowcount

/usr/local/lib/python3.4/dist-packages/pymysql/connections.py in query(self, sql, unbuffered)
    766                 sql = sql.encode(self.encoding, 'surrogateescape')
    767         self._execute_command(COMMAND.COM_QUERY, sql)
--> 768         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    769         return self._affected_rows
    770 

/usr/local/lib/python3.4/dist-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
    927         else:
    928             result = MySQLResult(self)
--> 929             result.read()
    930         self._result = result
    931         if result.server_status is not None:

/usr/local/lib/python3.4/dist-packages/pymysql/connections.py in read(self)
   1123     def read(self):
   1124         try:
-> 1125             first_packet = self.connection._read_packet()
   1126 
   1127             if first_packet.is_ok_packet():

/usr/local/lib/python3.4/dist-packages/pymysql/connections.py in _read_packet(self, packet_type)
    891                 break
    892         packet = packet_type(buff, self.encoding)
--> 893         packet.check_error()
    894         return packet
    895 

/usr/local/lib/python3.4/dist-packages/pymysql/connections.py in check_error(self)
    367             errno = self.read_uint16()
    368             if DEBUG: print("errno =", errno)
--> 369             err.raise_mysql_exception(self._data)
    370 
    371     def dump(self):

/usr/local/lib/python3.4/dist-packages/pymysql/err.py in raise_mysql_exception(data)
    118 def raise_mysql_exception(data):
    119     errinfo = _get_error_info(data)
--> 120     _check_mysql_exception(errinfo)

/usr/local/lib/python3.4/dist-packages/pymysql/err.py in _check_mysql_exception(errinfo)
    113 
    114     # couldn't find the right error number
--> 115     raise InternalError(errno, errorvalue)
    116 
    117 

InternalError: (1054, "Unknown column 'nan' in 'field list'")

**Comment by eywalker** [comment]
Just quickly looking at it, it looks like you are trying to insert a
dictionary, rather than a list of dictionary into the schema. `insert`
method expects a list of dictionary, so surround your dictionary with a [ ]
, try again, and please let us know.

**Comment by leongatys** [comment]
When I put [ ] around the dictionary it gives "DataJointError: Datatype <class 'list'> cannot be inserted"
Also all other tuples could be inserted fine with just giving a dictionary - it was only the one that had a 'nan' value.

**Comment by eywalker** [comment]
I see. I also noticed that we haven't pull in the change that would have made `insert` only accept a list of tuples, so that couldn't have been the problem either. Could you turn on the `logging` at `debug` level by inserting the following code somewhere early in your code:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
This will cause all SQL queries to be displayed on your screen.

**Comment by leongatys** [comment]
did it, the only further output is: 
INFO:datajoint.relation:INSERT INTO `lgatys_fmri`.`estimated_responses` (`stim_id`,`subject_id`,`voxel_id`,`response`) VALUES (0,0,49,nan)
DEBUG:datajoint.connection:Executing SQL:INSERT INTO `lgatys_fmri`.`estimated_responses` (`stim_id`,`subject_id`,`voxel_id`,`response`) VALUES (0,0,49,nan)

**Comment by dimitri-yatsenko** [comment]
MySQL's `double` and `float` types do not represent `nan` or `inf`.  The way we handled nans in matlab is convert them to nulls.  It's a strange design choice for MySQL not to use IEEE standards.

**Comment by dimitri-yatsenko** [comment]
We need to add special handling of nans` in `float` and `double` fields.  I am not sure what to do about `inf`.

In blobs, of course, there is no problem storing normal doubles.

**Comment by eywalker** [comment]
Because `nan` is a valid double value and is relatively straightforward to implement with `NULL`, I think we should just go ahead and implement this conversion. As far as I can tell, there is no simple way to implement support for `inf`, so we should add this to *wontfix* category and document it well.

**Comment by dimitri-yatsenko** [comment]
We can handle it the same way as on the MATLAB side:  If the value is `nan`, the attribute is removed from the tuple and the default value is used.  The user may choose to set the default value to `NULL` and that's how `nan` will be represented.

**Comment by dimitri-yatsenko** [comment]
Fixed.  Attributes of numeric types are omitted from the insert if their values are `nan`.  If the value is null, then a nan is returned by `fetch`.   Therefore, if you wish to be able to store nulls, make the attribute nullable. 

Example: (`test/test_nan.py`)
```python
import numpy as np
from nose.tools import assert_true
import datajoint as dj
from . import PREFIX, CONN_INFO


schema = dj.schema(PREFIX + '_nantest', locals(), connection=dj.conn(**CONN_INFO))


@schema
class NanTest(dj.Manual):
    definition = """
    id :int
    ---
    value=null :double
    """


def test_insert_nan():
    rel = NanTest()
    a = np.array([1, 2, np.nan, np.pi, np.nan])
    rel.insert(((i, value) for i, value in enumerate(a)))
    b = rel.fetch.order_by('id')['value']
    assert_true((np.isnan(a) == np.isnan(b)).all(),
                'incorrect handling of Nans')
    assert_true(np.allclose(a[np.logical_not(np.isnan(a))], b[np.logical_not(np.isnan(b))]),
                'incorrect storage of floats')
```
