### ISSUE TITLE
Python computed table: TypeError: Can't instantiate abstract class XXX with abstract methods populate_relation

### ISSUE THREAD

**Issue by leongatys** [datajoint/datajoint-python#119]
EDIT: Sorry, already found the problem, 'populate_from' is now called 'populate_relation'

Hi,
I am trying to define a computed table in datajoint python. 
I define the table as
```python
@database
class ReceptiveFields(dj.Computed):
        definition = """
        ...
        """

        @property
        def populate_from(self):
                return schemata.Voxels()


        def _make_tuples(self, key):
              ...
              self.insert1(key)
```
following the tutorial here: http://datajoint.github.io/2015/05/05/populating/
But when I try to create the table I get the error:
```python
/gpfs01/bethge/home/lgatys/caffe_projects/FMRIProject/datajoint/schemata.py in <module>()
     49 
     50 @database
---> 51 class ReceptiveFields(dj.Computed):
     52 	definition = """
     53         -> Voxel

/usr/local/lib/python3.4/dist-packages/datajoint/relation.py in decorator(cls)
     47         cls._connection = connection
     48         cls._heading = Heading()
---> 49         instance = cls() if isinstance(cls, type) else cls
     50         if not instance.heading:
     51             connection.query(

TypeError: Can't instantiate abstract class ReceptiveFields with abstract methods populate_relation
```
Was there a change in how to define computed tables? Or am I just not seeing some mistake here? 

Best
Leon

**Comment by dimitri-yatsenko** [comment]
It should be `populated_from`, not `populate_from`.  I wish Python would say that more explicitly.  

But our newest version that's not yet merged has a default `populated_from` whose value is the join of the parents of the table.

**Comment by dimitri-yatsenko** [comment]
Which version are you using?  We have made lots of changes but because the tests are not yet complete, we have not yet merged to the master.

**Comment by fabiansinz** [comment]
I fixed the typo on the website. @leongatys your contribution as beta-tester is really valued. Thanks a lot for the feedback.
