### ISSUE TITLE
Delete unused branches and create development branch

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#123]
The development branch is allowed to have failing tests. That way it would be easier to exchange features that are under development instead of cross-pulling them from each other's forks. Pull requests are only accepted into the master branch if they pass all travis tests. Additionally, we should add a tag v0.1 to the release commit.

**Comment by dimitri-yatsenko** [comment]
agreed

**Comment by fabiansinz** [comment]
Quick vote: Anyone against deleting the branches future and decorator?

**Comment by dimitri-yatsenko** [comment]
go ahead

**Comment by eywalker** [comment]
Go ahead
