### ISSUE TITLE
Terminology consistency: Schema vs Database

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#127]
Working through the code now, I've noticed that the reference to terms *schema* and *database* are interspersed throughout the code and documentation, and used interchangeably. I suggest that we stick to one for consistency in documentation. Since we ask users to use `dj.schema` in defining *schema* handle, I would think it makes sense the most try to stick to *schema* throughout our code.

**Comment by dimitri-yatsenko** [comment]
Let's use database for MySQL schemas (databases).

**Comment by fabiansinz** [comment]
I agree.

**Comment by eywalker** [comment]
Sounds good. I'll go with the idea that we use Database to refer to MySQL database (schema). We'll stick with the word `schema` to refer to the schema object that's used to decorate tables. Supposedly, these represent a conceptual grouping of Python code (using DataJoint) paired with MySQL database.
