### ISSUE TITLE
Random numbers in tests

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#128]
From test repeatability stand point, we should avoid introducing randomness in the test design. Currently, some of the test schemas generate tuples via random combination of keys. Although it generates nice realistic data quickly, he fact it will change the content of tables from run to run may be a source of nightmare in the future debugging! When you use `random` or `np.random`, please make sure to seed it with a fixed value **right before the usage**. Seeding at the top of the module is not enough as different parts gets executed in different order, making the seed pointless.

**Comment by dimitri-yatsenko** [comment]
agreed

**Comment by dimitri-yatsenko** [comment]
In `_make_tuples` methods, I use
```python
random.seed(str(key))
```
to ensure that the seed is different yet repeatable for every key
