### ISSUE TITLE
`__str__` and `__repr__` for RelationalOperand

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#136]
Currently the `__repr__` for `RelationalOperand` prints out the heading as well as the first few rows of the query. Although this is a very useful representation for a quick inspection of the table (or result of relational operations) content, it makes debugging quite annoying as quick inspection of the `RelationOperand` both executes the query and prints out often times massive table. As succinctly stated in Python's documentation on [`__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__), the `__repr__` is meant to be used during debugging, providing *unambiguous* information about the object (this concept is also well described [here](http://satran.in/2012/03/14/python-repr-str.html)).

Given this, I propose two alternatives:

1. Move the current verbose string representation found in `__repr__` into `__str__`, and supply more succinct but useful-for-debugging string representation in `__repr__` (e.g. relational operation that yielded the current object). In fact, if `__repr__` can contain the full description of how it was produced, that'd be useful. If a user would want to see what the relation's content looks like, it can be viewed via `print(relation)`

2. Since I understand that being able to just type in the name of relation at the interactive Python to get content preview is quite nice, we could add a config flag that controls the behavior of the `__repr__` . We would ship DataJoint with this config flag default to something like `preview`, causing `__repr__` to print out the preview of the table content as it does already. When debugging, the config flag can be set to `debug` with more succinct `__repr__` behavior.

Although I think option 1  follows the mantra of Python language, packages like `pandas` use option 2, defaulting to verbose `__repr__` useful during interactive programming.

**Comment by fabiansinz** [comment]
I think option 1) would be the clean way, but I think we probably want option 2). You could check the debug level in `dj.config` and change the behavior of `__repr__` if it is set to `DEBUG`.

**Comment by dimitri-yatsenko** [comment]
How about moving the table preview into the fetch object?

**Comment by eywalker** [comment]
We'll have it such that `__repr__` on `RelationalOperand` only outputs information about how it was constructed. To view the content preview, user can simply look at the `rel.fetch` - the `__repr__` for `Fetch` object will provide with the preview of the content. This is consistent with the idea that it's only `Fetch` object that will execute the query.

**Comment by dimitri-yatsenko** [comment]
With all the new features, constructing a useful representation for debugging is very difficult and requires additional computations.  I don't think it is reasonable to produce a very informative `__repr__`.  Developers have much better tools for inspecting the objects than `__repr__`.

I propose to remove all `__repr__` and `__str__` features other than a preview of the relation's contents when the debug mode is off.

I about to close this as a won't fix.

**Comment by dimitri-yatsenko** [comment]
Addressed in 4debbd88f
