### ISSUE TITLE
document and test modules

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#141]
Ok, here's the distribution of tasks:

@dimitri-yatsenko 
- auto_populate.py
- jobs.py
- relational_operand.py
- blob.py
- declare.py
- __init__.py

@eywalker 
- connection.py
- erd.py
- heading.py
- schema.py

@fabiansinz
- user_relations.py
- fetch.py
- relation.py
- settings.py
- utils.py

**Comment by dimitri-yatsenko** [comment]
Which documentation is this referring to?  How do I edit?

**Comment by fabiansinz** [comment]
It is referring to the documentation that gets produced when you type in `make html` in the doc directory. That should automatically be updated by readthedocs. There is a problem with this at the moment. I suspect because readthedocs does not provide some libraries and we have to create mock libraries for that. I will fix that. You can use the local version for the time being. You edit it by creating the necessary *.rst files and referring to the modules in question. Just look at the examples in the doc folder and let me know if there are problems.

**Comment by dimitri-yatsenko** [comment]
Should we remove this and rely on online tutorials for documentation?

**Comment by fabiansinz** [comment]
Would still be nice to have a documented API.

**Comment by dimitri-yatsenko** [comment]
Would you please add this?  I am not quite sure how it is meant to work and this is the only issue that keeps meeting milestone requirements for "Release v0.1".

**Comment by fabiansinz** [comment]
Since sphinx and readthedoc can a bit of a pain sometimes and because the [tutorials](https://github.com/datajoint/ipython-notebook-tutorial) provide a better source for learning datajoint, I am closing this with _wontfix_.
