### ISSUE TITLE
add the `skip_duplicates` option to `Relation.insert1`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#148]
We often insert values that may already exist.  The most common example is the filling of lookup tables.  To suppress duplicate entry errors, we use the `ignore_errors` flag.  It does the job but it also suppress other errors such as incorrect attribute names.  I propose adding the `skip_duplicates` attribute to `Relation.insert`.

**Comment by fabiansinz** [comment]
Agreed.

**Comment by eywalker** [comment]
Yep, sounds like a good idea.

**Comment by dimitri-yatsenko** [comment]
It does not appear that there is a solution on the MySQL site, so we have to check for duplicates explicitly.
http://stackoverflow.com/questions/548541/insert-ignore-vs-insert-on-duplicate-key-update

So `insert1` should check if the new entry is a duplicate first.  I am debating whether a transaction is necessary to include both the check and the insert, but it's probably not worth the trouble.

**Comment by fabiansinz** [comment]
solved by  #149
