### ISSUE TITLE
cascading delete

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#15]
see `dj.Relvar/del`  on the MATLAB side.

**Comment by eywalker** [comment]
First pass version of cascading delete is now implemented. As far as I could test, it works appropriately. However, it is crucial that we add more tests for complex relational operation. In particular, we would need to add test cases for `delete` and combination of `delete`, `restrict`, and `project`.

I'll try adding test cases covering cascading as well as normal deletes hopefully within today.

**Comment by eywalker** [comment]
There is a known bug in the cascading delete where restricted deletion on tables with multiple dependency to the source table may be incorrect. Fix will be implemented soon...

**Comment by dimitri-yatsenko** [comment]
mostly solved in e0aadc03. 

There is one non-critical case when delete fails to cascade correctly, but this case has never happened in real schemas.  This case only concerns multiple dependence paths through non-primary dependencies.

**Comment by eywalker** [comment]
Yes, but the solution is known and thus there is no reason not to implement
the fix :)
