### ISSUE TITLE
restrictions by a list

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#158]
Recently we introduced a discrepancy of what it means to restrict by a list of objects.  

Initially, restricting by a list combined the conditions using OR.  Recently we overrode this feature and combined conditions using AND. 

I believe, that restricting by a list or an array of conditions should be an OR operation.  This is how the MATLAB version handles it also.  With this convention, a collection of restrictions can be thought of as another relation and semijoins and restrictions become equivalent:

For example, the following two restrictions should produce the same result:
```python
A() & B()
A() & B().fetch()
```

At the same time, we need to be able to combine a list of restrictions using AND in some cases, internally. This is necessary when apply the list of restrictions from one relation to another relation, for example.

**Comment by dimitri-yatsenko** [comment]
This also means that
```python
A() & []
```
will return an empty relation.
Currently it returns `A()`.

**Comment by dimitri-yatsenko** [comment]
Actually, I am not sure what `A() & []` should mean. I think my previous comment was wrong.  It should return `A()` since every condition in `[]` is met.

**Comment by fabiansinz** [comment]
If it is OR, then it should return `A()`.

**Comment by dimitri-yatsenko** [comment]
What about `A() - []` then?  It seems that it should be ```A()``` too.  I sense a contradiction.

But this would be inconsistent with `semijoin`:  `rel & empty_relation` is empty if `empty_relation` has common attributes with `rel`.

**Comment by dimitri-yatsenko** [comment]
The definition of restriction `rel & conditions` is: "All tuples in `rel` that meet any of the conditions in `conditions`".

With this definition, `rel & []` is empty and `rel - []` is `rel`.

**Comment by fabiansinz** [comment]
I don't think that `A() - []` should be `A()`. By the above logic it should be empty. However

- I agree that `A() - []` and `A() & []` should yield opposite results. 
- I think that `A() & []` being `A()` is intuitive, but `A() - []` being empty is not. 
- As I pair I think `A() & []` being empty and `A() - []` being `A()` is more intuitive than the opposite combination. 

Therefore, I agree with you.

**Comment by dimitri-yatsenko** [comment]
Conclusions
---
After off-line discussion with @fabiansinz:

`rel & [cond1, ..., condn]` is defined as "a relation comprising all tuples from `rel` that match *any* of the conditions in the list."

Then the following will always result in an empty relation:
```python
rel & []
rel & ()
rel & set()
```

Then the negative restriction will return the original relation:
```python
rel - []
rel - ()
rel - set()
```

These definitions are consistent with the concepts of  *semijoin* and *antijoin* for which we use the same operators `&` and `-`, respectively.

The semijoin `rel & other_rel` can be considered as a restriction by a list of tuples from `other_rel`.  It is defined as "all tuples from `rel` that *match* any tuple in `other_rel`".  Two tuples are considered *matching* unless they have commonly named attributes with different values. 

It follows then that ```rel & other_rel``` is empty if `other_rel` is empty, no matter what the headings of the two relations are.

It follows also that, if two relations have no common attributes, than ```rel & other_rel``` is always `rel` if `other_rel` is not empty.

The empty dictionary `{}` is a single tuple with no attributes.  Therefore, it matches any tuple.

Then `rel & {}` and `rel & [{}]` and `rel & [{}, cond1, cond2]` always yield `rel` no matter what the other conditions are.

**Comment by eywalker** [comment]
Did any of the stuff I discussed with you get used? :D

**Comment by dimitri-yatsenko** [comment]
Basically, none of this is new and this is how datajoint-matlab has always worked.  We have recently introduced a bug that broke this and we needed to go through the exercise of explaining the logic of restrictions again.  This will be described in the tutorial.

**Comment by dimitri-yatsenko** [comment]
Further, since we do not have the concept of a relation of relations and restricting by a list is similar to restricting by a relation, then we shall not allow relations or other lists in restricting lists:

These will raise errors:
```
rel & [other_rel]
rel & [[cond1, cond2], cond3]
```
No nesting.
