### ISSUE TITLE
cascading table drop

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#16]
Make `datajoint.Base.drop` cascade. 

see dj.Table/drop on the matlab side for reference.

**Comment by dimitri-yatsenko** [comment]
After dropping tables, an attempt to instantiate a base relation with this table throws a `pymysql.err.ProgrammingError: (1146, "Table schema.table_name doesn't exist")`

I think this behavior makes sense and does not require addressing.

**Comment by fabiansinz** [comment]
Could we implement a class method to re-declare the table?

**Comment by dimitri-yatsenko** [comment]
First, this solution would not necessarily require a class method.

Second, I think the current behavior is simpler and more intuitive.  Tables are declared at class declaration time.  Dropping a table means that the class is no longer usable (as well as its instances) and it must be re-declared.

**Comment by dimitri-yatsenko** [comment]
However, currently, dependencies are not cleared.  

ERDs will still show the dropped tables.  This probably needs to be fixed.

**Comment by dimitri-yatsenko** [comment]
fixed in 3806c75d
