### ISSUE TITLE
support datatypes VARBINARY and BINARY

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#160]
We have not supported these previously. 

Should we support SET too? 

Here are all the datatypes, for reference: https://mariadb.com/kb/en/mariadb/data-types/

**Comment by dimitri-yatsenko** [comment]
Also DATETIME and YEAR types are not yet supported.  We probably should.

**Comment by Visdoom** [comment]
Is this support fix for the release 10?

**Comment by dimitri-yatsenko** [comment]
I am dropping BIT from this list since there is no equivalent type in MATLAB and Python. 
I am removing TEXT since we recommend using blobs for storing large texts with compression.

**Comment by dimitri-yatsenko** [comment]
I am proposing to close this issue after the upcoming release that will allow storing bytestings into blobs.
