### ISSUE TITLE
Signals and hooks

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#168]
@eywalker and me discussed implementing signals for certain events in datajoint. Use cases for that would be 
- Trigger the generation of plots once new data comes in. This would be for continuous quality monitoring or static websites that cannot trigger the generation of the plots by themselves. 
- Trigger the deletion of plots if a corresponding entity from the database is removed. 
- Trigger `populate` on other relations on the insertion of new data. 
- Replace `_prepare` by a more general mechanism.

I think that the following levels of signals might be desirable:
- object level signals (if something has been inserted via a particular instance)
- class level signals (if something has been inserted in any instance of that class)
- global signals

So far, I can think about the following events:
- class object has been created
- instance has been created
- insert, delete, drop (instance and class level)
- database connection lost, re-established
- populate has finished

I would like a syntax of the following form

``` python
@schema
class MyRelation(dj.Manual):
    definition = """
    idx           : int # example
    ---
    name      : varchar(50)
    """

    @dj.on_insert(scope='class')
    def email(self):
        # do something
```

**Comment by dimitri-yatsenko** [comment]
What's the advantage over overriding the respective method?
```python
@schema
class MyRelation(dj.Manual):
    definition = """
    idx           : int # example
    ---
    name      : varchar(50)
    """
    def insert(self, *args, **kwargs):
          super().insert(*args, **kwargs)
          self.email(self, *args, **kwargs)
```

**Comment by fabiansinz** [comment]
Overriding works on an instance level, but not on a class or global level. The already existing `_prepare` is an example that cannot be done via overriding. I find `_prepare` pretty useful and I  would like extend that functionality. 

In general, thread safe global signals would allow us to send important information to other instances of the same relation. For example: You could start population jobs via threads. Now one jobs find out that the database server is gone and sends a signal, that causes all other computations to save their current state to the hard disk. I think that would be pretty useful, especially for long-lasting computations. 

In addition, signals would allow you to hook into the "middle" of a existing method. If you don't want to copy the entire method from the mother class, it is harder to do that with overriding, since overriding only allows you to execute the *entire* method form the mother class. 

I am sure @eywalker and I could come up with even more examples, that could elegantly and efficiently be solved by signals.

**Comment by dimitri-yatsenko** [comment]
Testing whether the database server is gone is a quick test that every thread can do independently without intra-thread communication.  

Let's list a few more compelling examples that demonstrate the functional need for this that would then drive the design.

**Comment by dimitri-yatsenko** [comment]
This feature still seems incompletely specified and insufficiently motivated.  Please update or close.  Do we have any compelling use cases?

**Comment by fabiansinz** [comment]
That was me, btw.

**Comment by dimitri-yatsenko** [comment]
Let's keep this in the back of our minds.  This is a very advanced feature for advanced use cases and we have much more basic features for much more common use cases that await implementation.  Even if we revive this, we won't get to it in a long time.

**Comment by fabiansinz** [comment]
Since it is almost trivial to implement, I volunteer if we all accept having the additional dependency of datajoint on [blinker](https://pythonhosted.org/blinker/).

**Comment by dimitri-yatsenko** [comment]
* What are some examples of appropriate reactions for jobs `insert`, `update`, and `delete`?

I am a bit wary about adding such a complex feature that requires users to understand the inner workings of the library and I have not yet visualized a compelling example.  

Perhaps we could add this as an undocumented feature for evaluation and demonstration of use cases as long as it does not interfere with anything and has no effect on performance.   If we find interesting use cases, we can include it in the documentation.

**Comment by dimitri-yatsenko** [comment]
We have done a similar thing with Views (#257).  They seemed like a good idea but, after implementation, I could not come up with examples that would show a clear advantage, and I dropped support of views in #271.

**Comment by fabiansinz** [comment]
I am fine with including it as an undocumented feature so far and try it out.
