### ISSUE TITLE
Dependency loading timing

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#179]
Currently, dependencies among tables are loaded only upon call to the `populate` method. Otherwise, we must first call `load`. This is clearly inconvenient, and we should think of a good strategy to load all the dependencies, but hopefully only as necessary.

**Comment by dimitri-yatsenko** [comment]
Loading dependencies is a somewhat expensive operation.  In pull request #176, dependencies are loaded once at the start of each high-level user-invoked function that requires dependencies: populate, progress, erd, etc.

**Comment by eywalker** [comment]
Hmm based on the modified files in #176, I did not see load getting called from anywhere but populate...

**Comment by eywalker** [comment]
Ah, I see that it's getting called from within `populated_from`. However, this doesn't address the issue of needing to load when performing other operations like `deletion` and `erd`, as well as any look ups like `parents` and `reference`. I suggest that we implement `load` to take on a flag like `force`. When the `force` is set to `False`, it will check whether loading has ever been performed, and if not, perform the loading of dependencies, but not otherwise. We can pass `force=True` at places where it's critical to have correct dependency map (e.g. `populated_from` and `delete`). This was in fact how loading of dependency used to be implemented in the past, and we even had finer granularity for loading.

**Comment by dimitri-yatsenko** [comment]
Dependencies are needed for these operations:
* `drop` 
* `delete`
* the default `populated_from`
* `erd`

The dependencies are loaded once at the start of each of these operations. 

The problem with `force` is that it's not an all-or-nothing deal. New dependencies may need to be loaded as new schemas are imported.  So I would rather load the dependencies completely every time at the start of each of these operations.

**Comment by dimitri-yatsenko** [comment]
All of these methods already load dependencies.  As far as I can tell, there is no standing problem with the code.

**Comment by eywalker** [comment]
Reference to properties like `parents` should trigger loading, if it has not been done yet.

**Comment by eywalker** [comment]
And I completely failed to see that `loading` is already in place in methods like `delete` and `drop` as you said :stuck_out_tongue: 

But now I'm remember more about thoughts that went into the design, and I'm realizing that it's simply not trivial to ensure that properties like `parents` and `children` are in sync with structure with database, aside from calling `load` immediately before invocation. Given this, I now agree that we can just leave the implementation as you had it in #176.
