### ISSUE TITLE
Problem installing datajoint with pip

### ISSUE THREAD

**Issue by modeSolver300** [datajoint/datajoint-python#185]
Hello,

I'm hoping someone can help with the following installation problem.  I tried to install datajoint using pip and after running a command to test datajoint (import datajoint as dj), I get the following error in the python console:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python34\lib\site-packages\datajoint\__init__.py", line 39, in <module>
    from .connection import conn, Connection
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.3\helpers\pydev\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)

Some further details:
- Using python 3.4.2
- While installing datajoint, the automatic installation of NumPy failed.  I had to install it manually afterwards.
- OS: Windows 7

**Comment by fabiansinz** [comment]
Where did you run the import from? ipython3? pycharm? Could you try to run the import from ipython3 to exclude the possibility that it is a pycharm issue?

**Comment by modeSolver300** [comment]
Thanks for the suggestion.  I'll try to import it from ipython3.

Some more details.  I couldn't get pycharm to install it because datajoint is a pre-release and I didn't see a way for pycharm to use the --pre in the pip command (the installation kept failing in the pycharm installation tool).  Instead, I installed it from the windows command prompt while in the python scripts folder.

**Comment by fabiansinz** [comment]
I also seriously recommend not installing the pypi version, but pulling datajoint from github and install it with "pip3 install DATAJOINTFOLDER" (you might need to use pip instead of pip3). If you want to install it in place, use `-e`.
