### ISSUE TITLE
rename `project()` to `proj()`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#202]
This may generate a heated discussion but let's have it now.

The topic is the relational projection operator.  The verb form is _project_ (stress on the last syllable).

In matlab, we implemented it as `Relvar.pro()`.  In Python, we implemented it as `RelationalOperand.project()`.

I propose to rename it to `proj` in both languages while keeping the old methods as aliases for backward compatibility.

This will make the documentation and the tutorials more consistent.

The word `project` looks too much like the noun _project_ (stress on the first syllable), which may be confusing.  I like `proj` because it does not look like the noun _project_, which users may be primed to interpret as a software project.

Since we will keep the old methods for backward compatibility, this will not affect the current code based but the new tutorial will consistently use `proj`.

**Comment by eywalker** [comment]
Accepted - but you owe me one for this.

**Comment by fabiansinz** [comment]
Accepted - I want one "skip feature request discussion" joker for free.

**Comment by dimitri-yatsenko** [comment]
Great.  But no, we will review and question all new features.

**Comment by dimitri-yatsenko** [comment]
Fixed in d29ebe1
