### ISSUE TITLE
`dj.U` not working correctly in restrictions

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#228]
Example from our pipeline. `dj.U('animal_id') & preprocess.ExtractRaw()` yields a relation with several identical `animal_id` values. 
```
*animal_id   
+-----------+
7816         
7816         
9036         
9161         
9161         
9161         
9161         
9161         
9161         
9161         
9161         
9161         
9170         
 (13 tuples)
```

It should yield a set of unique animal ids

The SQL statement is `'SELECT DISTINCT 'animal_id' FROM 'pipeline_preprocess'.'_extract_raw''` looks correct to me and when I paste it into MySQL I get: 

```
mysql> SELECT DISTINCT `animal_id` FROM `pipeline_preprocess`.`_extract_raw`;
+-----------+
| animal_id |
+-----------+
|      7816 |
|      9036 |
|      9161 |
|      9170 |
+-----------+
4 rows in set (0.00 sec)

```

**Comment by dimitri-yatsenko** [comment]
Note that the `len` and `fetch()` work correctly.  Yes, the `DISTINCT` word gets lost when fetching specific attributes. I will think how to fix this.  The easiest way is to enclose inside another subquery, but MySQL sometimes get less efficient with extra subqueries. 
```python
len(dj.U('animal_id') & preprocess.ExtractRaw())
In[1]: 4

len((dj.U('animal_id') & preprocess.ExtractRaw()).fetch())
In[2]: 4

len((dj.U('animal_id') & preprocess.ExtractRaw()).fetch['animal_id'])
In[3]: 15

len(list((dj.U('animal_id') & preprocess.ExtractRaw()).fetch.keys()))
In[4]: 15
```
