### ISSUE TITLE
Should we think of a reasonable way to overload the __getitem__ method of base?

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#23]
It would be nice if we could use that for fetching.

**Comment by dimitri-yatsenko** [comment]
would you list a few suggested use cases?

**Comment by dimitri-yatsenko** [comment]
Maybe the object returned by fetch should provide this rather than Relation itself.

**Comment by dimitri-yatsenko** [comment]
Closing due to lack of specification.
