### ISSUE TITLE
Access log

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#233]
We now have dozens of schemas on our lab's server.  In most cases, we can easily identify to whom they belong and whether they may be removed.  I wonder if it would be helpful to store creation and access information in each schema.  For example, we could have a table called `~access`, which will record events like:

* accessing a schema (one entry each time at the time when the schema module is loaded)
* creation of the schema
* creation of a table
* dropping of a table
* altering of a table definition

This will record the user and the time of the event.

**Comment by dimitri-yatsenko** [comment]
Perhaps the module's doc string will be entered as a comment in the create schema log entry.

**Comment by fabiansinz** [comment]
I think this is a great idea. We should also store the ip where the command came from and also log deletes. I'd call it `~log` though.

**Comment by dimitri-yatsenko** [comment]
implemented in #258
