### ISSUE TITLE
Implement update

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#238]
Datajoint matlab has an update function. Although updates are deeply undatajoyous, it is sometimes needed to fix small bugs in a database.

**Comment by dimitri-yatsenko** [comment]
It will be implemented as `_update` and the docstring will explain that normal usage of datajoint does not rely on updates.

**Comment by dimitri-yatsenko** [comment]
implemented in version 0.3.8  (PR #239)
