### ISSUE TITLE
Implement `farfetch`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#242]
Within `_make_tuples` functions, it may be possible to automate query formation for fetching data that can be uniquely identified by its attribute name. 

For example,

``` python
nslices = (preprocess.Prepare.Galvo() & key).fetch1['nslices'] 
traces  = (preprocess.ExractTraces.Traces() & key).fetch['trace']  
```

would be replaced with 

``` python
nslices, traces = dj.get('nslices', 'traces')
```

This is intended to work from `_make_tuples` only since it will need to know its place in the data hierarchy and the value of `key`.

**Comment by eywalker** [comment]
An alternative suggestion for the syntax.

```python
search = self.search(key)
nslices = search['nslices']

# tables containing the attributes are joined if they are in the same search call
traces, rois = search['trace', 'roi']
```

**Comment by dimitri-yatsenko** [comment]
I like it.  This will allow more portable code that relies on descriptive attribute names and survives changes in the schema design.

**Comment by dimitri-yatsenko** [comment]
Another discussion and a different syntax. 

```python
nslices = (self & key).search1['nslices']      # fetch nslices as a scalar.

# tables containing the attributes are joined if they are in the same search call
traces, rois = (self & key).search['trace', 'roi']      # fetch matched traces and ROIs from different tables
```

**Comment by dimitri-yatsenko** [comment]
Another syntax
```python
nslices = self.get1(key, ['nslices'])      # fetch nslices as a scalar.

# tables containing the attributes are joined if they are in the same search call
traces, rois =  self.get(key, ['trace', 'roi']) 
```

**Comment by eywalker** [comment]
Between the last two, I'd prefer the `search.fetch1` and `search.fetch` syntax, allowing us to not repeat `key` argument.

**Comment by fabiansinz** [comment]
I agree with @eywalker although I'd still prefer to rename `search` into something else.

**Comment by eywalker** [comment]
Do we have running candidates on what to rename `search` to?

**Comment by dimitri-yatsenko** [comment]
I propose the name `farfetch`. It's catchy.

**Comment by dimitri-yatsenko** [comment]
I am removing this since this can lead to indeterministic behaviors. In the Pipeline Navigator and with new AI-based tools, we will provide tools for composing queries, but queries must be precise.
