### ISSUE TITLE
Insert target table primary key in job table

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#243]
Currently the primary key of the target table that is getting populated via `reserve=True` is _not_ inserted into the `jobs` table, making it difficult to identify on which primary key on the target table that the job is working on, or has encountered an error when populating.

The primary key of the target table should be inserted at the time of the job reservation.

**Comment by eywalker** [comment]
Insertion of target table primary key will be implemented as soon as issue #244 is resolved.

**Comment by dimitri-yatsenko** [comment]
This has been fixed for some time now.  Need to add a test and close.

**Comment by dimitri-yatsenko** [comment]
This was fixed in #316.  Closing.
