### ISSUE TITLE
Use of MySQL keywords in table attributes

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#249]
If MySQL keywords (e.g. `key`) is used as the name of an attribute in a table, as in the following example:

``` python
class A(dj.Manual):
    definition="""
    key:      int        # identifying key
    """
```

Trying to restrict with a string as in:

``` python
A() & 'key = 1'
```

results in the following error:

``` python
ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key = 1) LIMIT 7' at line 1")
```

This is in contrast to tables _without_ MySQL keywords as table attribute:

``` python
class B(dj.Manual):
     definition = """
     id:       int     # unique id
     """

B() & 'id = 1'
```

which runs without an error.

The error can be avoided by surrounding the MySQL keyword attribute with backquotes (``):

``` python
A() & '`key` = 1'      # runs without an error
```

Unfortunately, the error returned is highly cryptic and really gives no clue to the user to indicate that (some) attribute names need to be surrounded with backquotes.

Automatically parsing and surrounding all MySQL keywords with backquotes in the user's query is not efficient or practical, but I think the user should at least be suggested to try surrounding attribute names with backquotes to see if that would fix the error. Furthermore, this property must be properly documented so that user can easily find solution to this issue.

**Comment by dimitri-yatsenko** [comment]
We could solve this and several other problems by bringing all expressions into Python and no longer support direct SQL conditions.  

We could do this by adding a new object.  Let's call it `op` that would support the formation of conditions.  For example,
```python
A() & '`key`=1' 
```
would now become
```python
A() & (op.key == 1)
```

**Comment by dimitri-yatsenko** [comment]
```python
A() & (1 < op.value.log2 < 2.5)
```
would translate into
```python
A() & 'log(`value`,2) between 1 and 2.5) 
```

**Comment by dimitri-yatsenko** [comment]
```python
A() & (op.surf - op.z > 100)
```
would translate into
```python
A() & '`surf` - `z` > 100'
```

**Comment by dimitri-yatsenko** [comment]
```python
A() & (op.now - op.session_date > 3)
```
would translate into
```python
A() & 'DATEDIFF(NOW(), `session_date`) > 3'
```

**Comment by dimitri-yatsenko** [comment]
```python
A() & (op.animal_id in [7711, 7723, 7733])
```
would translate into
```python
A() & '`animal_id` in (7711, 7723, 7733)'
```

**Comment by dimitri-yatsenko** [comment]
I am not ready to defend this solution, but I thought I would put it out there.

**Comment by eywalker** [comment]
Introduction of MySQL ops into Python is the form of solution taken by some ORM like SQLAlchemy. Doing something like this has the benefit of providing an additional layer of separation between front end (Python methods and properties) and the backend (database commands).

What are the other issues you are thinking that this change will help solve?

**Comment by dimitri-yatsenko** [comment]
For now, I think we can just catch the exception and suggest the solution: enclose the attribute in backquotes.
