### ISSUE TITLE
Improve handling of refused connection

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#253]
Presently, if the server refuses the connection, datajoint fails to import.   Perhaps we could handle this a bit more gracefully.  For example, we could say, "The server localhost refused the connection for user cheryl.  Please re-enter the connection information"

**Comment by eywalker** [comment]
I agree, and in general, it would be nice to wrap most of the MySQL related errors with our own error, with more useful error messages.

**Comment by dimitri-yatsenko** [comment]
This was fixed in #271.
