### ISSUE TITLE
allow nullable foreign keys

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#254]
Currently, dependencies cannot be NULL, i.e. is a foreign key is set, the values must be non-nullable. 

This is the correct behavior for the foreign keys that are part of the primary key.  However, if the foreign key includes dependent attributes, then there is no reason why the foreign key should not be nullable. 

Proposed syntax:

``` python
definition = """
-> Table1    # primary keys are not affected.

---
-> Table2     # our usual syntax
=null -> Table3    # nullable attribute copied from Table3
attr=null -> Table4    # nullable renamed attribute referencing Table4
"""
```

or

``` python
definition = """
-> Table1    # primary keys are not affected.

---
-> Table2     # our usual syntax
-> Table3 = null  # nullable attribute copied from Table3
attr -> Table4 = null    # nullable renamed attribute referencing Table4
"""
```

**Comment by dimitri-yatsenko** [comment]
Another solution is make all foreign keys from dependent attributes nullable.  I think that's what I prefer.  This would have straightforward consistent cascade rules.  

But if do provide the ability to make the reference optional, another syntax is to use square brackets to signify optional (nullable) reference:

```python
definition = """
-> Table1    # primary keys are not affected.
---
-> Table2     # our usual syntax
-> [Table3]  # nullable attribute copied from Table3
attr -> [Table4]    # nullable renamed attribute referencing Table4
"""
```

**Comment by eywalker** [comment]
I vote for the second suggestion on the first post:

```python
definition = """
-> Table1    # primary keys are not affected.
---
-> Table2     # our usual syntax
-> Table3 = null  # nullable attribute copied from Table3
attr -> Table4 = null    # nullable renamed attribute referencing Table4
"""
```

**Comment by dimitri-yatsenko** [comment]
I think I prefer to just make nullable all foreign key attributes that are not in the primary key.  Then no changes of the syntax are required.  

I think the risk that users will not be forced to fill out some fields is minimal.

**Comment by eywalker** [comment]
Just like other non-primary field, I think it only makes sense to default to requiring the field to be filled out, with the option of not requiring so using some sort of `null` specification. In my tables, I do use multiple non-primary foreign keys that need to be filled in, and I would want this specification to be maintained.

If the user should not be forced to fill some fields, then the designer of the table should just specify  `=null` just like any fields, and I don't see a point making an exception for non-primary foreign key.

**Comment by dimitri-yatsenko** [comment]
my primary concern is complexity.  Is the ability to make the fields non-nullable worth the increase in complexity of syntax, documentation, etc.?

**Comment by dimitri-yatsenko** [comment]
This has been subsumed by issue #301
