### ISSUE TITLE
No need for CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#256]
It is a common practice to add a timestamp field to a table to record the time at which the record is inserted.  This is done by specifying the default value of `CURRENT_TIMESTAMP`.  
```
ts = CURRENT_TIMESTAMP : timestamp
```

However, both MariaDB and MySQL have the following rule:

> With neither DEFAULT CURRENT_TIMESTAMP nor ON UPDATE CURRENT_TIMESTAMP, it is the same as specifying both DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP.

So even when the user specifies no default, as in 
```
ts  : timestamp
```
The server will accept an insert with no `ts` specified and fill the current time.

Let's view this as a feature and document that any field of type `timestamp` defaults to current time.  Then we will not need to deal with the special value of `CURRENT_TIMESTAMP`.

If the user does not want that behavior, she can use the `DATETIME` datatype.

**Comment by eywalker** [comment]
I like not having to specify `CURRENT_TIMESTAMP` as you suggest, but for backward compatibility, we should still allow for `CURRENT_TIMESTAMP` to be specified, even if it means that we ignore it.

**Comment by dimitri-yatsenko** [comment]
Well I guess then there is nothing to fix.  I used this feature in the new log table, which uses timestamp as the primary key.  We just need to document this.

**Comment by eywalker** [comment]
Agreed. Let's make sure to document this feature well. Do we have an issue that lists all things we have to document already? If not, I'll start a new one and close this issue.

**Comment by dimitri-yatsenko** [comment]
The issue is not that straightforward and is too MySQL specific.  Issue #259 is one example where an older version of MySQL threw a cryptic error when no default was provided.  I am closing this a won't fix.
