### ISSUE TITLE
Extract DataJoint to SQL compilation into a standalone utility`dj2sql`

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#262]
I propose to create a standalone utility `dj2sql` that converts DataJoint queries into SQL for all DataJoint implementations. 

The DataJoint query language is a full language and that can be written as text rather than constructed from objects.   
For example, the query 
```python
(experiments.Session() & preprocess.Sync()).aggr(
                        preprocess.Extract.Trace(),  
                        'lens', n='count(*)')
```
could be written in text by substituting classes with their corresponding table names as
```
aggr(pipeline_experiment.session & pipeline_preprocess._sync,
    pipeline_preprocess._extract__trace, 
    lens, n=count(*))
```
dj2sql will convert this intermediate language to SQL: 
```sql
SELECT `animal_id`, `session_id`, `scan_id`, `lens`, count(*) as `n` 
  FROM `pipeline_experiment`.`session` NATURAL JOIN `pipeline`.`_extract_trace`
  WHERE (`animal_id`, `session_id`, `scan_id`) IN (
         SELECT `animal_id`, `session_id`, `scan_id` 
           FROM `pipeline_preprocess`.`_sync`)
  GROUP BY `animal_id`, `session_id`, `scan_id`
```

 It can work as a command-line utility, as a function call, and as a TCP/IP socket utility. 

So eventually, we will run a server that accepts datajoint queries directly, bypassing the intermediate SQL conversion.   We can also have interactive command line interfaces that understand datajoint.

**Comment by dimitri-yatsenko** [comment]
One advantage of this approach is that we can consolidate the query compilation into one utility and call it from all the programming languages.  I can implement it in C so that it can be compiled in every language for better performance.

**Comment by dimitri-yatsenko** [comment]
But I think I will start with a Python prototype.

**Comment by dimitri-yatsenko** [comment]
In the command-line utility, we can allow camelCase names and aliases for schemas:
```
alias exp = pipline_experiment;
alias pre = pipeline_preprocess;
aggr(exp.Session & pre.Sync,
    pre.Extract.Trace, lens, n=count(*))
```

**Comment by fabiansinz** [comment]
Is that Matlab? Why are you posting this here?

**Comment by dimitri-yatsenko** [comment]
It's not matlab. It's DataJoint script.

**Comment by fabiansinz** [comment]
Oh, I see. Sorry

**Comment by dimitri-yatsenko** [comment]
This is a long-term architectural change and is not considered under the current architecture.  Postponing until DataJoint Server becomes a thing.
