### ISSUE TITLE
Outer joins

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#263]
Currently, DataJoint only offers inner joins and the need for outer joins has not really come up.  But supply creates demand, so let's offer support for outer joins. 

Outer joins are already implicitly performed in `aggr`, where datajoint provides the `keep_all_rows` option, which internally, replaces the join within the aggregation with an outer join.

I propose to support left, right, and full outer joins, including left join in aggregation.  Thankfully, DataJoint syntax makes it fairly intuitive. 

I propose the following syntax:

### Inner join remains unchanged

```python
inner_join = a * b
```

### Left and right joins
Left joins are made by transforming the right argument into its outer version

```python
left_join = a * b.outer
```
This means that all rows of `a` are retained.  For those rows with no matching rows in `b`, the missing values in `b` are replaced with `NULL` (`None` in Python)

Similarly, in right joins, the left argument is transformed into its outer version.

```python
right_join = a.outer * b
```

### Full outer joins
In full outer joins, both arguments are transformed into their outer versions.
```python
outer_join = a.outer * b.outer
```
Since MySQL does not support full outer joins, we will probably disallow them too.

### Aggregation
The aggregated relation can be turned into its outer version to ensure that all rows of the aggregating relation are kept.

```python
aggr = a.aggr(b.outer, n='count(b_id)')   
```
replaces the current syntax of 
```python
aggr = a.aggr(b, n='count(b_id)', keep_all_rows=True)
```
When `dj.U` is the aggregating relation, then the aggregated relation cannot be outer.  The following will raise an exception: 
```python
aggr = dj.U('color').aggr(b.outer, n='count(b_id)')
```
`dj.U` itself cannot be made outer.

Although SQL allows aggregations by attributes with NULLs, I think aggregation by an outer relation should be forbidden:
```python
a.outer.aggr(b, n='count(*)')    # error: Outer relations cannot aggregate.
``` 

### Restriction
```python
a & b.outer     # ignores the restriction 
```
ignores the restriction.  This should probably just raise the exception "Restrictions by outer relations are not allowed."

### Properties of the result
The primary key of all joins is the union of the primary key attributes of the arguments.  However, left, right, and full outer joins may contain nulls.

The only difference is that now the primary key may contain some `None` values.  When treated as a regular value, the uniqueness of primary key values in the result is still preserved.

The result of an outer join may contain NULLs in its primary key attributes.  Outright, the result will not be flagged as outer itself. The rows with NULLs will be ignored in any inner joins or in restrictions.  The only time they will matter is in joins and aggregations where the other relation is outer itself.

The outer flag will be preserved in restriction and projection.  Thus `(a.outer & condition)` is equivalent to `(a & condition).outer` and `a.proj().outer` is equivalent to `a.outer.proj()`.

**Comment by dimitri-yatsenko** [comment]
## Pitfalls

The difficulty that outer joins produce is that they put NULLs in the primary key of the result.  NULLs are difficult to handle consistently.  Since `(NULL = NULL)` is always false, then joining on attributes with NULLs on both sides, should produce no matches.  Again this is not a problem until we outer join the outer join.   SQL does the crazy thing and considers `NULL=NULL` true for joins.  So the way I propose to handle this is to prohibit outer joins of outer joins when the possibility of joining on NULLs arises.

**Comment by dimitri-yatsenko** [comment]
If we implement unions (e.g. as the + operator), then the left join is `a*b + a` is the left join, `a*b + b` is the right join and `a*b + a + b` is the full outer join.  Perhaps implementing unions and using them to express outer joins is the more consistent approach.

**Comment by fabiansinz** [comment]
I'd like unions.

**Comment by dimitri-yatsenko** [comment]
And outer joins as unions?  Or outer joins in their own right too?

**Comment by dimitri-yatsenko** [comment]
I think I like to just have unions with no explicit outer joins.   Then expressions of them form `a*b + a` will be implicitly converted into outer joins for supposedly faster execution.

**Comment by dimitri-yatsenko** [comment]
I am closing this issuing and opening "Unions".
