### ISSUE TITLE
Lengthy error message does not get recorded into job reservation table

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#265]
When an error occurs during the `_make_tuples` call as part of `.populate(reserve_jobs=True)` and if the stack trace is really long (i.e. like a screenful), then DataJoint has an issue inserting this as an `error_message`, failing with message `pymysql.err.DataError: (1406, "Data too long for column 'error_message' at row 1")`. As a result, the status of the `job` table never gets changed to `error`, making it difficult to detect the fact an error has occur that has stopped the `populate` process. A fix should be rather easy as we will just have to truncate the `error_message` to certain number of characters.

**Comment by dimitri-yatsenko** [comment]
yes, we need to make the error_message column longer.

**Comment by eywalker** [comment]
This was addressed in issue #266.
