### ISSUE TITLE
Missing INSERT privileges for log table results in error

### ISSUE THREAD

**Issue by aecker** [datajoint/datajoint-python#268]
Due to the new log table users with only SELECT privileges on a schema cannot access this schema anymore. Instead, they get an error since entering the log entry fails.

A possible workaround is to give the user access to only the log table via

    GRANT INSERT ON `schema`.`~logs` TO 'user'

However, this is cumbersome, since it needs to be done for every user and schema, and tools like e.g. MySQL Workbench do not show (or let you edit) per-table access rights, requiring the admin to do this via the command line.

The simplest solution would be to catch the error and skip logging in this case. Since the user has only SELECT privileges, there isn't anything (s)he can do that needs to be logged anyway (assuming that the user does not have additional per-table privileges declared for other tables in this schema).

Alternatively, we could store the logs in a separate schema, simplifying the access privileges.

**Comment by fabiansinz** [comment]
I am in favor of skipping logging and throwing a warning.

**Comment by dimitri-yatsenko** [comment]
okay, I think we should just use the `logging` module to log the warning.  
```python
logging.warn('Insufficient privileges to make a schema log entry in `database`.')
```

**Comment by aecker** [comment]
That works of course, but the problem remains that the admins have to manage table-level access privileges for each user and schema or the users keep getting annoying warnings. Doesn't strike me as a very clean solution. What's the downside of a log schema?

**Comment by fabiansinz** [comment]
Might be easy to forget to set it up and give all users insert rights on it. The warning solution always works. However, I am not strongly opposed to the logging schema idea.

**Comment by dimitri-yatsenko** [comment]
You may disable `logging.warn` display

**Comment by dimitri-yatsenko** [comment]
I am not sure about creating a separate schema for logging.  It seems nice to keep all related information in the same schema.  I am open to the idea.

**Comment by fabiansinz** [comment]
I thought so as well initially. But a schema for all the logging might actually be more comfortable when you need to track things across several schemata. It'd be all in one place.

**Comment by dimitri-yatsenko** [comment]
would the job reservations also be in that special schema?

**Comment by dimitri-yatsenko** [comment]
It seems a bit insecure.  Users can view their logs.  They should not see other people's logs.  So we are still not avoiding the problem of table-level access control.  

I vote for keeping the logs and the jobs and all the other auxiliary tables in the same schema that they describe.

**Comment by dimitri-yatsenko** [comment]
I think logging.warn is not displayed by default anyway.

**Comment by dimitri-yatsenko** [comment]
Fixed in #271

I used `logger.info`, which is not shown by default.

**Comment by eywalker** [comment]
@aecker it would be great if you could verify that this fixed your issue and I'll close this thread.

**Comment by dimitri-yatsenko** [comment]
This is resolved.
