### ISSUE TITLE
Provide documentation for the code

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#27]
Now documentation generation system is in place, we should go and massively add documentations for all public interfaces of the DataJoint.

**Comment by fabiansinz** [comment]
I would also suggest to add basic documentation to the private ones.

**Comment by eywalker** [comment]
When Sphinx generates documentation, does it skip private methods (those starting with `_`) or does it generate documentation page for all methods?

**Comment by fabiansinz** [comment]
It skips them. But if you dig around in the code it is still nice to
have the doc. I could probably tell sphinx to include the private
methods as well, but I think that would just make things messy.


On 04/24/2015 12:44 PM, Edgar Y. Walker wrote:
>
> When Sphinx generates documentation, does it skip private methods
> (those starting with |_|) or does it generate documentation page for
> all methods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datajoint/datajoint-python/issues/27#issuecomment-96010029>.
>

-- 
Dr. Fabian Sinz
contact info: http://goo.gl/o87zXC

**Comment by eywalker** [comment]
I agee. I think it is good to keep the private methods out of the online
documentation. I'll start adding docs on private methods.

**Comment by dimitri-yatsenko** [comment]
Closing as invalid.  Submit issues with more specific issues.
