### ISSUE TITLE
Callable `definition`

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#273]
Currently the table definition must be a class property defined as a string. As more complex table designs emerge, it would be nice to provide table definition *templates* where only parts of the table definitions are provided, with the missing values intended to be filled in by the inheriting classes (providing concrete table definitions). However, because we expect `definition` to be a class property, there is no time for the subclass to *fill in* or modify the inherited definition. To get around this, currently we are using factory classes that generates a new class with dynamically generated `definition`. However, if `definition` can be evaluated dynamically during declaration, such round about mechanism is often unnecessary.
 
It would be nice if `definition` was like `@property` that can be evaluated at the time of invocation (i.e. class definition) but class property is not officially supported by Python (although we do provide our own class property in DataJoint).

Next best thing is to allow for `definition` to be callable. This will provide users with a choice of using the standard static string as `definition` or to implement `@classmethod` `definition` that dynamically evaluates `definition` string upon invocation.

This is also quite easy to implement, just changing one line in the `base_relation`.

**Comment by eywalker** [comment]
With callable definition, fitting of the same model on drastically different data sources can be easily implemented as mixins.

```python
class Model(dj.Computed):
    base_definition="""
    -> {data}
    -> ModelHyperparameters
    ---
    fitness:  float   # model fitness
    """
    @classmethod
    def definition(cls):
        return cls.base_definition.format(data=cls.data_source())

@schema
class DataA(dj.Lookup):
    definition="""..."""
    @classmethod
    def data_source(cls):
        return cls.__name__

@schema     
class DataB(dj.Lookup):
    definition="""..."""
    @classmethod
    def data_source(cls):
        return cls.__name__

@schema
class ModelOnA(Model, DataA):
    pass

@schema
class ModelOnB(Model, DataB):
    pass
```

**Comment by eywalker** [comment]
Does anyone have any opinion on this? If there is no strong object, I'll go ahead and implement this.

**Comment by fabiansinz** [comment]
Why can't you do 
```python
class Model(dj.Computed):
    base_definition="""
    -> {data}
    -> ModelHyperparameters
    -> {other}
    ---
    fitness:  float   # model fitness
    """
    @property
    def definition(self):
        return Model.base_definition.format(**self.resource)

class A(dj.Computed, Model):
    resource = {
        'data' : 'WhatEver', 'other':'SomethingElse'
    }

```

**Comment by eywalker** [comment]
Actually you are completely right. For some reason I have assumed that the `definition` attribute was accessed on the class and not on the instance. However, declaration occurs *after* instantiation so I can just use `definition` as instance `property`. In short, there is no problem here to begin with 😛.

**Comment by eywalker** [comment]
Just to be sure, I'll try this and if it works I'll close this issue.

**Comment by dimitri-yatsenko** [comment]
even simpler
```python
class Model:
    base_definition="""
    -> {data}
    -> ModelHyperparameters
    -> {other}
    ---
    fitness:  float   # model fitness
    """

class A(dj.Computed, Model):
    @property
    def definition(self):
         return self.base_definition.format(data='whatever', other='other')
```

**Comment by eywalker** [comment]
Alright, I have just verified that the regular `property` works just fine for `definition`. Closing this issue.
