### ISSUE TITLE
Increase test coverage >90%

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#28]
At the moment we are at 47%, which is clearly unacceptable.

**Comment by dimitri-yatsenko** [comment]
It's a worthy goal to strive for but let's keep the issues relevant to downstream users.

**Comment by fabiansinz** [comment]
I think it is important to have to well tested. At least leave the issue open.

**Comment by eywalker** [comment]
With whole bunch of recent changes both in the main code and in the tests, our coverage is now down to 63%. We should aim to increase this to at least ~70% prior to our first release.

**Comment by fabiansinz** [comment]
I agree. Just as an additional reminder, please use a short docstring for each test function as this will show up in travis and makes it a lot easier to infer what the function is testing.

**Comment by dimitri-yatsenko** [comment]
Attained 90% coverage in fa3e26edf.  We will now only accept pull requests that do not decrease coverage.
