### ISSUE TITLE
save configuration files explicitly

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#284]
Currently, if datajoint does not find a configuration file, it creates a local configuration file with default settings locally.  This is a bit heavy-handed.   Instead let's provide functions `dj.config.save_local()` and `dj.config.save_global()` to save the current settings.

**Comment by eywalker** [comment]
I'm definitely supportive about adding these two commands - although something like `dj.save_local_config()` and `dj.save_global_config()` might be easier to search as users can simply *tab* through on `dj` package rather than having to remember `dj.config`.

**Comment by dimitri-yatsenko** [comment]
But then they need `dj.config` to set and view config.  I think they can scroll to get to config and we need to write a good docstring for config.

**Comment by dimitri-yatsenko** [comment]
Here is the connection procedure https://github.com/datajoint/wiki/wiki/Install-and-connect

**Comment by eywalker** [comment]
Ok given that `dj.config` returns an object, it does make sense to attach `save_local` and `save_global`. Having suffix `_config` is redundant so I propose to drop that.

Just to point out, there is already `save` method that even accepts target path. We will implement `save_local` and `save_global` as a convenience method that knows the path and filename used as LOCAL and GLOBAL config, respectively.

**Comment by dimitri-yatsenko** [comment]
Fixed in #286
