### ISSUE TITLE
Should we provide exporting non-blob data to pandas?

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#29]

**Comment by eywalker** [comment]
Pandas support is something I've been thinking about and have not decided
on. If I'm not mistaken, converting from numpy record type (returned by
fetch) to pandas dataframe is easy (just passing on to df constructor I
believe). If this is the case I'm not sure if it is necessary for us to
provide an explicit export option.

**Comment by dimitri-yatsenko** [comment]
I don't think datajoint should depend on pandas.  We should just make sure the exchange of information between the two is trivial.  It sounds like exchanging numpy arrays is trivial.  We may need to provide a method similar to `dj.struct.tabulate` in the matlab version.

Closing as a wontfix.
