### ISSUE TITLE
correct cascaded deletes across renamed foreign keys

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#300]
a more detailed descriptions will follow.

**Comment by dimitri-yatsenko** [comment]
This was actually not fixed.  #371 stated that restructuring was done for #300 but the fix was not completed.

**Comment by ixcat** [comment]
note:
tests/test_foreign_keys.py
test_aliased_fk
test_delete
may need adjustment as part of fixing this.
