### ISSUE TITLE
Use keyword `master` in Part table's definition to refer to the Master table

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#302]
Currently, you have to explicitly refer to the Master table's name in the Part table's definition as in 

```python
class A(dj.Computed):
    definition="""
    id: int    # unique id
    """
    
    class B(dj.Part):
        definition="""
        -> A
        ---
        value: float  # associated value
        """
```

What's the master for `B` is obvious from the context and having to explicitly state `-> A` feels redundant. I propose to add support for a keyword like `master` such that the above definition would look like this instead:

```python
class A(dj.Computed):
    definition="""
    id: int    # unique id
    """
    
    class B(dj.Part):
        definition="""
        -> master
        ---
        value: float  # associated value
        """
```

As I will detail in a separate issue, this also supports defining a mix-in class with Part table already defined (e.g. you can easily support a design in which additional part tables can be **added** by inheriting from a mix-in class).

**Comment by dimitri-yatsenko** [comment]
I think this should be unified with #303 and used as `self.master`.

**Comment by eywalker** [comment]
I much prefer `master` as I think `master` is simpler and it's clear what it means from the context. If we say `self.master`, then we have to add `master` attribute to the `Part` class instead of the `_master`.

**Comment by dimitri-yatsenko** [comment]
then we should probably omit `self` altogether.  `-> data`  is sufficient.

**Comment by dimitri-yatsenko** [comment]
what's the latest on this issue? Can we close this?

**Comment by eywalker** [comment]
This has already been implemented and working well. Use of `self` is critical to distinguish the property of a class vs names defined in the local context. Closing.
