### ISSUE TITLE
Support silent mode

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#308]
Currently, when you import DataJoint and connect to database server for the first time, database prints couple information statements. Although this is helpful for interactive usage, printing to standard output can be quite annoying when you are trying to write and run a software which would print only critical information to the stdout. For this reason, I suggest that we add a configuration option to turn off this print statements.

**Comment by dimitri-yatsenko** [comment]
This should already be handled through the `logging` module without having to do any additional configuration.  Unfortunately, using `logging` is not always understood by users and we need to provide additional instructions.
