### ISSUE TITLE
optionally suppress count display

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#309]
When working with large tables (e.g. a billion tuples), fetching is quick but getting the count may take a long time (e.g. 60 s).  This makes previously annoyingly slow.

I propose to add the configuration option to turn off the display of the total count of tuples from the preview. 

```
dj.config['display.count'] = False
```
It will be `True` by default.

**Comment by eywalker** [comment]
Can I suggest to change the property name to something like `display.show_count` instead? `dispaly`is the section name and just saying `display.count` can be quite confusing with `display.limit`
