### ISSUE TITLE
Accepting user input for connection information

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#31]
I noticed that in `connection.py`  `conn_container` defintion, the part

```
input('Enter datajoint server address >> ')
```
was commented out. I'm guessing this was a done when configuring TravisCI, but is this necessary anymore?

**Comment by fabiansinz** [comment]
That is correct. When it is commented in the tests do not pass. Let's talk about how to properly deal with this. 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: "Edgar Y. Walker" <notifications@github.com> 
Datum: 25.04.2015  00:34  (GMT-06:00) 
An: datajoint/datajoint-python <datajoint-python@noreply.github.com> 
Betreff: [datajoint-python] Accepting user input for connection information
  (#31) 

I noticed that in connection.py  conn_container defintion, the part

input('Enter datajoint server address >> ')


was commented out. I'm guessing this was a done when configuring TravisCI, but is this necessary anymore?

**Comment by eywalker** [comment]
We have removed the feature to interactively input the connection information. Now the datajoint looks for all connection information (as well as other config info) in a local config files. We could potentially add such capacity back via a separate utility function that prompts for connection information and write them into the user's local config file, and that's not going to be a priority as I think it is just as easy to open up config file and place connection info there. Closing this issue...

**Comment by dimitri-yatsenko** [comment]
Forcing the user to store passwords in config files is probably not a good idea.

**Comment by fabiansinz** [comment]
I agree. But neither is stopping the execution of code and asking for a password. We could encrypt it. 
Am 05.05.2015 05:08 schrieb Dimitri Yatsenko <notifications@github.com>:Forcing the user to store passwords in config files is probably not a good idea.

**Comment by FloFra** [comment]
I think that the fix @fabiansinz suggested it the most straight forward.

Alternatively one could use the python keyring lib to store and retrieve the password. This won't help with the cluster problem nevertheless. I have yet to see a cluster, that properly supports keyring on its nodes.

Fun Fact: [Mysql does not need the password itself for authentication but only its sha1 hash.](https://dev.mysql.com/doc/internals/en/secure-password-authentication.html#packet-Authentication::Native41) Does not solve our problem though.
