### ISSUE TITLE
Expose `dj.config.save` and `dj.config.load` explicitly

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#311]
`dj.config` (an instance of `dj.settings.Config` object actually fully exposes properties and methods of the internal class `dj.settings.Config.__Config` via `__getattr__` trick. The problem is that this causes the methods of `__Config` such as `save` and `load` to be not suggested by tab completion.

We should either implement `__dir__` to expose `__Config` names or explicitly implement `save` and `load` pass-through function within `Config`.

**Comment by dimitri-yatsenko** [comment]
Should we remove the internal class?  The scenario of using settings as a context may not justify the increase in complexity and documentation load that it brings.

**Comment by eywalker** [comment]
As far as the regular usage is concerned, I don't think there is any overhead in documentation (esp provided that we expose methods like `save` and `load` that *should* be properly documented). Being able to do contextual config is a nice feature that I'd say we should keep it around. We can just leave that use case not fully documented for now, as it is admittedly an advanced use-case.

**Comment by dimitri-yatsenko** [comment]
Ok, I am just saying that I am not opposed to removing it.
