### ISSUE TITLE
Apply hook for fetch

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#313]
I propose the following addition to the fetch object. 

`data = myrel.fetch(map=myfunc)`

where

`myfunc` is a function that is applied to all fetched elements. 

In addition, there would be another keyword argument that applies mappings to attributes with matching column name separately. 

```
Spikes().fetch(map_dict=dict(rate_trace=np.squeeze))
```

**Comment by dimitri-yatsenko** [comment]
looks like a useful feature.

**Comment by dimitri-yatsenko** [comment]
@fabiansinz Will you please revise this issue with respect to changes made for #318?

**Comment by fabiansinz** [comment]
@dimitri-yatsenko updated.

**Comment by dimitri-yatsenko** [comment]
by "fetched elements" do you mean entire tuples before they are converted into the whatever format `fetch` returns?  In other words, what is the data type of the input into `myfunc`?

**Comment by fabiansinz** [comment]
That depends on you. You can use `as_dict=True`, then `myfunc` gets dictionaries, otherwise it gets structured arrays.

**Comment by dimitri-yatsenko** [comment]
Then it's not much more useful than applying the function to the result of `fetch`.  I am thinking it should work the same way whether `as_dict` is on or not and I think the second format with a `map_dict` is the only that makes sense.   The function gets applied to each tuple individually.

**Comment by fabiansinz** [comment]
I am not particularly attached to `map`. So shall we rename `map_dict` to `map` and only provide that functionality? Note that structured arrays actually create a problem here as they cannot change their datatypes. You cannot simply say `results['animal_id'] = [str(e) for e in results['animal_id']]` as that would change the datatype of the column. We would need to infer the datatype from the function and create a new structured array according to that.

**Comment by dimitri-yatsenko** [comment]
I am hesitant about this feature.  Seems like it complexity and documentation load may outweigh the benefits.  The user can post-process the results instead.

**Comment by fabiansinz** [comment]
I now see the problem with it, in particular the problem that the `dtype` of structured arrays cannot easily be changed. Let's stall it for now and maybe reactivate later.

**Comment by dimitri-yatsenko** [comment]
closing.  Re-open if relevant.
