### ISSUE TITLE
Simplify fetch

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#318]
Currently, the fetch object is not elegant and potentially confusing to users. I propose the following changes to simplify it. 

**Stateless fetch**
`fetch` becomes completely stateless. This will simplify the implementation and make the process more transparent. All states become keyword arguments in `fetch`. For example `rel.fetch.order_by('attribute').as_dict()` becomes `rel.fetch(as_dict=True, order_by='attribute')`. All previous states become forced keyword arguments. 

**__getitem__ and iterators**
Fetch keeps `__getitem__`, `keys`, and `__iter__`. The disadvantage that comes with the stateless implementation is that the ways the elements are fetched cannot easily be modified for most of these functions. The following changes would solve this

- `keys` does accept arguments like `__call__` (i.e. `rel.keys(order_by='attr1')`)

- `__call__` does also accept unnamed arguments. In that case it behaves like `__getitem__` but with possible modifications. For example `a1, a2 = rel.fetch['attr1','attr2']` is equivalent to `a1, a2 = rel.fetch('attr1','attr2')`. However, `__call__` can be modified such as `a1, a2 = rel.fetch('attr1','attr2', order_by='attr1')`.

- `__iter__` stays, but cannot be modified. In addition, we provide the iterator `traverse` which accepts the same modifying keyword arguments as `__call__`. Additionally, `traverse` can get unnamed arguments. For example `for a1, a2 in rel.fetch.traverse('attr1','attr2', limit=10):`.

**Comment by dimitri-yatsenko** [comment]
Yes, agreed.

**Comment by dimitri-yatsenko** [comment]
If fetch is going to be stateless, there is little reason to keep it as a class.  It can become a method of `RelationalOperand`.  `traverse` then will be used rather than `fetch.traverse`.

**Comment by fabiansinz** [comment]
I think we should keep it for two reasons:

- `__getitem__` needs an object and we might want to use getitem in the relation at some point (e.g. projections).

- it keeps all elements related to fetching separated from the relational algebra.

**Comment by eywalker** [comment]
Yes let's not remove `fetch` object all of a sudden - we have introduced it precisely for the above two reasons that @fabiansinz pointed out. Making it stateless is a distinct consideration.

However I'm not sure about making `fetch()` act essentially as a superset of `fetch[]`. I think I would prefer that `fetch('a', 'b')` to perform something different from `fetch['a', 'b']` or otherwise I don't see much use of `fetch[]` and this can actually confuse the user.

**Comment by eywalker** [comment]
Also, recall that a lot of this stateful approach got added to support the `fetch['a']` syntax as there is no way to pass in arguments like `limit=10`. 

I agree that current stateful approach has led to a rather ugly syntax and I'd love to simplify this, but I also don't like to see us suddenly providing many different ways to do exactly the same thing - that makes thing less simple.

**Comment by eywalker** [comment]
That being said, I do really like the new proposed syntax of `fetch('a', 'b', order_by='a')` and this can potentially bring about new call like `fetch1('a', order_by='a')` to mean fetch the first entry after ordering by `a` - this has the benefit of returning the element by itself and not in a list.

**Comment by fabiansinz** [comment]
I view the `__getitem__` as pure convenience. I don't have a problem with some redudancy in how you do things. In fact, I would like to put most of the logic into `__call__` and use the other methods to simplify syntax.

**Comment by eywalker** [comment]
Well my point is that if we make the suggested changes to `__call__` then there is nothing convenient about `fetch[]` at all.

**Comment by fabiansinz** [comment]
True. So we could throw a deprecation warning for a while and then get rid of it.

**Comment by eywalker** [comment]
Yeah that might be the best move. I like the idea of centralizing most things into the `__call__`. We should at least update docs and tutorials to use new syntax only ASAP if we decide to make this switch.

**Comment by eywalker** [comment]
Ok I think we are converging on the decision to:

1. bring in optional unnamed arguments into `__call__` method on `fetch`, supporting syntax like `rel.fetch('a', 'b')`, essentially acting equivalently to the current implementation of `rel.fetch['a', 'b']`
1. deprecate the use of `__getitem__` on `fetch` (i.e. no more `rel.fetch['a']` syntax)
1. make `fetch` completely stateless - therefore deprecate state modifiers like `order_by()` and `limit()` on `fetch`

I'm going to start the implementation of the above points most likely in that very order and we'll make this part of the release `0.7.0`.

**Comment by dimitri-yatsenko** [comment]
closing?

**Comment by fabiansinz** [comment]
Shall we wait until the feature is fully implemented and deprecated.

**Comment by dimitri-yatsenko** [comment]
I think it's fully implemented and deprecated.  Warnings are shown when the old syntax is used.

**Comment by fabiansinz** [comment]
Ok, then let's close. We can cleanup a bit when we remove the warning and the old functionality.

**Comment by eywalker** [comment]
As of #319, the new `fetch` syntax has been in place, and has been working fine in a production system. I'm closing this issue as initial objective was achieved. The old syntax like `fetch[attr]` will remain in the "deprecated" state for the next few releases with eventual plan for complete removal.
