### ISSUE TITLE
Rewritte settings

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#32]
* default dictionary in datajoint.settings
* dictionary derived class in datajoint.settings that has additional validators
* implement validators
* local file should store the local configuration. For security reasons that should not be a python module, but a json configuration file. If the json file is not there, it is created from default. An environmental variable can point to different location than local directory. 
* datajoint.__init__.py instaniates dictionary derived class as config from local config file.

**Comment by eywalker** [comment]
Thanks to Fabian this is pretty much implemented. However, more test cases should be added.
