### ISSUE TITLE
add passive mode to schemas

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#331]
The schema decorator declares tables in the database and fills out lookup tables.  This is useful during the design phase of the pipeline but adds overhead during regular use of the schema.  I propose to add the keyword argument `create=True` to the `__init__` of `dj.Schema`.

Then setting 
```python
schema = dj.schema('ephys', locals(), create=False)
```
will prevent creation of new tables and filling of lookup tables, reducing overhead and errors from accidentally creating outdated tables.

After the design phase is over and the pipeline has been created, the flag is set to `False`.

**Comment by dimitri-yatsenko** [comment]
Perhaps the argument should be called `mode` and allow several values: 

 `create`:  what we have now.  The schema creates new tables
  `use`:  the schema does not create new tables and throws an arrow if a table is not already declared.
  `check`: the schema checks table definitions against the database and throws an error if the database definition has changed.

**Comment by fabiansinz** [comment]
I like the idea. What about `development`, `production`, `strict`?

**Comment by dimitri-yatsenko** [comment]
I like these but "development" and "production" make it sounds that you first do development and then deploy whereas in reality you can stay in "development" the whole time with just some loss of efficiency.

**Comment by dimitri-yatsenko** [comment]
how about `dev`, `stable`, `strict`?

**Comment by dimitri-yatsenko** [comment]
I think I like {`active`, `passive`, `strict`} because `development` implies that is not ready yet.

**Comment by fabiansinz** [comment]
What about `fixed` (or `frozen`), `active`, `strict`

**Comment by dimitri-yatsenko** [comment]
Yes, I like: {`active`, `fixed`, `strict`}   Fixed is the most efficient because it does not perform any checks.  strict is useful for detecting obsolescence.

**Comment by dimitri-yatsenko** [comment]
I think it will be clearer and more explicit and if there will be two flags `create_tables=True` and `verify_tables=False` since all four combinations make sense.
