### ISSUE TITLE
allow table definition in doc string

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#332]
Currently, the table definition is provided in the `definition` property of the class.  It may be more succinct to use the doc string instead.

I propose the following solution:  If the `definition` property is missing, datajoint will look in the doc string for the table definition.

**Comment by fabiansinz** [comment]
What's the use case?

**Comment by dimitri-yatsenko** [comment]
In most cases, datajoint classes do not have a doc string because the table definition provides ample information.  So to save typing effort, we can now optionally use the doc string to put the definition, so you can do either of the following:

```python
@schema
class User(dj.Manual):
    definition = """ # Database user
    username : varchar(20) 
    ----
    full_name  :  varchar(60)
    """
```

```python
@schema
class User(dj.Manual):
    """ # Database user
    username : varchar(20) 
    ----
    full_name  :  varchar(60)
    """
```

**Comment by fabiansinz** [comment]
Sorry, that's not a use case, that's an example. I think there should be exactly one way to declare a table. Docstrings serve another purpose and should not be used for that in my opinion.

**Comment by dimitri-yatsenko** [comment]
I actually agree.  But it's so nice not having to type `definition` every time since the doc string is so rarely used for DataJoint classes.

**Comment by fabiansinz** [comment]
I don't feel that 13 characters of typing effort justifies the lack of conceptual clarity, the programming effort of handling those cases, and the visual clutter from having definitions as strings and docstrings in your editor with different syntax highlighting.

**Comment by fabiansinz** [comment]
If you don't want to type it, why don't you use live templates in pycharm?

**Comment by dimitri-yatsenko** [comment]
It's sad but i have to agree.

**Comment by dimitri-yatsenko** [comment]
closing this issue.
