### ISSUE TITLE
Collection of schema design patterns in docs

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#34]
We should have this. Other ideas on the topic are:
* give users the opportunity to submit new design patterns
* write a small website on which users can generate schemata and download the code

**Comment by eywalker** [comment]
I agree and I believe that making this is also part of the plan for the hackathon. Having a website for people to submit design patterns could be quite interesting, but it'll likely have to stay in the back burner until we get all main features implemented. 

I don't know of a way for us to make site with the proposed functionality without running interactive website on real web host. If this can somehow be done on publicly available hosting service (e.g. github pages), then it will be amazing.

**Comment by fabiansinz** [comment]
Solved by http://datajoint.github.io/gallery/ . Just needs to be filled with content.
