### ISSUE TITLE
Invalid enum values fail silently on insert() and insert1()

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#344]
It seems that invalid enum values do not raise an error in mysql + datajoint-python when inserting into a table. Here's a minimal example:

```python
import datajoint as dj

schema = dj.schema('dj_mysql_test', locals())

@schema
class Mouse(dj.Manual):
    definition = '\n'.join([
    "m : varchar(128)", # name
    "----",
    "m_sex : enum('F', 'M', 'unknown')"
    ])

m = Mouse()
m.insert1(dict(m='test1', m_sex='M'))
m.insert1(dict(m='test2', m_sex='blarg')) # fails silently
m.insert([dict(m='test3', m_sex='F'),
          dict(m='test4', m_sex='blarg')]) # fails silently

print(m.preview())
print('dj.__version__ == ', dj.__version__)
```
This results in the following output:
```
*m        m_sex    
+-------+ +-------+
test1     M        
test2              
test3     F        
test4              
 (4 tuples)

dj.__version__ ==  0.8.0
```
Obviously, I'm using the default values for the various kwargs for `.insert()` and `.insert1()`:
```python
replace=False, ignore_errors=False, skip_duplicates=False, ignore_extra_fields=False
```
Most relevantly, `ignore_errors=False`, yet no error is raised. Is this a known issue? When we try something like this on the same mysql server using datajoint-matlab, an error is raised, as it should be IMO.

```
$ mysql -V
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3
```

**Comment by eywalker** [comment]
Hi @mspacek this is most likely caused by the unfortunately bad default configuration of MySQL. In order for `ENUM` to refuse values not in the set, the MySQL server must be [running in `strict` mode](https://dev.mysql.com/doc/refman/5.7/en/constraint-enum.html) which is [by default turned *off*](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict).

**Comment by mspacek** [comment]
Aha. It seems our startup script in matlab was setting the mode to "TRADITIONAL" for every connection, hence insertion errors were raised in matlab but not in python, even on the same server.

Thanks for the tip!
