### ISSUE TITLE
Default `key_source` for computed tables with renamed FK attributes

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#345]
As was discussed in #301, when renamed foreign key attributes are present in the primary key, the default implementation of `key_source` no longer operates correctly.

**Comment by dimitri-yatsenko** [comment]
In general, it's not a good practice to use renamed keys for populating.  The key  supplied to `make_tuples` will be the key for inserting into the populated table and will not be suitable for querying the upstream tables.

We can fix the key_source to make populate work correctly but I wonder if we should prohibit populating across renamed foreign keys for now until we develop good practices for it.
