### ISSUE TITLE
Attempting to insert a negative value for an unsigned integer column raises no immediate error

### ISSUE THREAD

**Issue by mattbdean** [datajoint/datajoint-python#346]
Consider this schema:

```python
@schema
class Testing(dj.Manual):
    definition = """
    id : int unsigned
    """
```

If we insert a new row with a negative value for `id`, MySQL will attempt to insert it as if we had specified `id=0`

```python
Testing().insert1(dict(id=-1))
```

The table now contains this data:

| id |
|----|
| 0 |

If we attempt to insert similar data (`id=-2`), then we get this error:

```py
IntegrityError: (1062, "Duplicate entry '0' for key 'PRIMARY'")
```

This seems to be a MySQL-specific quirk. datajoint-matlab might also have this issue.

**Comment by dimitri-yatsenko** [comment]
This issues is caused by permissive server settings, see #344 and https://dev.mysql.com/doc/refman/5.7/en/out-of-range-and-overflow.html

**Comment by mattbdean** [comment]
Good to know, thanks!
