### ISSUE TITLE
__repr__ in terminal displays <object address> instead of preview

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#348]
I showed this to Fabian Sinz in person, and he was quite surprised! This is what I get when I try to display a table in the terminal. I thought this was meant to be the default behaviour:

```python
import datajoint as dj

schema = dj.schema('dj_test', locals())

@schema
class Mouse(dj.Manual):
      definition = """
      mouse_id: int                  # unique mouse id
      ---
      dob: date                      # mouse date of birth
      sex: enum('M', 'F', 'U')    # sex of mouse - Male, Female, or Unknown/Unclassified
      """

m = Mouse()

print(m)
print()
print(m.preview())

# output:
'''
<__main__.Mouse object at 0x7f7aeed36ef0>

*mouse_id    dob     sex    
+----------+ +-----+ +-----+

 (0 tuples)
'''
```
This is in both IPython (5.x, 6.x) and plain Python (3.5.x). According to Fabian, the intended behaviour for `__repr__` is to return a preview of the table, which makes more sense. In Jupyter notebook, it returns a nicely formatted preview of the table.

I've gotten around this by oveloading `__repr__` in our own tables so that they return `self.preview()`.

Am I the only one having this problem?

**Comment by dimitri-yatsenko** [comment]
A preview is printed unless `dj.config['loglevel']` is set to `"DEBUG"`.  This is for efficiency.  For more complex queries, a preview may take some time and we provide the option to suppress it.

**Comment by mspacek** [comment]
Great! Thanks! I switched to `"INFO"` instead.
