### ISSUE TITLE
Data entry widget for Jupyter

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#351]
It would be great to have a feature for entering a new tuple interactively.  For example, if you have the table `Animal`, you should be able to do something like:
```python
Animal().enter()
```
and this will open up a form allowing to enter a new tuple into it interactively.

Thoughts?

**Comment by dimitri-yatsenko** [comment]
Here is an example of automatic GUI creation:  
https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html

**Comment by dimitri-yatsenko** [comment]
Here is another related project:
https://github.com/quantopian/qgrid

**Comment by ixcat** [comment]
@eywalker tagging for discussion

**Comment by ixcat** [comment]
Created an initial rudimentary ```DJRecord``` widget-builder.

Actual code is in:
https://github.com/ixcat/djwip/blob/master/djwip/ixcat/djgrid.py
(```DJPanda``` class is another, more cumbersome Pandas/QGrid based approach)

a simple 'integration test' check jupyter notebook for ```DJRecord``` is in:
https://github.com/ixcat/djwip/blob/master/djwip/ixcat/djgrid/djrecord.ipynb
using the test schema:
https://github.com/ixcat/djwip/blob/master/djwip/ixcat/schemax/schema.py

Questions to proceed:
0. Usual code approach, etc auditing
1. Should this be in-tree or in a separate 'plugins' repo
2. If in-tree, what should be integration approach:
a. extend relation classes to provide add'l method in user table classes
b. take 'separate method'/'sidechain' approach where users pass in table classes similar to how ```DJRecord``` is currently implemented; if so, how precisely.

also: the code also uses some schema-navigation routines from 
https://github.com/ixcat/djwip/blob/master/djwip/ixcat/schemax.py;
these would likely either be inlined or potentially merged in as needed/desired.

**Comment by dimitri-yatsenko** [comment]
What's the decision on this?  I propose to integrate this as the `enter` method in `BaseRelation`.  However, it should perhaps behave differently depending on whether it's a the prompt or in Jupyter.

**Comment by ixcat** [comment]
Ah - there was some discussion or discussions which I cant currently place about having a separate module so as to not have too many dependencies in core prior to the trip - https://github.com/datajoint/datajoint-jupyter was created to that effect. Next steps on non-integration or integration welcome from there accordingly

**Comment by dimitri-yatsenko** [comment]
Closing.  This will be supported in a standalone package.
