### ISSUE TITLE
deprecate environment variables

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#352]
Currently DataJoint uses the environment variables `DJ_HOST`, `DJ_USER`, and `DJ_PASS` to override configuration settings.  This is a complex feature with little benefit to user.  I propose deprecating this feature.  If the user wants to set the login credentials from environment variables, they can easily do so using `dj.config`

**Comment by fabiansinz** [comment]
I vote against that. Environment variables are currently the main way to pass credentials into docker containers. For that purpose it is a very useful feature.

**Comment by dimitri-yatsenko** [comment]
This can be easily fixed by adding
```python
dj.config['database.host']=os.environ['DJ_HOST']
...
```
at the beginning of scripts

**Comment by eywalker** [comment]
I also would vote against the removal. Ability to use ENV var to set config greatly simplifies integration with Docker - esp as passing in custom ENV var during Docker launch is a very common and well supported way to configure the runtime in the container (e.g MySQL Docker). Requiring the few lines of boiler plate config at the beginning of script becomes extremely redundant and unnecessary introduces repeated code. The current chain of config resolution is well defined and I think it's just a matter of documenting it once cleanly, and does not warrant removal for the sake of simplification.

**Comment by eywalker** [comment]
Also this is a feature that's already been implemented well and has been in use frequently. If anything we should maintain it, and just document it.

**Comment by dimitri-yatsenko** [comment]
ok
