### ISSUE TITLE
windows dependencies / pygraphviz

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#353]
Not so much a datajoint/code bug but a documentation / install issue -

Pip/pygraphviz are apparently very selective concerning windows builds - several issues, some unresolved in pygraphviz tracker:

* https://github.com/pygraphviz/pygraphviz/issues/132
* https://github.com/pygraphviz/pygraphviz/issues/121
* https://github.com/pygraphviz/pygraphviz/issues/116
* https://github.com/pygraphviz/pygraphviz/issues/74
* https://github.com/pygraphviz/pygraphviz/issues/58

Some users have apparently been able to build at one time or another.

Related factors:

* Windows Version
* Python Version
* Pygraphviz version
* Graphviz 64 bit/windows is not generally available - unofficial workaround here: https://github.com/mahkoCosmo/GraphViz_x64/ 
* Possible issues with pygraphviz and python IO changes in python >3.5

Need to have reproducible steps for installing pygraphviz on windows until the situation stabilizes.

Any pointers welcome.

**Comment by dimitri-yatsenko** [comment]
Let's keep track of this issue and keep our users informed.  We should write about this on the ERD documentation page http://docs.datajoint.io/data-definition/ERD.html.  Sounds as though a solution should be around the corner.

**Comment by ixcat** [comment]
Posted example alternatives to pygraphviz in my wip area- 
these don't require link-time dependancy which might be a better approach - 
however this implies a manual graphviz install. Link here:

https://github.com/ixcat/djwip/tree/df83eeea48546d6be9ac4f14e67cae551cbfe16a/djwip/ixcat/windowsgv

If we don't have more extensive integration with graphviz api proposed for client-side code (only using it for rendering of static ERD diagrams), I propose the following mini-roadmap to migrate towards using pydot instead:

1) Sanity check of pydot version of above notebook on other platforms (Mac+Win OK currently)
2) Migration to NetworkX v2.x -

    The old/seemingly dormant pydotplus python 3 fork is used in networkx v1.11,
    whereas NetworkX v2.x reverts to the original 'pydot' package & a networkx v2.0
    is needed eventually anyway.

    Theoretically the pydotplus vs pydot API's are similar, so if a patch against current DJ is desired
    first to dig deeper on compatibility, that might be another mini-roadmap.

3) Flip diagram to use pydot
4) This should enable dj.ERD on windows with ```pip install datajoint``` and graphviz .msi, 
     which is pretty straightforward, although admittedly not ```1 click```.
5) From there, we can look into conda packaging

**Comment by ixcat** [comment]
thinking further, I will go ahead and create a 'pydot' branch & track main in my repo *as well*; this should only be a few lines of diff and easy to keep in sync with whatever changes go in base.

**Comment by ixcat** [comment]
Thinking mini roadmap over-thought things - if pydot(plus) works after more testing, I see no problems in the approach of merging and then can deal with regressions upon networkx 2 implementation.

**Comment by ixcat** [comment]
But alternately can stick to roadmap. Will take a quick dive into networkx2 next to see how that goes & comment in #362 accordingly.
