### ISSUE TITLE
debug/unittest/document blob insertion parameters

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#360]
During a demonstration test using longblob data, recieved disconnect for blob insert - 
To some extent this is expected; For mysql the parameter max_allowed_packet must be set accordingly. Need to track down to what extent this can be cleanly caught/unittested/documented for both the MySQL and RDS cases.

> Traceback (most recent call last):
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 1039, in _write_bytes
>     self._sock.sendall(data)
> BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/chris/Workspace/datajoint-python/datajoint/autopopulate.py", line 118, in populate
>     self._make_tuples(dict(key))
>   File "./ingest-pub.py", line 255, in _make_tuples
>     self.insert1(key, ignore_extra_fields=True)
>   File "/Users/chris/Workspace/datajoint-python/datajoint/base_relation.py", line 125, in insert1
>     self.insert((row,), **kwargs)
>   File "/Users/chris/Workspace/datajoint-python/datajoint/base_relation.py", line 256, in insert
>     args=list(itertools.chain.from_iterable((v for v in r['values'] if v is not None) for r in rows)))
>   File "/Users/chris/Workspace/datajoint-python/datajoint/connection.py", line 125, in query
>     cur.execute(query, args)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
>     result = self._query(query)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
>     conn.query(q)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 855, in query
>     self._execute_command(COMMAND.COM_QUERY, sql)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 1092, in _execute_command
>     self._write_bytes(packet)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 1044, in _write_bytes
>     "MySQL server has gone away (%r)" % (e,))
> pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./ingest-pub.py", line 289, in <module>
>     Image().populate()
>   File "/Users/chris/Workspace/datajoint-python/datajoint/autopopulate.py", line 121, in populate
>     self.connection.cancel_transaction()
>   File "/Users/chris/Workspace/datajoint-python/datajoint/connection.py", line 175, in cancel_transaction
>     self.query('ROLLBACK')
>   File "/Users/chris/Workspace/datajoint-python/datajoint/connection.py", line 125, in query
>     cur.execute(query, args)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
>     result = self._query(query)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
>     conn.query(q)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 855, in query
>     self._execute_command(COMMAND.COM_QUERY, sql)
>   File "/Users/chris/Workspace/ve-darwin16/lib/python3.6/site-packages/pymysql/connections.py", line 1071, in _execute_command
>     raise err.InterfaceError("(0, '')")
> pymysql.err.InterfaceError: (0, '')

**Comment by dimitri-yatsenko** [comment]
Acceptable settings are specified in https://github.com/datajoint/mysql-docker/blob/master/my.cnf
If a server is not set up correctly, this is an administrative issue and not a `datajoint-python` API issue.

**Comment by eywalker** [comment]
This would be more appropriate as a documentation goal - such as FAQ or troubleshooting section. Unless I meet objections I will close this issue and start a corresponding issue at doc site.

**Comment by dimitri-yatsenko** [comment]
We should find a way to improve the error messages when this happens.

**Comment by ixcat** [comment]
updated:
since the traceback is not clear, catch the exception and rethrow it into a DatajointError which informs of the proper documentation/parameter to update

**Comment by dimitri-yatsenko** [comment]
The MySQL error is not informative and there does not seem to be a way to get the exact reason for the disconnect from the message alone.

**Comment by dimitri-yatsenko** [comment]
Let's close and improve documentation for cases of lost database connection.
