### ISSUE TITLE
add optional progress report to populate

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#367]
An option to populate to report progress and estimated completion time would be helpful.

Example:
```python
SpikeSort().populate(display_progress=True)
```

**Comment by eywalker** [comment]
Let's perhaps use something like `tqdm` (https://pypi.python.org/pypi/tqdm) to achieve this.

**Comment by dimitri-yatsenko** [comment]
Yes, that was my thinking.  It works great in command line and Jupyter.
