### ISSUE TITLE
Problematic behavior of `locals()` inside a funtion

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#368]
Use of `locals()` inside a function leads to unexpected behavior. For an example, the following code snippet

```python
def make_tables():
    schema = dj.schema('test', locals())
    
    @schema
    class A():
        definition = """
        id:  int     # id
        """
    @schema
    class B():
        definition = """
         -> A
         """
```
Calling the fucntion `make_tables()` will result in name resolution error for the foreign key reference `-> A` inside the definition of `B` despite the fact that the following works just fine:

```python
schema = dj.schema('test', locals())
    
@schema
class A():
    definition = """
    id:  int     # id
    """
@schema
class B():
    definition = """
     -> A
     """
```

The problem arise due to the fact that, for some reasons, the dictionary returned by the `locals()` do *not* stay updated when used inside a function. This can be demonstrated by the following code:

```python
def test_locals():
    names = locals()
    print(names.keys())   # will print out []
    # add new variables
    a = 10
    b = 5 
    print(names.keys())   # still print out []!
    print(locals().keys())  # ['names', 'a', 'b']
    print(names.keys())   # ['names', 'a', 'b']
```

This makes the use of `locals()` highly unreliable inside a function.

**Comment by dimitri-yatsenko** [comment]
Seems like a Python problem rather than DataJoint.   We should just document it, right?  It's uncommon to declare classes inside functions anyway and we may need to highlight this problem in our training course.

**Comment by dimitri-yatsenko** [comment]
Does Python claim `locals()` to return an updated object?  What's different about a function's namespace from a module's namespace?

**Comment by dimitri-yatsenko** [comment]
This should be fixed with the #412 when `context` is left as `None` (default) in the schema object.  Will someone please confirm?

**Comment by eywalker** [comment]
The use of `inspect.currentframe().f_back.f_locals` unfortunately does *not* solve this issue as illustrated below:

```python
def mock_schema():
    return inspect.currentframe().f_back.f_locals

def test_locals():
    names = mock_schema()
    print(names.keys())   # will print out []
    # add new variables
    a = 10
    b = 5 
    print(names.keys())   # still print out []!
    print(mock_schema.keys())  # ['names', 'a', 'b']
    print(names.keys())   # ['names', 'a', 'b']
```

I suggest that we move the population of the context via `inspect.currentframe().f_back.f_locals` at the very top of schema's `__call__`. This way, schema will make use of the most updated local context when it decorates a class. This will also allow for the schema object imported from other module to work properly using the new local context.

**Comment by eywalker** [comment]
Specifically I suggest we do the following. In `__init__` of `Schema`, we simply store passed in context without modification (thus `self.context` defaults to `None`). In the first line of `__call__` method (https://github.com/datajoint/datajoint-python/blob/master/datajoint/schema.py#L186) we then do:

```python
if self.context is None:
  context = inspect.currentframe().f_back.f_locals
```
and use `context` throughout the `__call__` method.
