### ISSUE TITLE
Escape `%` in the restriction string automatically

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#376]
Currently in order to do MySQL wild card matching in the restriction clause, users will have to type something like `attr like "test%%"` where as equivalent statement will be `attr like "test%"` in MATLAB. This is due to the fact that `%` denotes string interpolation and it messes with formatting logic used during query processing. However having to use different query formatting is rather weird, so I propose that we properly escape user's string so that all `%` gets replaced with `%%` automatically. If user continues to use the currently necessary `%%` in their string, this will obviously translate into `%%%%` which then sends `%%` to MySQL, but this should not be an issue.

**Comment by dimitri-yatsenko** [comment]
seems reasonable.   Will this be applied to all queries?

**Comment by eywalker** [comment]
Anywhere they'll pass in strings, yes.

**Comment by dimitri-yatsenko** [comment]
Even strings that are inside dicts?  e.g.  `rel & dict(a='3%')`

**Comment by dimitri-yatsenko** [comment]
`pymysql` may already have some sort of an escaping system built it on all strings passed into conditions that may be configurable.

**Comment by eywalker** [comment]
When you restrict by dict, you cannot do `like` matching anyway right? If not, we could even skip parsing in dict.

**Comment by dimitri-yatsenko** [comment]
that's why I asked at what point the substitution will be made.  It's worth looking into `pymysql`'s mechanisms since they deal with escapings.

**Comment by eywalker** [comment]
Actually, I take that back. I suppose if your string was litearally `"3%"` in the table, then you would want to match `a = "3%"` but I think you'll need `a="3%%"` now. I never tried this, but this would be a terrible behavior.

**Comment by eywalker** [comment]
Looks like `pymysql` wouldn't deal with this issue for you - https://stackoverflow.com/questions/3037581/how-do-i-escape-from-python-mysql-query

**Comment by dimitri-yatsenko** [comment]
So sounds like it needs to be handled at the lowest level then inside `dj.Connection.query`

**Comment by eywalker** [comment]
Assuming that we don't make use of the `%` based interpolation in either string itself or via `pymysql`'s substitution feature, yes, we can handle this at `dj.Connection.query`. We should verify.

**Comment by dimitri-yatsenko** [comment]
Or should we just ask people to use `%%` in the documentation?

**Comment by eywalker** [comment]
Nah, this should be fixed - having to type %% is annoying...

**Comment by dimitri-yatsenko** [comment]
Inserts too.
