### ISSUE TITLE
Error when accessing schema that already has ~log table but you don't have access to

### ISSUE THREAD

**Issue by mudphudwang** [datajoint/datajoint-python#379]
```python
natexp = dj.create_virtual_module('scadena_natimexperiment', 'scadena_natimexperiment')
```

    ---------------------------------------------------------------------------

    OperationalError                          Traceback (most recent call last)

    /usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py in insert(self, rows, replace, ignore_errors, skip_duplicates, ignore_extra_fields)
        262                         placeholders=','.join('(' + ','.join(row['placeholders']) + ')' for row in rows)),
    --> 263                     args=list(itertools.chain.from_iterable((v for v in r['values'] if v is not None) for r in rows)))
        264             except pymysql.err.OperationalError as err:

    /usr/local/lib/python3.5/dist-packages/datajoint/connection.py in query(self, query, args, as_dict)
        124                 warnings.simplefilter("ignore")
    --> 125                 cur.execute(query, args)
        126         except err.OperationalError as e:

    /usr/local/lib/python3.5/dist-packages/pymysql/cursors.py in execute(self, query, args)
        165 
    --> 166         result = self._query(query)
        167         self._executed = query

    /usr/local/lib/python3.5/dist-packages/pymysql/cursors.py in _query(self, q)
        321         self._last_executed = q
    --> 322         conn.query(q)
        323         self._do_get_result()

    /usr/local/lib/python3.5/dist-packages/pymysql/connections.py in query(self, sql, unbuffered)
        855         self._execute_command(COMMAND.COM_QUERY, sql)
    --> 856         self._affected_rows = self._read_query_result(unbuffered=unbuffered)
        857         return self._affected_rows

    /usr/local/lib/python3.5/dist-packages/pymysql/connections.py in _read_query_result(self, unbuffered)
       1056             result = MySQLResult(self)
    -> 1057             result.read()
       1058         self._result = result

    /usr/local/lib/python3.5/dist-packages/pymysql/connections.py in read(self)
       1339         try:
    -> 1340             first_packet = self.connection._read_packet()
       1341 

    /usr/local/lib/python3.5/dist-packages/pymysql/connections.py in _read_packet(self, packet_type)
       1013         packet = packet_type(buff, self.encoding)
    -> 1014         packet.check_error()
       1015         return packet

    /usr/local/lib/python3.5/dist-packages/pymysql/connections.py in check_error(self)
        392             if DEBUG: print("errno =", errno)
    --> 393             err.raise_mysql_exception(self._data)
        394 

    /usr/local/lib/python3.5/dist-packages/pymysql/err.py in raise_mysql_exception(data)
        106     errorclass = error_map.get(errno, InternalError)
    --> 107     raise errorclass(errno, errval)
    

    OperationalError: (1142, "INSERT command denied to user 'ewang'@'10.21.17.251' for table '~log'")

    
    During handling of the above exception, another exception occurred:

    DataJointError                            Traceback (most recent call last)

    <ipython-input-3-ad23ec27eb78> in <module>()
          4 detect = dj.create_virtual_module('detect', 'detect')
          5 sort = dj.create_virtual_module('sort', 'sort')
    ----> 6 natexp = dj.create_virtual_module('scadena_natimexperiment', 'scadena_natimexperiment')
          7 natimg = dj.create_virtual_module('scadena_synth_naturalimages', 'scadena_synth_naturalimages')

    /usr/local/lib/python3.5/dist-packages/datajoint/__init__.py in create_virtual_module(modulename, dbname)
         84     """
         85     mod = ModuleType(modulename)
    ---> 86     s = schema(dbname, mod.__dict__)
         87     s.spawn_missing_classes()
         88     mod.__dict__['schema'] = s

    /usr/local/lib/python3.5/dist-packages/datajoint/schema.py in __init__(self, database, context, connection, create_tables)
         71                 else:
         72                     self.log('created')
    ---> 73         self.log('connect')
         74         connection.register(self)
         75 

    /usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py in __call__(self, event)
        581                 version=version + 'py',
        582                 host=platform.uname().node,
    --> 583                 event=event), ignore_errors=True, ignore_extra_fields=True)
        584         except pymysql.err.OperationalError:
        585             logger.info('could not log event in table ~log')

    /usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py in insert1(self, row, **kwargs)
        123         For kwargs, see insert()
        124         """
    --> 125         self.insert((row,), **kwargs)
        126 
        127     def insert(self, rows, replace=False, ignore_errors=False, skip_duplicates=False, ignore_extra_fields=False):

    /usr/local/lib/python3.5/dist-packages/datajoint/base_relation.py in insert(self, rows, replace, ignore_errors, skip_duplicates, ignore_extra_fields)
        264             except pymysql.err.OperationalError as err:
        265                 if err.args[0] == server_error_codes['command denied']:
    --> 266                     raise DataJointError('Command denied:  %s' % err.args[1])
        267                 else:
        268                     raise

    DataJointError: Command denied:  INSERT command denied to user 'ewang'@'10.21.17.251' for table '~log'

**Comment by eywalker** [comment]
This appears to happen when 

1. the user tries to access a schema that already has `~log` table declared
2. the user does **not** have permission to insert into `~log` table

This kind of situation will likely arise frequently when a new user is given view only access to a schema.

Probably the easiest fix is for the `~log`'s `__call__` method to catch failure to ignore logging calls.

**Comment by dimitri-yatsenko** [comment]
Yes.  Another solution is to always give insert access to the auxiliary tables, i.e. those that begin with `~`.  That's an administrative decision that improves tracking of data access. Although in the future, we may migrate this function to the server side altogether and use triggers instead, removing this functionality from the client library.

**Comment by eywalker** [comment]
As you said that's a server side issue that we don't want to be involved in (at least not now). Besides, if the user has viewing rights on a table in schema, then DJ should allow access to the table whether or not they can insert logs into `~log`.

**Comment by dimitri-yatsenko** [comment]
It depends on how you view DataJoint.  If we view DataJoint as the whole system: clients and servers, then a valid approach is to establish some rules for granting privileges.  Then perhaps the more appropriate solution to establish the rule that any user who has any privileges to a schema should also have `INSERT` privileges to `~log`.

**Comment by dimitri-yatsenko** [comment]
I suggest that this error should throw a more meaningful message: "Please ask database administrator to grant INSERT privileges to the activity log table."  But I don't think that this error should be suppressed.

**Comment by eywalker** [comment]
At least based on how DJ acts now, I'd be in favor of separating the concern and requirements, and I still think that one should be able to grant simple view rights to a table without having to give insert rights on any table in the schema. Once DJ can bridge the separation between server and client more (i.e. by integrating more tightly with the server end), then more tight access management can be enforced reasonably.

**Comment by eywalker** [comment]
After some more discussion, we have decided to proceed by throwing a warning rather than an exception when a user with insufficient privilege (i.e. no `INSERT` privilege) on `Log` table tries to access schema with `Log` table already defined. This will allow for "viewing only" users to proceed with working with the tables but will still encourage them to seek appropriate `INSERT` privilege by database administrator.
