### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#38]
... and make sure it agrees with the licenses of the libraries we use.

**Comment by peabody124** [comment]
any problems with GPL?

**Comment by fabiansinz** [comment]
I just saw: Dimitry decided for MIT license. It's in the wiki.

**Comment by dimitri-yatsenko** [comment]
Yes, we have had this under MIT for a couple of years.  I am open to changing the license.  If we change to GPL, let's get everyone's approval.

**Comment by fabiansinz** [comment]
I am fine with almost everything. I think GPL might be too restrictive. James proposed to go with LGPL. However, I am also completely fine with MIT.

**Comment by eywalker** [comment]
I do agree that GPL is probably too restrictive. But I don't between MIT
and LGPL.

**Comment by eywalker** [comment]
I suppose we can close this issue now that we have agreed upon a license?

**Comment by dimitri-yatsenko** [comment]
I am fine with LGPL.  Anything special that needs to be done with regard to previous releases?
