### ISSUE TITLE
Deprecation warning for changed definition syntax. 

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#381]
In the past, the following syntax worked for defining tables:
```
@schema
class TestScores(dj.Computed):
    definition = """
    # testing the model across datasets
    
    -> BestModel
    test_source -> Source
    ---
    """
```
Now, this throws an error `TypeError: not enough arguments for format string`.

The solution is:

```
@schema
class TestScores(dj.Computed):
    definition = """
    # testing the model across datasets
    
    -> BestModel
    (test_source) -> Source
    ---
    """
```
It would be nice if this would give a more meaningful error message or a deprecation warning. `dj.__version__ == '0.8.1'`.

**Comment by dimitri-yatsenko** [comment]
Fixed in #381
