### ISSUE TITLE
Deprecate `ignore_errors` and alternate implementation of `skip_duplicates`

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#382]
After closer investigation of MySQL's `IGNORE` modifier effects (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#Comparison-of-the-IGNORE-Keyword-and-Strict-SQL-Mode) which lies at the heart of #347, I believe that the flag `ignore_errors` and current implementation of `skip_duplicates` can have undesired side effect on the database content. Given this I propose the following changes:

* Completely deprecate use of `ignore_errors` - users should employ Python's `try...except` logic to handle errors appropriately instead
* Change implementation of `skip_duplicates` such that only `duplicated entry`-related warnings would be suppressed.

**Comment by ixcat** [comment]
sounds reasonable at a high level...
