### ISSUE TITLE
ERD does not "see" inherited part tables

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#385]
ERD does not see classes that correspond to part tables defined in the superclass of a master table: 

```python
class Super:
    class Part(dj.Part):
        definition = """
        -> master
        """

@schema
class A(Super, dj.Computed):
    definition = """
    -> Upstream
    """

dj.ERD(schema).draw()
```

The ERD displays `A.Part` as `data_base.__super__part`, indicating that the class name lookup fails in this case.

Furthermore, issuing `schema.spawn_missing_classes()` redefines the original `A.Part`.

**Comment by dimitri-yatsenko** [comment]
This has to do with how nested classes are inherited in Python.   Python does not actually produce a separate nested class in each subclass.  For now, we will just recommend against using this method.

**Comment by guzman-raphael** [comment]
Based on latest assessment that this is not recommended, proceeding with closing the issue.
