### ISSUE TITLE
Serializing dict as blob assumes string keys

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#392]
It seems dict serialization was added last year in #248 by @eywalker . I'm trying to add a dict as a mediumblob to our database. The dict has integer keys, not string keys, and they map to tuples. It looks something like this:
```
{1:(0, 100), 2:(0, 200)}
```
Currently, datajoint assumes that keys are always strings:
https://github.com/datajoint/datajoint-python/blob/master/datajoint/blob.py#L286

I tried changing `pack_string(k)` to `pack_obj(v)`, which works fine while pack, but later I get a byte count assertion error when unpacking the blob here:
https://github.com/datajoint/datajoint-python/blob/master/datajoint/blob.py#L111

Any ideas?

**Comment by dimitri-yatsenko** [comment]
We are somewhat committed to keep MATLAB/Python interoperability.

**Comment by mspacek** [comment]
OK, then maybe the `pack_string()` call should be put in a try-except block, to catch errors in `value.encode('ascii')`, and report non-string keys as not allowed, instead of just raising an encoding error?

**Comment by dimitri-yatsenko** [comment]
I think we should allow non-MATLAB compatible serialization for those who want it.  The MATLAB compatible serialization will handle a set of basic things like ndarrays, string-keyed dicts, strings, and lists.  The rest will be serialized with a Python object serializer.  Perhaps we can add the `matlab_compatible=True` kwarg to inserts to allow this option.

**Comment by dimitri-yatsenko** [comment]
This issue will be rolled into #427.  Closing as duplicate.
