### ISSUE TITLE
unknown different plot behavior

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#396]
```plt.hist(alm.Session().aggr(alm.UnitExtracel() & 'unit_quality=2', ncell='count(*)').fetch('ncell').astype(float));```

vs no ```astype(float)```

in some configurations should be further investigated.

**Comment by dimitri-yatsenko** [comment]
this may be more of a matplotlib issue

**Comment by dimitri-yatsenko** [comment]
I am closing this.  This is has to do with differences between matplotlib versions.
