### ISSUE TITLE
Allowing for basic SQL aggregators like max, min, or sum

### ISSUE THREAD

**Issue by Visdoom** [datajoint/datajoint-python#401]
I'd like to request the feature that one could do simple sql queries of the functionality:
``` SELECT MAX(y), func_id  FROM Function GROUP BY id```

I need to find parameter sets that optimise a certain value and it would be grand to query the highest scoring parameter set without having to fetch all data from the db.

What do you think?

**Comment by ixcat** [comment]
Hello -

Thanks for the feedback -
Generally this should be possible via the aggregation operator  ```aggr``` and in some cases ```dj.U```-

https://docs.datajoint.io/queries/Aggr.html

however the documentation as you can see is lacking.

Here is an example of synthesizing an 'autoincrement'-style key taken from the datajoint-catalog ```RET1``` [example code](https://github.com/datajoint-catalog/djcat-RET1/blob/master/ret1_ingest.py):

```
# generate synthetic 'autoincrement' movie_id
movie_id = (dj.U().aggr(Movie(),n='max(movie_id)').fetch1('n') or 0)+1
```

we have a standing general task to get more examples concerning these features - hopefully soon.

**Comment by dimitri-yatsenko** [comment]
Aggregation is fully implemented using the `aggr` operator.  We need to improve the documentation and provide more examples.  Will you please provide a more detailed example?  

If the `id` in your query is the primary key of another entity set, e.g. `Foo`, then your query would be:
```python
Foo().aggr(Function(), m='max(y)')
```

**Comment by dimitri-yatsenko** [comment]
We are closing this for now.  The real issue is the lack of documentation on `aggr` and we will address it.

DataJoint implements aggregation quite differently from SQL.  It aggregates one entity set with respect to another.  `dj.U` is a special entity that is sometimes necessary when no appropriate entity set already exists to aggregate by.
