### ISSUE TITLE
add a string equivalent of `dj.key` in fetch

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#406]
Currently, `dj.key` is used to fetch the primary key.  However, this requires importing datajoint.  I propose to add a string equivalent of `dj.key`.  For example, this could be '<key>'.

Before:
```python
import datajoint as dj
import analysis
alphas, keys = analysis.Hyperparam().fetch('alpha', dj.key)
```
After:
```python
import analysis
alphas, keys = analysis.Hyperparam().fetch('alpha', '<key>')
```

**Comment by eywalker** [comment]
I agree that this would be a nice addition but would prefer something even simpler like `@key` or something along that line.

**Comment by dimitri-yatsenko** [comment]
how about `'KEY'`
After:
```python
import analysis
alphas, keys = analysis.Hyperparam.fetch('alpha', 'KEY')
```

**Comment by eywalker** [comment]
hm or perhaps `DJKEY`? That would make it sound more special.

**Comment by dimitri-yatsenko** [comment]
I think capitalized `KEY` is clearly special.  Everything else is always lowercase.

**Comment by eywalker** [comment]
Yeah but visually I'm not sure how much `KEY` stands out in comparison to something like `@key` or `<key>`.

**Comment by dimitri-yatsenko** [comment]
`KEY` easier to remember and it clearly stands out.  `@key` looks like a decorator or a MySQL variable and it may throw people off.

**Comment by eywalker** [comment]
Ok fair enough. Does `fetch` currently only work with lowercase? Does it correctly throw an error if any capital latter is included now?

**Comment by dimitri-yatsenko** [comment]
In a way.  Tables are not allowed to declare upper case attributes.  Fetch checks if attributes are in the heading and throws an error if they are not found, not matter the reason.

**Comment by eywalker** [comment]
Ok as long as `KEY` is currently not allowed now, I think it's fair.

**Comment by ixcat** [comment]
devils advocate - any of

1) any module is typically itself importing datajoint; idiomatically this means usually one can ```from lib import dj.key as key``` or refer to mod.dj.key

2) failing above, ```from datajoint import key```
3) set Table.key in relation classes as attribute pointing to datajoint.key

**Comment by eywalker** [comment]
Yeah but this is really suggested as a quick alternative to any of the above (in particular 1 and 2). As for 3, we definitely don't want to advocate for any `rel.key` to point to `dj.key` as it gives the wrong impression that `rel.key` only refers to the primary key for `rel`.
