### ISSUE TITLE
Use of imported schema object

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#413]
Currently, when you create a schema object in one module (i.e. Python file) using `locals()` and then import that schema object and use it to decorate a DataJoint user relation class, the lookup of foreign key names does not work. For example:

`module1.py`
```python
import datajoint as dj

schema = dj.schema('my_schema', locals())

@schema
class A(dj.Manual):
    definiton = """
    id:  int    # id
    """

# this works just fine
@schema
class B(dj.Manual):
    definition  = """
    -> A
    """
```

`module2.py`
```python
import datajoint as dj
from .module1 import schema   # importing schema object

# this still works because no foreign key reference made
@schema
class C(dj.Manual):
    definition = """
    id: int    # id
    """

# however, this doesn't work because imported schema object cannot look at the *current local* context
@schema
class D(dj.Manual):
    definition = """
    -> C
    """
```

Although this behavior is completely consistent and thus is expected based on how `locals()` work, the result is certainly counter-intuitive and may be error prone - especially because some cases of using imported schema object (e.g. when defining class `C` in the above example) actually works.

In conjunction to fixing #368 as aimed by #412 , I suggest that we also let `dj.schema('schema_name')` to be aware of the local context it is currently present **regardless of where it was defiend**.

**Comment by dimitri-yatsenko** [comment]
This was fixed by #417
