### ISSUE TITLE
Problem to delete part table if defined via wrong master table

### ISSUE THREAD

**Issue by coschroeder** [datajoint/datajoint-python#421]
I have the following problem with a definition of a part table:

I defined a part table (NewMaster.Trial) in the wrong way, by using an "old" mastertable. 
Looking like this:

```@schema
class OldMaster(dj.Computed):
    definition = """   
    ...
    """
    class Trial(dj.Part):
        definition = """  
        -> OldMaster
        ---
    ...
        """
    
@schema
class NewMaster(dj.Computed):
    definition = """   
    ...
    """
    class Trial(dj.Part):
        definition = """  
        -> OldMaster
        ---
    ...
        """
```

Now the question: How can I get rid of the parttable NewMaster.Trial?
By dropping NewMaster it is not dropped, because it is connected to OldMaster.
I have a lot of computed data in OldMaster, so I don't want to drop this.
Normally parttables are dropped (only?) via theire master...
Is there a solution in datajoint?

**Comment by eywalker** [comment]
Hi @coschroeder, have you tried simply dropping the part table directly? As in `NewMaster.Trial().drop()`?

**Comment by coschroeder** [comment]
Thanks! That works, interesting.

**Comment by eywalker** [comment]
Thanks for bringing this up - we'll update the documentation to make this point clear!

**Comment by samuelbray32** [comment]
In case someone finds this issue first when facing this, the `force=True` solution does not currently work.  See the `drop_quick` method in #374 discussion if needed
