### ISSUE TITLE
"External" capabilities

### ISSUE THREAD

**Issue by horsto** [datajoint/datajoint-python#425]
I have some questions regarding the _external_ field and function. I am mostly interested in its implementation in python. 

1. For (very) large datasets it would be useful to have the option to perform partial loading / memory mapping of data when it is fetched - is there anything available/planned like this? 
2. how complex can arrays become that are written to the external field - are there any limitations? I understand that the aim here is to increase compatibility between python matlab and arbitrary datatypes are not supported? 
3. Is there a way to use the _external_ functionality (storage handling, md5 hash creation, ...) for a file that hasn't been loaded and serialised using the datajoint interface (for example an arbitrary binary file). As a concrete example we want to write out converted *and* original data to external storage, but organise in the same schema.

**Comment by dimitri-yatsenko** [comment]
1.  No, currently there is no support for partial loading.  A fetch is all or nothing.  

If this feature is necessary, let's open a separate dedicated issue. 

However, if an object is too large, perhaps it could and should be _normalized_ into smaller components stored and queried individually for greater query flexibility.

2.  Currently we support only one serialization scheme that mimics MATLAB datatypes.  The MATLAB implementation can store any MATLAB structure.  Numpy arrays of arbitrary dimension are supported.   In Python we haven't yet matched some of the more complex MATLAB structures.  However, we are moving toward customizing serialization and compression protocols to allow greater flexibility on the python side.   Most likely what will happen is:   common data types (ndarrays, lists of strings, scalar dicts) will be fully compatible between MATLAB and Python.  The more complex language-specific structured will be stored in customizable serialization protocols. 

3. Yes, you can convert a binary string into a numpy array and insert.  We can add support for inserting binary strings directly.

**Comment by dimitri-yatsenko** [comment]
Closing this issue.  Please re-open if the question is unresolved.  Or submit a new issue for other questions.
