### ISSUE TITLE
Use of `decimal` type in primary key prevents `reserve_jobs=True`

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#428]
Currently insertion of `decimal` datatype into blob is not supported. Because of this, when you have a computed table with `decimal` primary key attribute, `populate(reserve_jobs=True)` fails due to the failure of inserting the primary key dictionary (containing the decimal key attribute value) into the `jobs` table `key` blob field. Worse yet, when this error occurs, this occurs silently, such that it appears as if the whole `populate` jobs completed very quickly.

**Comment by dimitri-yatsenko** [comment]
The problem description is not accurate. `populate` works normally with decimal fields and does not skip any jobs.  The `key` field in the jobs tables is not used for anything internally; it is saved only for debugging purposes.

**Comment by dimitri-yatsenko** [comment]
To close this issue, remove `packable_or_none` from `jobs.py`.
