### ISSUE TITLE
Fix table and base logic

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#43]

**Comment by eywalker** [comment]
The separation between `Table` and `Base` was not logically clean, and have been addressed in #52  and #54 . The main machinery for table declaration has been moved into `Table`. The difference in these two classes now mainly stems from what kind of *foreign references* in the table definition can be handled. For an example, if the table definition contains `-> a.Subjects`, the name `a` must be resolved in order for this definition to make sense. In the context of `Base` derivatives which is bound to a module, then `a` is interpreted to be the name of a module bound to some database. The steps taken by `Base` in resolving the module name reference is described in detail in #40 (this needs to be placed in the documentation...)

For a `Table` instance that does not have a module binding, there is no straightforward or meaningful way to resolve a reference to another module. Hence foreign table reference `-> a.Subjects` will result in an error when found in the definition passed into `Table` derivative. However, you can still refer to another table as long as you know the actual name of the database the table is found in, and you can do so by putting the database name surrounded by backquotes (\`) as in ``-> `dbname`.Subjects``.

This reference resolution logic is now encapsulated into a method `get_base(module_name, class_name)` and can easily be extended to allow for more elaborate referencing (should we ever come up with one).

**Comment by eywalker** [comment]
Now the name of `Base` changed to `Relation`, perhaps I should change the name of the method to `get_relation` (although it can sometimes return a `FreeRelation` instead of a `Relation`)...

**Comment by fabiansinz** [comment]
I am for it. Most of the time it will be a normal relation anyway.

**Comment by dimitri-yatsenko** [comment]
Is this resolved?

**Comment by eywalker** [comment]
I think this issue can be considered resolved as `Relation` and `FreeRelation` are working properly.
