### ISSUE TITLE
deleting a schema with downstream dependencies

### ISSUE THREAD

**Issue by arsenyf** [datajoint/datajoint-python#447]
I tried to delete a schema (or some particular tables within this schema) and could not do it because it had downstream dependencies in a different schema. It would be very helpful to make the error message more informative about the problematic dependencies, because in this case for instance I was not aware that there are downstream dependencies in some other schema. Same holds form the MATLAB version. Thanks

**Comment by guzman-raphael** [comment]
Related to #476

**Comment by ixcat** [comment]
moving to #476
