### ISSUE TITLE
len(rel) is slow

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#458]
I noticed that if I have a long table (relation) `rel`, then calling `len(rel)` can be quite slow. It takes about 2 seconds on our setup to return if the length is say, 300000 tuples. Here's the code in `RelationalOperand`:

```python
    def __len__(self):
        """
        number of tuples in the relation.
        """
        return U().aggr(self, n='count(*)').fetch1('n')
```
After looking at the code for `RelationalOperand.preview()`, I noticed that it uses `len(self.proj())` instead of `len(self)`, which returns the same result in about half the time. Could `__len__` be sped up? Maybe just replace it with `len(self.proj())`?

**Comment by dimitri-yatsenko** [comment]
Does it pass the tests?  It's time for another careful review of the DataJoint to SQL transpilation.  We have a few issues open related to it.  It's the hardest part of the code.

**Comment by mspacek** [comment]
Actually, this is even faster, seems to return immediately no matter the table size:
```python
    def __len__(self):
        """
        number of tuples in the relation.
        """
        query = 'SELECT COUNT(*) FROM %s' % self.full_table_name
        return self.connection.query(query).fetchone()[0]
```
I'm probably being naive. I'll try and run the tests.

**Comment by mspacek** [comment]
So the above only works when `len()` is called on a full table. As soon as it's restricted or joined or otherwise modified, `self.full_table_name` is no longer available, and even if it was, it obviously wouldn't give the right answer. I don't think I understand enough about the internals to figure this out, but maybe someone else can find a way to optimize `__len__`?

**Comment by dimitri-yatsenko** [comment]
Yes, there is room for optimization.  SQL transpilation is the hardest part of the code.   I will work on it as part of resolving other issues as well: #449, #386, #450.

**Comment by dimitri-yatsenko** [comment]
Here is another example.  The following query:
```python
len(dj.U('up_factor') & stimulus.Trippy))
```
produces the following SQL
```sql
SELECT DISTINCT `n` FROM 
    (SELECT DISTINCT count(*) as `n` FROM 
        (SELECT DISTINCT `up_factor` FROM 
            (SELECT DISTINCT `up_factor` FROM 
                (SELECT * FROM `pipeline_stimulus`.`trippy`) as `_s37`) as `_s38`) as `_s39`) as `_s3a`
```
whereas it could be accomplished with
```sql
SELECT count(distinct `up_factor`) as `n` FROM `pipeline_stimulus`.`trippy`
```
Unfortunately, MySQL does not optimize the long query and it can take a very long time.
