### ISSUE TITLE
Add pandas.DataFrame methods

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#459]
Ever since we've started using datajoint, I've been frustrated by how hard it is to access data in a table. I often just want to get a few rows and/or columns so I can examine some of the data, and to do that, I don't want to have to type a complicated restriction followed by a fetch. I've added some convenience methods/properties to a mix-in class that we inherit from for all of our tables. Here's a quick description of some of them:
- `df`: fetches the whole table, returns it in a DataFrame - this can be slow for big tables
- `head`: fetches just the first `n=25` tuples in the table, returns it in a DataFrame - very fast
- `tail`: fetches just the last `n=25` tuples in the table, returns it in a DataFrame - slower than `head`
- `full`: prints out the entire table in a DataFrame, without skipping over any rows

Once in a DataFrame, the data is trivial to get at using direct column and row indexing. Another benefit is that the DataFrame does a nicer job of displaying as much data as possible in the given screen space.

The code for the above is quite trivial. Would there be any interest in integrating these into datajoint? I'd be happy to do it.

(Sorry for not using the proper database terminology, but the terms "table", "row" and "column" are much more intuitive to most users than "relation", "tuple" and "attribute").

**Comment by eywalker** [comment]
Hi @mspacek!  I'd be interested in looking at your utility implementation if anything to understand your point better.

**Comment by dimitri-yatsenko** [comment]
Yes, let's review and discuss the best way to do it.

**Comment by mspacek** [comment]
Sure! Here it is:
```python
class ConvenienceTable(object):
    """Mix-in class to add some convenience methods and properties to a DJ table"""

    def get_df(self, offset=None, limit=None):
        """Fetch the whole table or restrict to offset and limit, return in a DataFrame"""
        return DataFrame(self.fetch(offset=offset, limit=limit))

    df = property(get_df)

    def get_head(self, n=25):
        """Fetch the head of the table (first n entries), return in a DataFrame"""
        return self.get_df(offset=None, limit=n)

    head = property(get_head)

    def get_tail(self, n=25):
        """Fetch the tail of the table (last n entries), return in a DataFrame"""
        nrows = len(self) # this is slow as of datajoint 0.10.0
        #nrows = len(self.proj()) # this is currently faster
        offset = nrows - n
        return self.get_df(offset=offset, limit=n)

    tail = property(get_tail)

    def get_full(self):
        """Print out all the rows of the DataFrame"""
        print(self.df.to_string())

    full = property(get_full)
```

**Comment by dimitri-yatsenko** [comment]
We could add this to the `UserRelation` class at the expense of adding `pandas` dependency. 

Alternatively, this class can be mixed at the class declaration time at the user's discretion but less conveniently.

**Comment by dimitri-yatsenko** [comment]
Hm..  should we do this or not?  It seems that loading the fetch result into a DataFrame is just too simple:
```
pd.DataFrame(a.fetch())
```
does the same as 
```
a.df
```
But the first solution keeps `datajoint` lighter and more independent.   Is the feature worth the increased complexity?

`head` and `tail` presume a particular sorting.  `MySQL` sorts by the primary key but it generally should not be assumed for more complex queries. A more efficient implementation of `tail` would have been to simply reverse the sorting from `ASC` to `DESC` and not have to get the total count.   Sorting by the primary key is fast.

I think we should just add a HOWTO section to the documentation describing work with pandas.  This  should also include inserting data from a pandas dataframe.

**Comment by mspacek** [comment]
Sounds good. Another option would be to `from pandas import DataFrame` only within the e.g. `get_df()` method, so that pandas need not be a requirement for datajoint, just an optional dependency if you want to use such shortcuts.

Yes, the `head` and `tail` stuff were naive. Would be great to have a better implementation. I don't know enough about MySQL to do it myself.

**Comment by eywalker** [comment]
Wouldn't it be better to add a keyword argument like `as_df=True` in the `fetch` instead?

**Comment by dimitri-yatsenko** [comment]
Perhaps.  But @mspacek wanted the convenience.  If you fetch, you might as well just wrap the fetch in `pd.DataFrame` without all the trouble.

I am providing this solution as a test.  It's lightweight and it works more efficiently than @mspacek original solution.  If we don't like it, we can drop it.

**Comment by dimitri-yatsenko** [comment]
The `head` and `tail` feature is kind of nice.
