### ISSUE TITLE
Fix long lines

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#460]
I've noticed there are a lot of long lines in the code. I normally set myself the rather generous limit of 95 characters, but that's regularly exceeded throughout. Should we set a limit for datajoint and stick to it?

**Comment by dimitri-yatsenko** [comment]
Yes, let's comply with PEP 8.  However, let's not make corrections solely for the sake of PEP 8 compliance.   Let's improve PEP 8 compliance gradually as part of working on other problems. 

This is good and relevant: https://www.youtube.com/watch?v=wf-BqAjZb8M
