### ISSUE TITLE
support for auto-batching/chunking of inserts

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#462]
In many cases, one is processing a large number of records one at a time for addition into a datajoint schema, but needs to restructure code to insert groups of records in batches for performance reasons. Having support for such a 'batching' functionality within datajoint itself would allow the user to deal with individual records in a  'natural' way by using ```.insert1``` as each record is encountered/processed, and remove the the need to radically restructure code around batches for performance when necessary.

One possible syntax to support this might be ```Rel.insert1(record, batch_size=10)```. 

Some means to 'flush' pending inserts might also be necessary; I propose: ```Rel.flush_inserts()```

Other items possibly worthy of exploration would be how this might relate to auto-population transactions and error handling (since control flow for a batched ```insert1``` record with errors is now non-local).

**Comment by ixcat** [comment]
Also: a similar mechanism might also be useful in the case of large/long running deletes; I didn't file an issue yet because this is a less common use case but thought I'd mention it here since this is a similar sort of 'batch' scenario.

**Comment by dimitri-yatsenko** [comment]
Labeling `wontfix` until urgency is confirmed and we assign to a release.

**Comment by ixcat** [comment]
just noted it seems to be a similar type of scenario as:
https://github.com/datajoint/datajoint-python/issues/312

**Comment by dimitri-yatsenko** [comment]
I am closing this.  Let's find cases when this is a problem and address them then.  This seems like a complex feature for a problem that has other solutions.
