### ISSUE TITLE
(A & B) * B results in an error

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#463]
Currently the following query:

```python
(A & B) * B
```

throws an error like:
```python
Cannot join relations on dependent attribute `xxx`
```
where `xxx` is a non-primary key attribute of the relation `B`

**Comment by dimitri-yatsenko** [comment]
Yes, it's because it tries to optimize `(A & B) * B` as `A * B & B` to avoid an extra subquery.   This has to do with rules of query optimization.  We need to add this to tests.

**Comment by eywalker** [comment]
Yeah I thought so but isn't it weird then that the error message says there is an issue with join? I would have expected error about restricting with dependent attribute
