### ISSUE TITLE
dj.connection should allow specifying client character set

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#468]
Related to ongoing unicode support discussions (see also #455 , #453).

In order to properly interoperate with a unicode-supporting schema, the datajoint connection object needs to provide a method to specify client character set encoding.

e.g, when called something as follows should be passed according to some configuration:

```
$ sed -ne 92,95p ~/ve/lib/python3.6/site-packages/datajoint/connection.py
        self._conn = client.connect(init_command=self.init_fun,
                                    sql_mode="NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,"
                                             "STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION", charset='utf8',
                                    **self.conn_info)
```

(hard coding obviously not the correct solution - above example simply illustrative of function call 'charset' argument addition against current trunk for the specific case of utf8)

**Comment by dimitri-yatsenko** [comment]
Fixed with #456 -- the charset is now set in `dj.config['connection.charset']`.
