### ISSUE TITLE
Primary key attributes should respect order in which they are specified

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#47]

**Comment by dimitri-yatsenko** [comment]
The description is ambiguous.  How about the following? 
 1. The order of the attributes in a table should match the order of attributes in its declaration 
 1. The reverse engineered definition should exactly match the original definition.
Both these conditions are met in the MATLAB version of datajoint and we should replicate the function.

**Comment by dimitri-yatsenko** [comment]
If you meant something else, please describe and provide a specific example to replicate the problem.

**Comment by dimitri-yatsenko** [comment]
Failed to reproduce.  Closing as invalid.
