### ISSUE TITLE
implement user roles

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#472]
Newer MySQL (8.0) and MariaDB (10.0.5+) support 'role based' authentication/permissions -
It might be good to support this (e.g. via dj.config) for those who need it.

https://dev.mysql.com/doc/refman/8.0/en/set-role.html
https://mariadb.com/kb/en/library/roles_overview/

**Comment by dimitri-yatsenko** [comment]
Does Amazon Aurora support roles?

**Comment by ixcat** [comment]
Roles are MySQL 8+ or Maria 10.0.5+

Aurura is based on 5.7 currently (update was in 2/2018) so I do not expect this feature to be backported at present.

**Comment by dimitri-yatsenko** [comment]
Aha, at least 5.7 supports JSON operations!  (unrelated to this issue)

Let's wait with roles until we determine the future architectures.

**Comment by dimitri-yatsenko** [comment]
I changed the title because datajoint's goal is not to implement MySQL features but to use MySQL and other backends to support useful features.

**Comment by dimitri-yatsenko** [comment]
I will close for now.  These types of features should be defined strategically based no user cases rather than on availability of features in MySQL.
