### ISSUE TITLE
dj.ERD plotting - should resolve beyond relabeling layer when additional depth given

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#477]
Given a schema of 2 tables A and B where b.b.b (module, table, attr) is a renamed reference to a.a.a,  dj.ERD(a) + 1 will stop at the renaming 'number' used for b.b rather than to the actual table of b.b. It would probably be better to resolve + 1 to actual tables rather than renaming labels. (noted @eywalker)

**Comment by dimitri-yatsenko** [comment]
Would you rephrase the problem? Perhaps an example?

**Comment by ixcat** [comment]
Probably over explained - a much more simple explanation is that when using 'erd + 1' syntax, the erd display can stop at the numbered renaming circles rather than the actual tables the attribute comes from. It would probably be better to resolve the '+1' fully to actual tables.

For example - if one is still needed I can try to create one; This was noted by @eywalker & I just logged the issue; @eywalker do you have the actual example you were using handy?

**Comment by dimitri-yatsenko** [comment]
Yes, I agree.  I remember fixing this problem earlier.  I need to reproduce the remaining cases to be able to fix them.

**Comment by dimitri-yatsenko** [comment]
Fixed in #651
