### ISSUE TITLE
dj.ERD renaming labels increment across subsequent calls

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#478]
it seems that dj.ERD renamed-attribute label numbers are kept across subsequent calls to dj.ERD

e.g. if on first call, the renamed attribute labels 0,1,2 exist, on the next call there will be 3,4,5 instead, etc

**Comment by dimitri-yatsenko** [comment]
Yes.  Is that a bad thing?

**Comment by eywalker** [comment]
Yes, it's a bad thing because it doesn't make sense and people would be wondering what the number means. Far better if ERD is completely reproducible across calls.

**Comment by ixcat** [comment]
a) what would be the rationale for doing it this way?
b) it produces inconsistent / confusing behavior to users
c) it could suggest some variable(s) is/are not being properly sanitized across calls, which in turn could imply some sort of bug in some corner case that we are not seeing

**Comment by eywalker** [comment]
Agreed with @ixcat

**Comment by dimitri-yatsenko** [comment]
Assigning the same unique number to the same node every time across all ERDs is a challenging problem.   Perhaps we could avoid it altogether.  Maybe we could leave the circles blank and show the entire reference query upon tooltip hover?

**Comment by dimitri-yatsenko** [comment]
ok, I think we should remove the numbers altogether since they carry no useful information.

**Comment by dimitri-yatsenko** [comment]
It's not difficult in two identical calls.  But it is difficult in two slightly different calls.  In either case, I don't think the numbers play any significant role and they can be safely omitted for now.

**Comment by eywalker** [comment]
I agree with @dimitri-yatsenko - the number carries no useful information so would rather just not display anything.
