### ISSUE TITLE
Keyboard interrupt exception during fetch

### ISSUE THREAD

**Issue by david-klindt** [datajoint/datajoint-python#487]
Would it be possible to handle keyboard interrupt exceptions during fetch with a context manager? Sometimes I run a long fetch and it takes a while and I forgot something or have to cancel it but then I lose connection to the database when I keyboard interrupt and have to restart my noetbook.

**Comment by dimitri-yatsenko** [comment]
Hi @david-klindt,

Just for reference, could you provide a sample calling code that you would use in this case?

**Comment by dimitri-yatsenko** [comment]
Are you really asking for a way to be able to interrupt the query without having to rerun a notebook to re-establish the connection?

**Comment by dimitri-yatsenko** [comment]
It appears as though it is necessary to restart the connection after an interrupt https://github.com/PyMySQL/PyMySQL/issues/287    We could allow reconnecting upon the next query.  However, within a make call, transactions will be interrupted.

**Comment by david-klindt** [comment]
yes #279 should fix it for my use case, thanks!
