### ISSUE TITLE
Restriction by 'some_attr = 0' returns all tuples with values that do not cast to integers when some_attr is of type varchar

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-python#488]
For an attribute of type `varchar`, restricting by an `int` causes MySQL to cast the tuple attributes to `int` rather than casting the restriction value to `string`. This can cause odd behavior.

Example:

```
@schema
class Table(dj.Lookup):
    definition = """
    some_attr: varchar(16)
    """
    contents = zip(['Test', '1', '1test'])
```

`Table & 'some_attr = 0'` returns `Test`
`Table & 'some_attr = 1'` returns `1` and `1test`

**Comment by austin-hilberg** [comment]
Manually casting the `int` values to `string`, i.e. with `'some_attr = "0"` produces expected behavior, but it would be a reasonable expectation for users not to have to do that.

**Comment by eywalker** [comment]
As pointed out [here](https://stackoverflow.com/questions/21762075/mysql-automatically-cast-convert-a-string-to-a-number), using MySQL mode of `STRICT_ALL_TABLES` should address this issue. I have updated the recommended configuration found in https://github.com/datajoint/mysql-docker. Let's test to verify that this fixes the issue.

However, it may still not be a bad idea to perform a conversion like the one suggested above on DJ side.

**Comment by eywalker** [comment]
Looking further into this, it is actually likely an issue in this line: https://github.com/datajoint/datajoint-python/blob/master/datajoint/connection.py#L98

We will likely have change `STRICT_TRANS_TABLES` to `STRICT_ALL_TABLES`

**Comment by dimitri-yatsenko** [comment]
Is this a document-but-`wontfix`?

**Comment by eywalker** [comment]
No this is actually something to be fixed inside the DataJoint `Connection` object, replacing the config `STRICT_TRANS_TABLES` with `STRICT_ALL_TABLES`.
