### ISSUE TITLE
Incorrect documentation: fetch.as_dict()

### ISSUE THREAD

**Issue by smackesey** [datajoint/datajoint-python#489]
[Docs](https://docs.datajoint.io/queries/Fetch.html) say this should work to fetch data as a dictionary:

    data = rel.fetch.as_dict()

This gives an error. I looked at the source and the correct code is:

    data = rel.fetch(as_dict=True)

**Comment by ixcat** [comment]
thanks for your report.

**Comment by dimitri-yatsenko** [comment]
The issue has been directed to the documentation repo.  Thank you.  Closing.
