### ISSUE TITLE
provide 'standard' mechanism for database schema name selection (database.prefix?)

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#490]
We have been discussing the use of ‘configurable’ database strings for testing purposes in schema development work -

One useful mechanism to use is a ‘database prefix’ - a string which is prepended to the ‘common’ name of a database schema - for example:
```
prefix = ‘my_test_’
dbname = ‘database’
```
-> application code will use: `‘my_test_database’`

In the codebases where this pattern has been applied, we have implemented this mechanism via:
```
schema = dj.schema(dj.config.get('database.prefix', '') + 'database')
```
So, wondering if it would make sense to standardize this mechanism in some way since it is useful for schema development/testing and other uses - either directly in the `dj.schema` logic or some other means (utility function, etc)

**Comment by dimitri-yatsenko** [comment]
In general use, people use several groups of databases with different prefixes.  If we just blindly apply the same prefix to all schemas, it could lead to many hard to explain errors. 

I would vote to standardize this mechanism by documenting the current use.

**Comment by dimitri-yatsenko** [comment]
What about providing the ability to do regular expression replacements?  That way one could be judicious about replacements.
```python
dj.conf['schema_substitutions'] = [('^alice_', 'test_alice_'), ('^bob', 'test_bob_')]
```

**Comment by ixcat** [comment]
That could work as well. 

The 'blind prefix' case could still be applied via `^` substitution and more specific safeguards could still be used where they are needed. 

Code would be more complicated however -
Also - how to handle multiple regexp matches would need to be defined -
Do we match on the first match or all matches? If all matches, do secondary+ matches apply to the the 'current' string at this stage of processing, or if the original string, which match takes precedence, etc.

**Comment by dimitri-yatsenko** [comment]
I would say perform all the substitutions in sequence. 

Yes, the originally requested feature would be implemented as:
```python
dj.conf['database.schema_substitutions'] = [('^', 'test_')]
```

**Comment by dimitri-yatsenko** [comment]
Another solution is to pass function that transforms the name with default `None`.

```python
dj.conf['database.schema_renaming'] = lambda s: 'test_' + s
```

**Comment by dimitri-yatsenko** [comment]
Yep, `TypeError: Object of type 'function' is not JSON serializable`

**Comment by dimitri-yatsenko** [comment]
Nope, saving bytecode with is not the right approach because python bytecode is not guaranteed to be compatible between releases of python.  

How about we save it as a string?  This will limit the replacement function to lambda expressions:
```python
dj.conf['database.schema_renaming_function'] = `lambda s: 'test_' + s`
```

**Comment by eywalker** [comment]
I'm not fully convinced that allowing injection of an arbitrary function into the config is really needed. This should be thought through a bit more before making it into the master branch.

**Comment by dimitri-yatsenko** [comment]
After trying a couple of solutions, I don't see anything more elegant than doing this on the application side.  This functionality does not seem to belong inside the datajoint library: any external implementation will be clearer and less bug-prone.

I propose to close this issue.
