### ISSUE TITLE
rename internal classes and modules to comply with current terminology?

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#494]
Should we rename the internal class and module names to be consistent with terms we use in the documentation?

`relational_operand.py` -> `query.py`
`RelationalOperand` -> `Query`
`base_relation.py` -> `table.py`
`BaseRelation` -> `Table`
`user_relation.py` -> `user_table.py`
`UserRelation` -> `UserTable`
`FreeRelation` -> `FreeTable`

**Comment by eywalker** [comment]
as far as I can tell, this will not affect existing codes that use DataJoint right? If so, then yes, I think making it consistent with the documentation terminology can be helpful.

**Comment by dimitri-yatsenko** [comment]
That's right.  No effect on user.
