### ISSUE TITLE
support ellipsis in proj to signify "all remaining attributes"

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#499]
At the moment, there isn't a convenient mechanism to rename an attribute or calculate a new attribute while keep all the other secondary attribute.  In matlab, we use '*' for that purpose.  I propose to use ellipsis. 

For example, 
```python
s.proj(a='b', ...)    # rename b to a, keep everything else.
```

**Comment by eywalker** [comment]
But that order wouldn't work with positional and keyword arguments, right? The form would have to be `s.proj(..., a='b')` which is perhaps a bit more awkward. 

Alternatively, we could just do `s.proj('*', a='b')` keeping the syntax closer to MATLAB

**Comment by dimitri-yatsenko** [comment]
yes, either ellipsis `...` or `*` would have to go first, which is less intuitive. 

Another solution is to have a special version of `proj` called `rename` which would all attributes that have not been renamed. 

I think I prefer
```python
s.proj(..., a='b', c='cos(b)')
```

**Comment by eywalker** [comment]
As you suggested, having something like `rename` is an option but given that we'd want that to be able to do things like computed attribute that `proj` can do, that's too similar in function to `proj`.

I think I do prefer that syntax of `s.proj(..., a='b', c='cos(b)')` as well, and this is not *too* awkward as something similar already appears in NumPy indexing as in:

```python
x = np.random.randn(1, 2, 3, 4))
x[..., 0]
```

Only thing against it is the difference with MATLAB. If we use `'*'` then it would be more consistent between Python and MATLAB in syntax.
