### ISSUE TITLE
Prohibit inserts from outside `make` in auto-populated tables.

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#511]
Auto-populated tables should not permit inserts from outside their `make` method.   Raise an error when the user attempts to do so.

**Comment by eywalker** [comment]
Key addition is the `allow_direct_insert=True` keyword argument to insert to override this restriction that is present by default on `AutoPopulate` classes.

**Comment by dimitri-yatsenko** [comment]
`allow_direct_insert=None`  It's basically `False` for by default for auto-populated tables.

**Comment by eywalker** [comment]
Makes sense
