### ISSUE TITLE
Set default number of display rows to 10 (or 12)

### ISSUE THREAD

**Issue by ecobost** [datajoint/datajoint-python#523]
I think users commonly increase the default of 7. This is a bit annoying when using a python terminal (more convenient in a notebook where you can put it in a cell). A default of 10 rows seems sensible enough.

**Comment by ecobost** [comment]
If loading wasn't inefficient and there was a way to scroll through rows rather than printing them as output, the optimal for me would be to show the entire table. Because those do not hold, I think the best is to show as many rows while not hoarding the terminal. I think most people would be ok with around 10-15 rows. On the other hand if the table has a lot of attributes and the row will be divided in 2 lines even 10 rows may be too much.
Personally, I'm often changing the display_limit to 10 or 12 or 15.

**Comment by dimitri-yatsenko** [comment]
ok, i will make it 12.
