### ISSUE TITLE
`pandas` support

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#537]
Add comprehensive support for `pandas` for represent datajoint entity sets.
1. `pandas` will become a required package for datajoint
2.  `dj.config` will provide the option `fetch_format` to specify the default format for `fetch` output: `pandas.DataFrame` or `numpy.rec_array` or list of `dict`s.
3.  `fetch` will support returning pandas dataframes when configured. `fetch` will provide a keyword argument to select the output format.  The returned dataframe will be indexed by the primary key.
4.  Restriction operator will accept `pandas` as an argument as in `table & df`
5.  `insert` will accept a pandas dataframe as input for inserting.
6.  Add the methods `head` and `tail` as a shortcut to fetch the first and the last few elements (ordered by primary key) from a query expressions. The result will be in the default format specified in `dj.config`.

This issue subsumes issue #459.

**Comment by eywalker** [comment]
A few thoughts:
1. I know I'm the one who said it but I'm having second thoughts on making `pandas` dependency required. I suppose we could always fall back to test during import instead?
2. To me fetch format should be between just the record array and pandas DF, and not include an option to fetch as dictionary always. Fetching as dict is a bit special as we will use this whenever doing `fetch1` or `KEY` regardless of the return type of the record type.
3. I agree, but I'm thinking about keeping `as_dict=True/False` and supplying an additional keyworkd argument like `rec_format="numpy"/"pandas"` 
4-6. Completely agreed

**Comment by dimitri-yatsenko** [comment]
1. optional dependency is a bit of a nuisance since now it will require testing both pandas installed and pandas not installed.  What are the main reasons for not adding pandas dependency?

**Comment by eywalker** [comment]
Just the idea of not having an additional strict dependency. I'm 50/50 about this anyway.

**Comment by dimitri-yatsenko** [comment]
We did this with graphviz but primarily because it can be difficult to install.  Pandas' installation is fairly reliable.

**Comment by dimitri-yatsenko** [comment]
One risk with pandas is that new users might get confused by having to learn two distinct data models: datajoint and pandas.  They are sufficiently distinct yet many things look very different.  That was the reason that initially kept me from bringing pandas into the picture.
