### ISSUE TITLE
Importing table definition during transaction causes transaction to commit

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#539]
Assume you have a module with a table definition as follows:

`sample.py`
```python
import datajoint as dj
schema = dj.schema('sample')

@schema
class A(dj.Manual):
    definition = """
    id: int
    """
```
Further, *assume that this table has not been declared yet*. 
From another file or interactive console, assume we run the following:

```python
import datajoint as dj
schema = dj.schema('sample')

@schema
class B(dj.Manual):
    definition = """
     id: int
     """

conn = dj.conn()
conn.start_transaction()
B.insert1((1, ))
import sample  # import the other module, triggering the definition of the table
conn.cancel_transaction()
```

After the above code is run, the table `B` ends up containing the entry `id: 1`, *despite the request to rollback the transaction. This is caused by the fact that when the module `sample` was imported during the transaction, the table creation statement caused the open transaction to be committed prematurely.

To avoid this, any create statement (e.g. schema or table create) should check if the connection is in transaction and if yes, throw an error to prevent a premature commit of the transaction in progress.

**Comment by dimitri-yatsenko** [comment]
There can be other scenarios when a table is declared from inside a transaction.  For example, there is nothing to prevent a user from declaring a table inside a make call.  Raising an error in such cases should address all these scenarios.

**Comment by eywalker** [comment]
I agree, and raising error for the table creation statements and schema creation statements should catch all of those cases.

**Comment by dimitri-yatsenko** [comment]
MySQL ought to have an option to disable DDL statements while in transaction.  It's a little insane that they just commit the transaction instead.

**Comment by dimitri-yatsenko** [comment]
This was fixed in https://github.com/datajoint/datajoint-python/pull/565
