### ISSUE TITLE
Assign error codes to DataJoint error

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#540]
Currently a lot of DataJoint operation related errors result in `DataJointError` thrown. While the error message is typically helpful, it requires us to check the message to know precisely what kind of error occurred, and in particular, we don't check for the exact content of the `DataJointError` during the testing, often just saying that `DataJointError` should be thrown. I'm wondering if it would make sense for us to either:

1. assign error codes to each error so that checking for error identity becomes simpler, and/or
2. subdivide `DataJointError` into subclasses to better represent different kinds of errors.

**Comment by dimitri-yatsenko** [comment]
I favor 2: Subclass from DataJointError.  We have already begun doing so with `DuplicateError`.

**Comment by dimitri-yatsenko** [comment]
I favor subclassing because of the more laconic and expressive handling by `try: ... except`

**Comment by dimitri-yatsenko** [comment]
In general, I think this issue is not sufficiently specific to know for sure when it's "fixed".  Can we make it more specific?

**Comment by dimitri-yatsenko** [comment]
I am closing this issue.  To resubmit, please have specific errors rather than a general blanket issue for abstract problems.
