### ISSUE TITLE
Check datatype compatibility pre vs post #514

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#544]
With PR #514, we now actively restrict what MySQL attribute data types are formally supported in DataJoint. This unfortunately means that if users were using "unsupported" data types prior to this PR, their code will cease to work (or worse yet, they will continue to be able to use the table, but will encounter an issue the next time they try to re-declare the table). To minimize issues caused by this, I've listed all datatypes present under MySQL so that we can explicitly rule them in vs out of our supported data types list. Following is the suggested criterion for the selection:

1. you could insert into an attribute of that datatype
2. you could fetch from an attribute of that datatype
3. Fetched value from that datatype can be inserted back directly without any inconsistency or error
4. the use of the datatype in DataJoint makes sense/fits the expected use of DataJoint

with that here are the data types collected from [MySQL 8.0 reference manual](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-overview.html). Checked item means that the decisions are already made for support/non-support and have been verified:

### Numeric types
- [x] INTEGER (supported?)
- [x] (TINY/SMALL/MEDIUM/BIG)INT (**supported**)
- [x] DECIMAL (**supported**)
- [ ] NUMERIC
- [x] FLOAT (**supported**)
- [ ] REAL
- [x] DOUBLE (**supported**)
- [x] BOOL
- [x] BOOLEAN
- [ ] BIT
- [ ] BIT(M)

### Date and time types
- [x] DATE
- [x] TIME
- [x] DATETIME (**supported**)
- [x] TIMESTAMP
- [x] YEAR

### String types
- [x] CHAR
- [x] VARCHAR
- [ ] BINARY
- [ ] VARBINARY
- [x] (TINY/MEDIUM/LONG)BLOB
- [x] (TINY/MEDIUM/LONG)TEXT
- [x] ENUM
- [ ] SET

**Comment by dimitri-yatsenko** [comment]
NUMERIC is just an alias for DECIMAL.  
We have no plans to support TEXT.
We do not support SET.  Sets are serialized into blobs.
We do not support BIT since there is no equivalent datatypes in MATLAB and Python.

**Comment by eywalker** [comment]
Ok thanks for the info. It is also important that we check what was the state of usage before we implemented this explicit check. If the data type was never usable before then that’s fine. However if it was actually usable before then we should carefully evaluate if dropping the “unofficial support” is ok. Bool is an example where we did not officially support but was functional and we decided to support. Just want to make sure we don’t miss other cases like that.

**Comment by dimitri-yatsenko** [comment]
Here is the current regular expression that checks whether datatype is supported.  Notice that it only checks the beginning and not the entire string. 
```python
    acceptable_datatype_pattern = r'^(time|date|year|enum|(var)?char|float|double|decimal|' \
                                  r'(tiny|small|medium|big)?int|bool|' \
                                  r'(tiny|small|medium|long)?blob|external|attach)'```
```
This means that the pattern accepts `datetime` and `boolean` even though they are not explicitly listed.

**Comment by dimitri-yatsenko** [comment]
They only candidates for being previously allowed (and now unsupported) would be `numeric` and `real`.  Both are aliases for other data types and would be happily converted into `decimal` and `double`, respectively.

**Comment by dimitri-yatsenko** [comment]
For `numeric` and `real`, should we do the same thing as with `bool` and accept them at declaration time?  In `describe` they will be re-defined as `decimal` and `double` respectively.

**Comment by eywalker** [comment]
Yes, I'd agree with that.
