### ISSUE TITLE
Hide local configuration

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#555]
New users often commit their configuration files in public code repositories, presenting a data security threat.   I propose to keep the local configuration file into a hidden folder, e.g. `./.datajoint`, hoping that users will have the sense not to add it to their git repository.

**Comment by eywalker** [comment]
I have a feeling that the making anything hidden will in fact make it even more likely that they'll commit it as they don't see it and thus they are not aware of the file. Better solution perhaps would be offer to include `datajoint-config.json` into `.gitignore`?

**Comment by dimitri-yatsenko** [comment]
Creating a hidden directory is a common approach for preventing committing sensitive files.  It takes an extra step to stage files in a subfolder for commit.  We cannot be sure that the users use git for version control, so writing into .gitignore may be a less general solution.

**Comment by eywalker** [comment]
I get the idea of using hidden folder/file, and I also thought about this, but quite honestly I don't think this makes it more likely that the user would be careful to not include it. In fact, given that it is a hidden file (which is btw only true on Mac/Linux), it is just more likely that they'll miss it.

**Comment by dimitri-yatsenko** [comment]
ok, i am closing then.  This is a problem to look for and guard against, continuously.  Perhaps we should insist that the configuration file be stored outside any repos.

**Comment by austin-hilberg** [comment]
Would it make sense for `dj.config` to check for a `.gitignore` file when config changes are made, and issue a warning if the config file is not ignored?

**Comment by eywalker** [comment]
I do like @austin-hilberg’s idea actually

**Comment by dimitri-yatsenko** [comment]
That is still too git-specific and I am not sure we want to introduce such overly-specific solutions.

**Comment by austin-hilberg** [comment]
How many version control systems would we need to address in order to cover say 90% of users? I would assume that git would get us most of the way there already.
