### ISSUE TITLE
Projection removes antijoin constraints

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#558]
I have a collection stimuli that I wanted to extend. The `imagenet.Album` tables have a field called `collection_id`. In the first line, I identify new images that are not yet in the existing set of stimuli. Note that the `stimulus.StaticImage.ImageNet` tables does not have `collection_id`. 

In the second line I create a selection of new stimuli and directly give them a new `collection_id`. However, when I do that, datajoint forgets about the antijoin constraints above. When I remove the `collection_id=3` call the antijoin constraints are applied correctly. 

```
candidates = stimulus.StaticImage.ImageNet()  - imagenet.Album.Single() - imagenet.Album.Oracle()
selection = candidates.proj('image_class', 'image_id', collection_id='3')```

**Comment by eywalker** [comment]
Here is a minimally reproducing case:

```python
schema = dj.schema('test')

@schema
class A(dj.Lookup):
    definition = """
    id: int
    """
    contents = zip(range(10))
    
@schema
class B(dj.Lookup):
    definition = """
    id: int
    id2: int
    """
    contents = zip(range(5), range(5, 10))
```

```python
>>> len(A-B)
5   # correct behavior
>>> len((A - B).proj(id2='3'))
10  # this is a bug!
```

**Comment by eywalker** [comment]
After studying the code, here is an even simpler (and worse) example of failure caused by the same issue:

```python
@schema
class X(dj.Lookup):
    definition = """
    id: int
    """
    contents = zip(range(10))
 
d = dict(id=3, id2=5)
```

Given these,

```python
>>> len(X & d)
1  # as expected
>>> len((X & d).proj(id2='3')
0 # incorrect result!
```

**Comment by dimitri-yatsenko** [comment]
These are two different and somewhat unusual cases.

**Comment by eywalker** [comment]
The underlying cause is the same - projecting in an attribute that actually exists in the restricting dictionary or expression. It does point out logical error in the handling of projection on a restricted expression

**Comment by dimitri-yatsenko** [comment]
Yes, this is clearly an urgent bug but adding more subqueries is not a good solution.  We are working on updating query processing.

**Comment by eywalker** [comment]
Whatever the form will be, we will put some form of a workaround by the end of this week. Hopefully we don’t have to put in the subquery workaround, although it will be temporary anyway.

**Comment by dimitri-yatsenko** [comment]
The fix here is to prohibit creating new attributes with the name of an existing attribute. This will now raise a `DataJointError`
