### ISSUE TITLE
unit tests arbitrarily delete all databases called `test`

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#588]
we shouldn't assume full control of the 'test' database namespace, but instead track test databases individually; or at least use something more datajoint specific.

**Comment by dimitri-yatsenko** [comment]
It's `djtest`. I think that's specific enough.

**Comment by dimitri-yatsenko** [comment]
it's also configurable through the `DJ_TEST_DB_PREFIX` environment variable.

**Comment by ixcat** [comment]
whoops. apologies :) closing.
