### ISSUE TITLE
[dev branch] new `TYPE_PATTERN` data patterns do not support `INTEGER`

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#596]
The `TYPE_PATTERN` matchers in delcare.py do not allow `INTEGER` to pass through, but only the various `INT` flavors.

Previously this would allow table definition.

We do not explicitly list 'integer' in `https://docs.datajoint.io/python/definition/06-Datatypes.html`; not sure what is best fix.

**Comment by dimitri-yatsenko** [comment]
I will add `integer` as a synonym for `int`

**Comment by dimitri-yatsenko** [comment]
Fixed in #600. Will close after merging into master.
