### ISSUE TITLE
Allow argument `order_by='attr'` in Table() call 

### ISSUE THREAD

**Issue by kklurz** [datajoint/datajoint-python#598]

**Comment by dimitri-yatsenko** [comment]
Would you provide additional details or an example? `Table()` yields an reference to the table in the database, which represents a set of entities. A set, by definition, is unordered. 

The returned object has a preview method for displaying in text mode or in HTML mode in Jupyter.  The preview gives a quick idea of what the object represents. It is generated by the preview methods `__repr__` and '_repr_html_`, which do not take any arguments, so it would not make sense to pass an `order_by` argument to them.

Order only makes sense in `fetch` methods when the data are retrieved from the database into a Python object. Other variants of `fetch` are `head` and `tail` and they do accept the `order_by` keyword argument.

**Comment by dimitri-yatsenko** [comment]
Marking invalid until clarified.

**Comment by kklurz** [comment]
Sorry for not being specific enough, I'll describe it in more detail:

I am using a Jupyter Notebook and by calling Table() the `_repr_html_` preview method is called. This method has a default ordering of the data in the table which can not be changed by the user at the moment. I think it might be useful to allow this method to take an argument  ` order_by='attr' ` so the preview of the table is already displayed in the way that the user needs.

**Comment by dimitri-yatsenko** [comment]
There is not really a way in Python to pass arguments to `_repr_html_` and `__repr__`. The previews are primarily used in interactive mode to get a quick glimpse of the object but not necessarily details. I think what you are looking for could be accomplished by using something like:

```python
Table.head(order_by='attr', format="frame")
```
This will return the result as a pandas frame, which is displayed nicely in Jupyter.

**Comment by kklurz** [comment]
OK, thank you! I will close this issue then.
