### ISSUE TITLE
expression/GroupBy should not require additional attributes

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#604]
The expression.GroupBy class currently requires that groupings have additional attributes beyond the common set. This prevents some projection expressions, such as those counting occurrences of child records when the parent:child relationship is 1:1 (e.g. parent & child have identical primary keys). A current workaround is to use dj.U to virtually extend the table so that additional attributes are present, however this is needlessly complex.

e.g.:
```
Parent().aggr(Child, ct='count(*)', keep_all_rows=True)
```
does not work, but something like:
```
Parent().aggr(Child.proj(fake='"fake"') * dj.U('fake'), ct='count(*)', keep_all_rows=True))
```
does.

**Comment by guzman-raphael** [comment]
@ixcat Looks like this was missed in the reporting of the `CHANGELOG.md` for `0.12.0`. Closing as addressed.
