### ISSUE TITLE
Should we rename `__iter__` in primary_iter?

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#61]
I think the name would fit better. I would then use `__iter__` for iterating through all tuples of a relation and return them as tuples. This would have the advantage to be able to use for loops like

```
for animal_id, date_of_birth, genetic_line in mice_relation:
   ...
```

What do you think?

**Comment by dimitri-yatsenko** [comment]
I was thinking of the following use of the iterator: Use it to return primary keys so that it can be used in for loops and the result could be used to restrict other relations. For example:
```
for key in Mice():
     for key in Scans() & key:
           image((Scans() & key).fetch('green_image'))
```

**Comment by fabiansinz** [comment]
I don't understand this example. Is `Ìmage` another relation? Shouldn't it be 

```
for key in Mice():
   for key2 in Scans() & key:
       image(key2).fetch('green_image')
```

**Comment by dimitri-yatsenko** [comment]
By `image`, I meant a function that display the image.  If `Image` were another relation and it had a method called `image` for plotting, the code would become:
```python
    for key in Mice():
        for key in Scans() & key:
              (Image() & key).image()
```
Yes, I used the same variable `key` in both loops.

**Comment by fabiansinz** [comment]
Ah, ok I missed on bracket. But you could still do it with the other iterator. The original code would become 

```
for key in Mice().primary_iter():
        for image in Scans() & key:
              ...
```

which I think is actually easier.

**Comment by dimitri-yatsenko** [comment]
`project()` returns the primary key, so if we make the iterator yield tuples of the relation, then the code above would be:
```python
for key in Mice().project():
    for image_tuple in Scans() & key:
        ...
```
This makes sense.

**Comment by dimitri-yatsenko** [comment]
The most logical solution would be to change `__iter__` to yield entire tuples. Then `project()` is used to project the relation onto its primary key.

**Comment by fabiansinz** [comment]
I agree. I'll implement it.

**Comment by dimitri-yatsenko** [comment]
so the answer to the original question is "No." Closing.
