### ISSUE TITLE
Using 'sudo pip' as suggested in the tutorial is a bad practice

### ISSUE THREAD

**Issue by aless80** [datajoint/datajoint-python#617]
Please consider to review your recommendation in the tutorial (and maybe in your docs) about the following point: 

> pip3 install datajoint
> ...
> Depending on how your Python environment is configured, you may have to prefix sudo to the above command.
[tutorial](https://tutorials.datajoint.io/setting-up/datajoint-python.html)

Using 'sudo pip' is generally frowned upon as it can seriously mess up python. The best option is using a virtual environment, followed by pip --user. On the internet you can find some debate on the 'sudo pip' practice, but it is certainly not the best practice. 

I actually tried pip3 datajoint --user. Datajoint did not work, as some dependency (the enum function) was not working. In contrast, datajoint was working after installing it in a virtual environment. 

Also suggest users to use to install dependencies with `pip install -r requirements`. Consider to add matplotlib to requirements.txt, which is needed by e.g. ERD.draw()

**Comment by guzman-raphael** [comment]
Hi @aless80. Thank you for your feedback. Regarding documentation, feel free to submit new issues to our [documentation repo](https://github.com/datajoint/datajoint-docs). I have recreated this issue [here](https://github.com/datajoint/datajoint-docs/issues/217). You can subscribe to updates there. Closing this one.
