### ISSUE TITLE
Best practices for working with shared pipelines?

### ISSUE THREAD

**Issue by tjd2002** [datajoint/datajoint-python#623]
Once we build a schema for our lab's database, how should multiple analysts go about working with the resulting pipeline?

In the docs, there is a section on ["Working with existing pipelines"](https://docs.datajoint.io/python/existing/Existing.html) that shows how to use Virtual Modules. Is this the preferred method? And/Or should we be sharing the source for the current schema definition (so that folks can see the schema at a glance, including any comments)?

**Comment by dimitri-yatsenko** [comment]
If the upstream pipeline is stable, the the pipeline code is shared and the downstream pipeline developers may simply import the modules. Make sure that `dj.schema` is called with `create_tables=False`. This way when the schema does change, the downstream users won't attempt create some old tables. Generally, downstream analysis developers should not have `CREATE` privileges in the upstream schema.

You are right that using `dj.create_virtual_module` or `schema.spawn_missing_classes` allows downstream users to see the schema, query the data, and develop new analyses without needing to import any upstream pipeline code.

**Comment by dimitri-yatsenko** [comment]
This resolved.
