### ISSUE TITLE
pyparsing 2.4.1 interop creates connection issues

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#629]
The pyparsing 2.4.1 release seems to cause something in our code to hang for connections (at least; rest can't be tested w/o connection)

data points thus far:
- ubuntu 16.04 and system (pyparsing 2.0.3 via apt vs 2.4.1 in pip)
- datajoint-python travis builds
- personal test in ve (old 2.3.0 and 2.4.0 OK; 2.4.1 NOK)

**Comment by dimitri-yatsenko** [comment]
This was a bug in `pyparsing.Or` introduced in `pyparsing 2.4.1`

**Comment by ixcat** [comment]
looks like builds/unit tests are now ok after #631 : `https://travis-ci.org/datajoint/datajoint-python/builds/562698261`

@guzman-raphael @eywalker @dimitri-yatsenko who can cut a 0.11.3 release, or if someone wants to walk through I can do

thinking we close after this?

**Comment by guzman-raphael** [comment]
@ixcat I can as long as everyone is in agreement, however, the one piece that I don't know yet is how to properly update the `CHANGELOG.md`. 

@eywalker anything special?

**Comment by dimitri-yatsenko** [comment]
I have just updated both the CHANGELOG and the version number for both 0.11.2 and 0.12.rev5. Ready for release.

**Comment by dimitri-yatsenko** [comment]
Fixed with #631
