### ISSUE TITLE
in 0.12.dev3, dj.Diagram(schema.Table) + 1 does not show downstream tables if the foreign key is renamed

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#644]

**Comment by shenshan** [comment]
<img width="348" alt="Screenshot 2019-08-29 17 59 09" src="https://user-images.githubusercontent.com/2539832/63986042-08e2fc80-ca87-11e9-9ae5-0592555b66ee.png">

**Comment by guzman-raphael** [comment]
@shenshan We are good to close this issue, correct?

**Comment by dimitri-yatsenko** [comment]
I believe this is fixed. @shenshan Would you confirm?

**Comment by guzman-raphael** [comment]
Fixed in `0.12.0` release. 
Closing
