### ISSUE TITLE
timediff used in proj() does not give a correct result

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#646]
<img width="928" alt="Screenshot 2019-08-30 13 32 07" src="https://user-images.githubusercontent.com/2539832/64049811-ef938c00-cb2a-11e9-9bb0-2ae38f61db65.png">

**Comment by dimitri-yatsenko** [comment]
Please try without the `"` surrounding the attribute names. If you must use quotes around attribute names, use back quotes \` as in
```python
session_with_duration = (acquisition.Session & cluster).proj('session_end_time',
    session_duration='TIMEDIFF(`session_end_time`, `session_start_time`)
```
