### ISSUE TITLE
handle ambiguous leading slashes in s3 locations

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#648]
S3 buckets are strictly speaking, k:v stores, where the key is a string.

AWS S3 and min.io (possibly others) allow folder-based navigation in their web UI's based on '/' separation of key components.

However, min.io does not seem to allow leading '/' components, and the folder view for AWS results in confusing '//' paths. e.g. top level '/folder' becomes '//folder', with '/' being a viewable entry at top level.

Therefore, I propose always trimming leading slashes from S3 objects to allow minio-S3 usage, of top level bucket directories (e.g. `location=''`) for blob storage, and prevent the confusing case for aws-S3.

One potential downside could be that existing S3 configurations using leading slashes may regress, or not be usable by other non-blob S3 access patterns (e.g. filepath objects). These sorts of regressions could be fixed by users bulk moving 'moving' the objects in '//folderlike' to 'folderlike' via web gui.

**Comment by dimitri-yatsenko** [comment]
I have not seen this. If double '/' appear anywhere, they should be eliminated. How do I reproduce this problem?

**Comment by ixcat** [comment]
@dimitri-yatsenko , the steps to reproduce are:

- spin up minio
- set `'location': ''` in an s3 configuration

indeed removing all duplicate slashes might be even better..

**Comment by ixcat** [comment]
Per PR in #649 will be treating as outside scope to 'normalize', but also will adjust paths to be generated without 'inherent', leading slashes, which work for top-level storage in both minio and s3. Using location='/' will yield the behavior described here as ambiguous.
