### ISSUE TITLE
Mix of print statements and logging results in messy logs

### ISSUE THREAD

**Issue by Raphtor** [datajoint/datajoint-python#667]
I am trying to incorporate Datajoint into a larger project, but half of the output from it is in the form of print statements to stdout, which results in messy logs. I've tried suppressing the output, but since my application is threaded, it results in other logs being suppressed as well. Would it be possible to use only the logging module?

**Comment by dimitri-yatsenko** [comment]
Good point and a quick fix. Yes, let's clean this up in 0.12.1?

**Comment by guzman-raphael** [comment]
@Raphtor, while we are still working through priority issues for the next release, could you try the following pattern? Should allow you to suppress print's from individual DataJoint statements or a block (but will still print errors):

```python
from datajoint import conn, DataJointError
import os
import contextlib

with open(os.devnull, "w") as f, contextlib.redirect_stdout(f):
    conn()
    raise DataJointError('example')
print('No connection details printed...')
```

**Comment by ixcat** [comment]
would be good to also have a configurable 'log-to-file' hook when this happens - c.f:
`https://github.com/mesoscale-activity-map/map-ephys/blob/master/pipeline/shell.py` `logsetup()` function , etc.
