### ISSUE TITLE
blobs for arbitrary objects

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#67]
Currently, blobs can only store n-dimensional numerical arrays.  The data serialization is done using the mym protocol to keep the data compatible with the matlab side of things.  Mym supports all MATLAB data structures: structures, structure arrays, cells, objects, etc.  In practice, we only store numerical arrays in blobs.  Everything else is usually normalized into their own attributes.  So I am okay with deviation from the mym protocol for serializing other objects than numerical arrays.  This is low priority for now since this feature is not in strong demand.

**Comment by aecker** [comment]
I'm not sure if anyone other than you actually does it like that. Also, how do you deal with an array of strings? Create a separate table with (index, string) as attributes? Not very efficient/convenient...

Also, I store structures quite often in the database. Usually they're class objects cast to struct. It would create a lot of overhead with little benefits if I had to normalize those into attributes.

**Comment by dimitri-yatsenko** [comment]
@aecker, if I understood you correctly, you agree that this issue needs to be address.

Yes, ideally there is rarely a good reason to store anything than numeric arrays in a blob, but we should probably provide this ability.  The question is do we do this in a matlab-compatible way or just serialize using python-native object serializers.

**Comment by aecker** [comment]
Yes I agree, it should be implemented. And it should be implemented in a way that data can be  accessed transparently from both host languages.

**Comment by dimitri-yatsenko** [comment]
Complete transparency probably cannot be accomplished for arbitrary objects because python has datatypes that are not supported by matlab.  What we can do, however, is to provide python support for all matlab datatypes.

**Comment by dimitri-yatsenko** [comment]
Has the been resolved in 25dff0925?  Ready to close?

**Comment by dimitri-yatsenko** [comment]
Added tests in fa3e26edf, closing.
