### ISSUE TITLE
Support wider range of database connections

### ISSUE THREAD

**Issue by chrisroat** [datajoint/datajoint-python#670]
Connecting securely to an external database sometimes may require one of the following:
- SSL support
- Unix socket connections

I think these are standard parameters in the `pymysql` library.  This doesn't look like too much work - If we go with datajoint, I would be willing to help implement.

**Comment by ixcat** [comment]
Thank you for the feedback.
TLS/SSL support is coming in 0.12 (any day now, available as a pre-release in pip) - see also:

`https://github.com/datajoint/datajoint-python/pull/620`

I'm fairly certain setting `database.host` as `localhost` will use socket, but perhaps it connects IP over `127.0.0.1`. That said, there's not a way to override the socket path which may be useful in some situations.

Also, side-note, depending on your use case, you can call `dj.conn()` directly to setup a customized connection for special cases. We use this mechanism occasionally to connect to 2 databases simultaneously.

For sockets, what do you envision this looking like? checking database.host as a path?

**Comment by dimitri-yatsenko** [comment]
@chrisroat Please try the pre-release version with `pip install --pre datajoint` to work with TLS.

**Comment by chrisroat** [comment]
Thanks for the tips on what is coming (and how to get it)!

For a unix socket, I was just thinking of using the `unix_socket` on a pymysql client object.  I did that on a fork of the repo, and it worked as I expected.

I had been using the cloud proxy to connect to a Google Cloud SQL like this:
https://cloud.google.com/sql/docs/mysql/connect-external-app#6_start_the_proxy

**Comment by guzman-raphael** [comment]
@chrisroat TLS connections are now supported in the official release 0.12.0+.

**Comment by dimitri-yatsenko** [comment]
Shall we close this issue?

**Comment by chrisroat** [comment]
Sure.  I think unix sockets might be a niche need.
