### ISSUE TITLE
Add `multiprocess` argument to populate() to launch a multiprocessing.Pool

### ISSUE THREAD

**Issue by mspacek** [datajoint/datajoint-python#695]
It would be nice if `populate()` had something like an `multiprocess` argument that automatically set up a `multiprocessing.Pool` with separate MySQL connections, and then distributed calls to the table's `make()` method across the different processes in the pool. This would avoid having to manually launch multiple independent instances of Python+datajoint to take advantage of multiple CPU cores.

**Comment by mspacek** [comment]
See the [mp](/datajoint/datajoint-python/tree/mp) branch.

**Comment by dimitri-yatsenko** [comment]
Getting to this soon!

**Comment by A-Baji** [comment]
Closed in Datajoint Python v0.13.3
