### ISSUE TITLE
Append table definition to docstring

### ISSUE THREAD

**Issue by SimonRenner** [datajoint/datajoint-python#699]
Thinking about improving the documentation of our own database, we thought it would be nice to add the table definition to its docstring. We do this using a decorator on the table definition somewhat like this:
```python
def docappend(cls):
    cls.__doc__ += cls.definition
    return cls

@docappend
@schema
class MyTable(dj.Imported):
    .....
```
To us, it seemed like a minor but useful feature to include in a future version of datajoint.

**Comment by dimitri-yatsenko** [comment]
we could make this the default behavior of `@schema`.
