### ISSUE TITLE
jobs table requires `enable_python_native_blobs`

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#700]
Data serialized to the jobs table uses insert data which falls into the `enable_python_native_blobs` category, meaning that job reservation as currently written won't work without this flag enabled.

(some) Possible fixes:

1) Skip serializing this data for not-enabled native-blob installs
2) Temporarily set `enable_python_native_blobs` using dj.config contextmanager and insert
3) Recode blob logic to explicitly save using structured array

**Comment by dimitri-yatsenko** [comment]
Fix in #703 implement solution 3.
