### ISSUE TITLE
DataJoint should facilitate work with database hosting services or "hubs"

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/datajoint-python#715]
In the event that DataJoint is utilized against a scalable deployment of database hosting services or `hubs`, requirements are as follows:

- No subdomain will be dedicated for databases instances.
- Allow host to be specified such that it queries a DJHub API target e.g. parse host config if matching pattern `hub://<DJHub_host>/<organization>/<project>`
- Requests will be unauthenticated (for now) since we assume that `projects` will be initially all public. Once there is interest in private, we will add authentication on requests to those specific `projects`. Similar to how the GitHub REST API behaves.
- Configuration should allow flexibility for backend in case we need to relocate servers to different hosts and/or modify ports.
- Requests should be secure and enforce TLS connections (Database connection treated separately).
- Allow room for expansion of API as it grows to provide more controls and access functions on DJHub data.
- Include helpful error handling
- Handle use case when a `project` has been relocated to a new endpoint in backend
- Specific request/response for initial API target was agreed as follows:
```
Host: <DJHub_host>
Route: /v0.000/get_database_fqdn
Method: POST
Body: {"org": "<organization>", "project": "<project>"}
Response: {"database.host": "<database_server>:<database_port>"}
```

Note: The above assumes best practice of backend hosting service with a suggested implementation.

**Comment by ixcat** [comment]
implemented as plugin: https://github.com/datajoint/datajoint_connection_hub-python
