### ISSUE TITLE
Packet sequence number wrong 

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#722]
I have been getting this error periodically.
```
pymysql.err.InternalError: Packet sequence number wrong
```
I am creating this issue for tracking, in case other people are getting it too while I investigate.

**Comment by ixcat** [comment]
PyMySQL 422 seems to indicate this may be multithread related (not putting full link here since it updates their tracker)

**Comment by dimitri-yatsenko** [comment]
I was not using multithreading.  But it's reproducible: It happens when I try to insert a very large blob that exceeds `max_packet_size`. MySQL disconnects and then on the next connection, it throws  "Packet sequence number wrong."  This is avoided, of course, by increasing `max_packet_size` or by using an external store.

Let's keep this issue open for a while to see if others run into this.

**Comment by dimitri-yatsenko** [comment]
closing since this was just for tracking. This is a quirk of MySQL.
