### ISSUE TITLE
Unable to run unit tests using nosetests

### ISSUE THREAD

**Issue by ishaan007** [datajoint/datajoint-python#723]
I am trying to add a few more unit tests to datajoint. I am unable to run the existing unit tests defined in datajoint/test folder using  nosetests.

I run the following command from datajoint directory  to run tests defined tests/schema.py

`nosetests -s tests/schema.py`

Please help out

**Comment by guzman-raphael** [comment]
@ishaan007 Thank you for the report! Looks like one of our certs has expired. I will make an update to apply a fix shortly.
