### ISSUE TITLE
How to append more info to CONN_INFO while writing unit tests

### ISSUE THREAD

**Issue by ishaan007** [datajoint/datajoint-python#733]
So I am trying to code up some unit tests for a new feature for datajoint, that our team developed. I need to add some more attributes to CONN_INFO for my test cases. What would be the best practice for it ? What it be okay if I add dj.config to all my new test cases and dont use CONN_INFO at all ?

**Comment by guzman-raphael** [comment]
Welcome @ishaan007. Would you mind elaborating a little bit more on what features you are trying to test and your test cases? We love learning about how others are adopting and evaluating DataJoint.

Typically, modifying `CONN_INFO` should not be necessary. Our unit testing approach is to conduct them as self-contained such that they are portable. If a specific set of tests require specific `dj.config` settings, then they can be specified within the context of your test (as you suggested). 

Keep in mind: `CONN_INFO` is used only for 'testing' database access credentials and thus should not be changed across tests. `dj.config` can be used but that assumes that your feature is explicitly configured by end-user for use. If this is configuration that is only necessary for your tests, then you can simply define them as attributes within a test class, test method, or test module level.

**Comment by guzman-raphael** [comment]
@ishaan007 Closing this issue based on the provided feedback. If there is anything that was missed or if there is more to add, feel free to reopen.
