### ISSUE TITLE
log table growth

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#737]
Somewhat a 'discussion' ticket than a concrete issue for the moment -

User mentioned large log tables resulting from continuous background workers - 
While cleanup is fairly straightforward, it might make sense to:

a) Have some control of logging of jobs to log table

b) Have some facility for auto or periodic cleanup according to some parameters

Also: it was noted that many entries related to deleting autopopulate keys from the jobs table were primarily the source of the log growth. Since these particular entries don't relate directly to user data deletion, it might make sense to disable logging them to slow the log table growth.

**Comment by dimitri-yatsenko** [comment]
ok, let's just not log operations on the jobs table or any of the auxiliary tables.
