### ISSUE TITLE
Expose simple access to table attributes.

### ISSUE THREAD

**Issue by stephenholtz** [datajoint/datajoint-python#738]
For an imported `Table` you currently need to use `Table.heading.attributes.keys()` to retrieve the names of the attributes within the table. Propose adding a property that gives the keys as a list. e.g. `Table.attributes` will return the list of attributes. 

This is in the spirit of the `table_name` property already in `table.py`.

Is this worth a PR?

**Comment by dimitri-yatsenko** [comment]
`Table.primary_key` -- list of primary attributes
`Table.heading.nams` -- list of all attributes

**Comment by stephenholtz** [comment]
Ah, my mistake - I overlooked that and will use it. 

To be more harmonious with the documentation and terminology I would still vote for `Table.attributes`, but realize it is a small point.
