### ISSUE TITLE
Should we have a switch in settings that makes the library prompt for confirmation before deleting?

### ISSUE THREAD

**Issue by fabiansinz** [datajoint/datajoint-python#74]

**Comment by dimitri-yatsenko** [comment]
perhaps a common switch for all interaction.  Such as "prompt_before_critical_operations=True".

**Comment by fabiansinz** [comment]
I like that.

On 05/14/2015 09:46 PM, Dimitri Yatsenko wrote:
>
> perhaps a common switch for all interaction. Such as
> "prompt_before_critical_operations=True".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datajoint/datajoint-python/issues/74#issuecomment-102232356>.
>

-- 
Dr. Fabian Sinz
contact info: http://goo.gl/o87zXC

**Comment by dimitri-yatsenko** [comment]
fixed in 9e22bf8
