### ISSUE TITLE
Programmatic creation of DJ description strings for existing classes with type hints

### ISSUE THREAD

**Issue by rgerkin** [datajoint/datajoint-python#745]
I would like to be able to reuse a lot of my existing classes (which also have utility outside of DataJoint framework) without adding descriptions to all of them (which are largely redundant with the type hints or comments I already have).  

Would there be interest in me contributing a (more fleshed out, exception handling) version of this: 
 
```
class MyClass:
    """A regular Python class that does not use DataJoint"""
    
    x: int = 3
    """type: int"""
    
    y: str = 'something'
    """type: str"""

def make_dj_description(cls, type_map=None):
    '''A function for producing DataJoint descriptions based on type hints'''
    _type_map = {'int': 'int', 'str': 'varchar(256)'}
    if type_map:
        _type_map.update(type_map)
    dj_desc = "id: int\n---\n"
    for attr, type_hint in cls.__annotations__.items():
        dj_type = _type_map[type_hint.__name__]
        dj_desc += "%s: %s\n" % (attr, dj_type)
    return dj_desc

print(make_dj_description(Stuff)) # Prints out a description which can be used in a DataJoint-compatible version of `MyClass`.
```
One could then turn the non-DJ version of `MyClass` into a DJ one with:
```
dj_MyClass = schema(MyClass)  # Programmatic alternative to adding the schema decorator
dj_MyClass.description = make_dj_description(MyClass)
```

This could applied to an arbitrary number of classes, turning a module with a bunch of type-hint-rich classes into a DataJoint schema without rewriting anything.  Most of the work here would be in getting the correct mapping of `type_map`.

**Comment by guzman-raphael** [comment]
An intriguing approach! It is nearly there on what DataJoint needs but misses a few important things.

I see some fundamental DataJoint features missed by this method for instance: Foreign Key relationships. 

Without them, each table will be independent of one another which doesn't fit into the DataJoint model of a Pipeline. Each DataJoint table normally 'connects' to a Pipeline at a node tier suitable for the entity. This approach effectively creates each table in a segregated manner as if they were each a part of their own Pipeline. 

A few things to consider:
- For each property in your classes, knowing only the type is not sufficient. You must know both the type and if the property is a Primary Key or a Secondary Key. 
- Primary Key names should be globally unique across a Pipeline to prevent name collisions when used as Foreign Keys. 
- Each class should have a one-to-many relationship to other classes to identify who are their parents (if any). Provided this is defined in your classes already, then you could use it to construct the Foreign Key declaration. 

If the above can be satisfied, then I would say you have met the minimum requirements to be able to automate a Pipeline.

**Comment by dimitri-yatsenko** [comment]
Hi @rgerkin ,

A DataJoint class constitutes a table, which denote a set of entities of a particular type. This is a distinct approach from the object-relational mapping that you are describing. A good review of the principles of the datajoint model is found here: https://arxiv.org/abs/1807.11104 — soon to be updated. The tutorial is more concrete.  Let's find some time to discuss this.

**Comment by dimitri-yatsenko** [comment]
DataJoint concerns itself with building a structured database with a cascade of dependencies, some of the which involve computations. The tables must be designed deliberately and with care for data integrity. The design of primary keys and foreign keys is essential for the expressing and enforcing data integrity constraints. So I would recommend designing the tables explicitly.

**Comment by rgerkin** [comment]
@dimitri-yatsenko @guzman-raphael 
I don't plan to use this a way to maintain full cross-compatibility between existing classes and dj tables, but just a way of avoiding have to rewrite table definitions for which 99% of the information is effectively already there in the type definitions in those classes.  With that being said:

```
def set_dj_definition(cls, type_map=None):
    _type_map = {'int': 'int', 'str': 'varchar(256)', 'float': 'float'}
    unsupported = [list, dict]
    if type_map:
        _type_map.update(type_map)
    dj_def = "id: int auto_increment\n---\n"
    for attr, type_hint in cls.__annotations__.items():
        if type_hint in unsupported:
            continue
        name = getattr(type_hint, '__name__', type_hint)
        default = getattr(cls, attr)
        if isinstance(default, str):
            default = '"%s"' % default
        elif default is None:
            default = 'NULL'
        if name in _type_map:
            dj_def += "%s = %s : %s\n" % (attr, default, _type_map[name])
        else:
            dj_def += '-> %s\n' % name
    cls.definition = dj_def

def schematize(cls, schema):
    result = []
    cls = type(cls.__name__, (dj.Manual, cls, object), {})
    set_dj_definition(cls)
    cls = schema(cls)
    return cls

from pyrfume.odorants import Molecule, Vendor, ChemicalOrder 
for cls in [Molecule, Vendor, ChemicalOrder]:
    locals()[cls.__name__] = schematize(cls, schema)
dj.ERD(schema).draw()
```

seems to work on selected classes from the pyrfume library (git master, not pypi version) I maintain, gives me the correct entity relationship diagram, and I can add/retrieve data.  Since that library is in flux and is also a dependency of a few other projects, I think this can help me speed up prototyping.  With that being said I will need to continue improving this to handle some of the complexities that you guys have brought up.  Ultimately the schema will need to settle -- I'm just not there yet and need something better for prototyping than typing everything twice.

Do you guys have a preferred location for general enhancements that you do not internally plan to support?  I could put it in pyrfume but it isn't specific to it as it should work on any class with typed attributes.

**Comment by guzman-raphael** [comment]
Closing based on latest offline discussions with @rgerkin and @dimitri-yatsenko.
