### ISSUE TITLE
connect to storage server via SMB

### ISSUE THREAD

**Issue by gmaggi** [datajoint/datajoint-python#755]
Hi,

I am starting to work with DJ, and I have some questions regarding to an external store.

- In the institution that I work on, we have a data storage server where users access to data via SMB (also NFS)  
- The main question is: does DataJoint have facilities to connect (from users PCs) to a  servers using SMB?
    * The idea would be that the same server can host the DataJoint database
    * If so, what prerequisite packages does the host server need? (this is a Solaris machine)
    * I guess the kind of connection that I was looking for is some thing like what you have in your docs: https://docs.datajoint.io/python/admin/5-blob-config.html#external-store

Thanks in advance,
Giuliano.

**Comment by guzman-raphael** [comment]
Hi @gmaggi. DataJoint External Store is certainly the right feature to be evaluating for this, however, there is not currently direct support for Samba. 

However, a workaround you might want to consider that should work is mounting the SMB share onto the host that DataJoint is running (as a pre-requisite) and configure access via a `file` external store. See [the doc above](https://docs.datajoint.io/python/admin/5-blob-config.html#principles-of-operation), specifically `dj.config['stores']['external-raw']`.

**Comment by gmaggi** [comment]
Thanks @guzman-raphael for the advices!. We've made some tests that are currently working fine, and we'll contact you gentlemen in case of additional questions.

Regards,
Giuliano.

**Comment by guzman-raphael** [comment]
For reference: This topic was continued within a DataJoint Slack thread @ https://datajoint.slack.com/archives/C456JE4GK/p1602489560011200.
