### ISSUE TITLE
batch insert that return failed items

### ISSUE THREAD

**Issue by jcouto** [datajoint/datajoint-python#772]
Hi, 

could there be a method for inserting multiple items in batch and knowing which ones failed?

Thanks in advance!

**Comment by dimitri-yatsenko** [comment]
Something like this?
```python
failed_elements = []
for element in collection:
    try:
        table.insert1(element)
    except Exception as err:
        failed_elements.append((element, err))
```

**Comment by eywalker** [comment]
No the suggestion here is to integrate such individualized insert as an option for `insert` method.

**Comment by dimitri-yatsenko** [comment]
Right. The code summarizes what it would take to accomplish the same goal before the feature is available. 

The current semantics of `insert` is that it performs a single query to the database as one transaction: the entire set is inserted all together or not at all.  Adding this new capability directly in `insert` would introduce a very different type of action. Before implementing something like this, I would like to question whether the solution above is actually clearer than an integrated solution would be. The solution above is sufficiently simple that it may not justify adding a new method to table or a new functionality to `insert`.

**Comment by eywalker** [comment]
Right makes sense. The need for inserting one by one, or in batches (so that the degree of rollback upon failure can be controlled) has come up a number of times, so it would be good for us to discuss and consider whether integrating this into `insert` would make sense.

**Comment by jcouto** [comment]
I guess the way I see this would be `allow_partial_inserts=True` in the method.  I agree that it doesn't fit with the semantics of `insert` but it is one of the things that happens to me often in the first stages of data ingestion; specially if i did not acquire the data myself. 

Perhaps only partially related: sometimes the reason for aborting an insert comes before the actual database call (e.g. due to enable_python_native_blobs).

**Comment by jcouto** [comment]
If you consider this in the future: To me it would make more sense that `insert` is unchanged but that`insert1` is able to parse a list of dicts (also).

**Comment by dimitri-yatsenko** [comment]
Closing. The logic of inserts is that it's an atomic operation. Partial failures need to be handled by the caller.  However, feel free to open a new issue or PR to address related concerns.
