### ISSUE TITLE
Operators Join `@` and Restrict `^` with permissive join-compatibility checks.

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#785]
DataJoint has a set of rules for *join compatibility*.  Joins can be performed on attributes that are semantically compatible. 

The present rule is:
> All the namesake attributes in both operands must be in the primary key of either of the operands.

The rule itself is likely to evolve before the 1.0 release.

An attempt to join two expressions that are not join compatible results in an error. The *join compatibility* are also applies when restricting one expression with another expression. 

In rare cases, users wish to override this restriction and allow joining on attributes that DataJoint deems incompatible. Under the current rule, this can be accomplished by promoting an attribute to be included in the primary key, making it compatible with any namesake attribute in the other operand. This technique will no longer generally work if the join-compatibility rule changes.

Therefore, we propose to add two new operators `@` and `^` that work identically to `*` and `&` but ignore the join-compatibility check.

## Join
```python
A * B   # raises an error if A and B are not join-compatible
A @ B  # joins anyway
```
## Restriction
```python
A & B  # raises an error if A and B are not join-compatible 
A ^ B   # restricts anyway
```
## Anti-restriction
```python
A - B  # raises an error if A and B are not join-compatible 
A & -B  # raises an error if A and B are not join-compatible 
A ^ -B   # anti-restricts anyway
```

## Aggregation
Aggregation will have an extra keyword argument, `permissive_join=False`
```python
A.aggr(B,  ...)   # raises an error if A and B are not join-compatible
A.aggr(B, ..., permissive_join=True)   # aggregates anyway
```

## Universal sets
Universal sets are join-compatible with anything

**Comment by stephenholtz** [comment]
I love this idea. Would it be simplifying for documentation (and people's memories) to instead use two of the operators together to indicate permissive join? e.g.:

`**` instead of `@`
`&&` instead of `^`

All of these operators are already associated with other meanings, so I don't think it would be more or less confusing on that side, but it could be easier to simply say "force/make permissive by adding a second `*` or `&`".

I understand if there are other planned meanings for `**` and `&&` in particular, however.

**Comment by dimitri-yatsenko** [comment]
Hm...  

`**` differs in operator precedence from `*` whereas `@` has the same precedence.  Also both `*` and `@` have similar semantics in Python: a product of two things. 

`&&` does not exist in Python.

**Comment by stephenholtz** [comment]
Ah, that make sense. The precedence alone kills the idea, switching between matlab and python is killing me with the `&&`.
