### ISSUE TITLE
Dataset transfer

### ISSUE THREAD

**Issue by ttngu207** [datajoint/datajoint-python#791]
Related to Issue #560 
DataJoint needs a feature to select a subset of data to be transferred to another database (with identical scheme/pipeline design)
For instance, users would select particular session(s) and all relevant upstream and downstream data are to be transferred to a specified host.

**Comment by CBroz1** [comment]
Relabel to `enhancement` or `under-development`?

**Comment by dimitri-yatsenko** [comment]
Duplicate of #560 
We will address these together.
