### ISSUE TITLE
Users deleting from auto-populated tables can break group integrity

### ISSUE THREAD

**Issue by SimonRenner** [datajoint/datajoint-python#794]
When deleting a row from an autopopulated table that has attributes in its primary key which do not come from upstream dependencies, that row might not get filled when populating the table again.

The table setup might look something like this

```python
class UpstreamTable(dj.Manual):
    definition = "\n".join([
    "first_attribute : int",
    "---"])

class MyTable(dj.Computed):
    definition = "\n".join([
    "->UpstreamTable",
    "new_attribute : int",
    "---",
    "some_secondary_attribute : float"])
```
If the entries in `MyTable` look like this:

```python
>>> MyTable
*first_attribute  *second_attribute  some_secondary_attribute
+---------------+  +--------------+  +------------------------+
1                      1                           1.7
1                      2                           -0.1
1                      3                           0.6
```
deleting one row will lead to that row not being repopulated again:
```python
>>> (MyTable & "second_attribute = 2").delete()
>>> MyTable
*first_attribute  *second_attribute  some_secondary_attribute
+---------------+  +--------------+  +------------------------+
1                      1                           1.7
1                      3                           0.6
>>> MyTable.populate()
>>> MyTable
*first_attribute  *second_attribute  some_secondary_attribute
+---------------+  +--------------+  +------------------------+
1                      1                           1.7
1                      3                           0.6
```

Supplying some warning or restriction either when defining such a table or when performing a delete that restricts with the new attribute would be helpful.

**Comment by dimitri-yatsenko** [comment]
I changed the title to indicate that this happens when the user deletes from auto-populated tables when restricting the delete by something other the key source. This may happen in a variety of ways but always due to the user's delete command. In other words, datajoint allows deleting parts of what is populated by a single `make` call. 

This is related to issue #151.

**Comment by dimitri-yatsenko** [comment]
This design pattern was one of the main motivations for the Master-Part relationship.

class UpstreamTable(dj.Manual):
    definition = "\n".join([
    "first_attribute : int",
    "---"])

class MyTable(dj.Computed):
    definition = "\n".join([
    "->UpstreamTable",
    "new_attribute : int",
    "---",
    "some_secondary_attribute : float"])

**Comment by SimonRenner** [comment]
What could such a policy look like in the current case? I can think of stuff like overloading delete functions or creating custom table subclasses but this feels more like a hack than a solution.

**Comment by dimitri-yatsenko** [comment]
This can and should be addressed by schema design. Any time a set of entities is treated as an inseparable group, it should be organized as a master-part relationship where the new attributes in the primary key are introduced in the part but not in the master. You might institute a policy that auto-populated tables (`dj.Imported` and `dj.Computed`) should be constructed only from foreign keys without introduce any new attributes.

**Comment by guzman-raphael** [comment]
@SimonRenner With the latest response it appears the intent here has been satisfied by @dimitri-yatsenko's suggestion. Closing for now but feel free to reopen if there is something that was missed.
