### ISSUE TITLE
schema/table navigation methods

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#800]
should provide methods to:
* list tables within a schema
* list parts within a master:part
* ???

**Comment by guzman-raphael** [comment]
To match our `dj.list_schemas()` syntax, perhaps we could do the following?
- If `schema` is a schema object, `schema.list_tables()`
- If `Student` is a master table, `Student.list_parts()`

**Comment by ixcat** [comment]
other alternative could be some kind of `dj.ls` / `dj.dir` kind of a thing (or both)

**Comment by guzman-raphael** [comment]
Superseded by #838
