### ISSUE TITLE
File permissions for external store

### ISSUE THREAD

**Issue by chbehrens** [datajoint/datajoint-python#807]
I suggest to add an option to configure the file/folder permissions for the external storage. Currently it is 755, so only the user who created the database (or rather stored the first files) is able to use the external storage. That means other database users are not able to populate any table that stores files externally.

**Comment by ixcat** [comment]
Hi @chbehrens - thanks for the feedback

Though we can certainly see some utility here, reviewing further we will continue to treat this as an externality/administrative concern related to managing external shared storage and not manage this from DataJoint natively.

For windows stores, I would ensure the users are in a common group, and then recursively modify permissions on the root folder of the external store to allow access to that group. Further permissions should be inherited automatically.

For unix/mac/linux stores (using a shared directory, NFS, or other unix-native storage), I would suggest also ensuring the users are in a common group, and (assuming only users in the group should have access) modifying directories to have :group / 02770 permissions and for files to have :group 0660 permissions. After this, I'd also add a 'umask' call to common pipeline code or ensure this is present in each user's profile. More concretely (as root):

to setup/adjust existing share/users:
```
groupadd datajoint
usermod -a -G datajoint bob
usermod -a -G datajoint alice
chown -R :datajoint /path/to/share
find /path/to/share -type d -print0 |xargs -0 chmod 02770
```

The 02770 permissions imply that created items will be created inheriting the group from the parent, and full read/write/create/delete access to the folder for users in the datajoint group. File creation is handled with this
in combination with the user `umask(2)` setting. 

In python (e.g. in pipeline/schema initialization code): 
```
import os
import stat
os.umask(stat.S_IROTH | stat.S_IWOTH | stat.S_IXOTH) # mask out other read,write,execute flags
```
or from the shell (prior to running python/datajoint):
```
umask 007
```
More on umask is available in the `umask(2)` and `inode(7)` manual pages (Linux) or `umask(2)` / `chmod(2)` (MacOS)

Alternately, using S3 storage (e.g. with `min.io`) would allow the object storage server to run with one set of backing file permissions, and user/client access to be delegated with S3 credentials.
