### ISSUE TITLE
Request: Implement attribute rename function 

### ISSUE THREAD

**Issue by spapa013** [datajoint/datajoint-python#810]
Requesting a method that allows for renaming any attribute in table view using `.proj()` but that doesn't drop the secondary attributes that are not passed into `.proj()`.

```python
def rename(rel, **kwargs):
    return rel.proj(*rel.heading.names, **kwargs)
```

**Comment by dimitri-yatsenko** [comment]
Try
```
r.proj(..., new='old')
```

**Comment by spapa013** [comment]
That fulfills the request, thanks!
