### ISSUE TITLE
ERD plotting support

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#82]
The logic for creating and manipulating graphs that represent the ERD is pretty much there and can be found in the `erd` branch. I will keep this branch as the feature implementation branch. There are a few issues that I'm running into as I try implementing plotting support:

1. `pygraphviz` library that was once used in our project for plotting ERD does not support Python 3 natively **yet**. Explicitly using their beta branch with `pip install pygraphviz==1.3rc2` allows us to use it in Python 3, but I'm not sure if we would like to introduce a dependency on beta-version of the package, especially as this is a very specific dependency.
2. `pydot` is an alternative package that may be used, but again there is no official Python 3 support. There appears to be a port `pydot3k`

The above two were the preferred method to work with `graphviz` graph plotting engine, that yields very nicely arranged graphs. Alternatively, I could try working with `graphviz` directly, but to my knowledge, the library can only render files like `.pdf` files at the end and it takes some effort to display this into `matplotlib`.

**Comment by dimitri-yatsenko** [comment]
Fixed in PR #208
