### ISSUE TITLE
Remove Python 3.5 support

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/datajoint-python#829]
As it has reached [End-of-Life](https://www.python.org/dev/peps/pep-0478/#release-schedule), we can safely remove support and update docs.

Noting hear as there were some challenges that Python 3.5 presented specifically when building lightweight conda-based images for development, testing, and deployments.

**Comment by dimitri-yatsenko** [comment]
Awesome! I cannot wait to get rid of all the OrderedDicts. Should we do this in 0.13?

**Comment by guzman-raphael** [comment]
Sounds to me like a good time to make the update. Let's confirm with others in our upcoming Dev meeting tomorrow.

**Comment by eywalker** [comment]
Note that the fact dictionary is ordered is considered an implementational detail and only specifically for CPython 3.6. This means that any other valid implementation of Python 3.6 standard need not provide ordered dictionary. In contrast, Python 3.7 is using ordered dictionary at the specification level. So we can safely drop OrderedDict from 3.7 onward but not while we are supporting Python 3.6
