### ISSUE TITLE
Request for a `schema.list_tables()`

### ISSUE THREAD

**Issue by ttngu207** [datajoint/datajoint-python#838]
Similar to `dj.list_schemas()`, would be great if we can list all tables under a particular schema that are topologically sorted - with `schema.list_tables()`

**Comment by Synicix** [comment]
#844 
I added basic table fetcher for now since that is what I needed for DJGUI.

I am not entirely sure what you mean by topologically sorted, as in a dict with the table names in hierarchy of which one depends on each other? Either way I probably work on that later unless it is urgently needed.

**Comment by dimitri-yatsenko** [comment]
Fixed with #844

**Comment by guzman-raphael** [comment]
Hey @dimitri-yatsenko. We are keeping this open as it is currently not applying a topological sort.

**Comment by dimitri-yatsenko** [comment]
I see. #833 provides `connection.dependencies.topological_sort()` to provide this functionality.
