### ISSUE TITLE
Create a function in utils.py that converts raw tables name from list tables to actual class names and types

### ISSUE THREAD

**Issue by Synicix** [datajoint/datajoint-python#848]
Return a dict with keys of tables types and the name of each tables.

-- For part tables, list the name with <Parent>.<Part>

**Comment by Synicix** [comment]
Discussed with Rapahel, Chris, Maho, and Shan already, We agree on this route for now.

**Comment by dimitri-yatsenko** [comment]
This issue seems like a solution rather than an issue to be solved. Please describe the issue instead so we can find an optimal solution.

**Comment by Synicix** [comment]
In short list_tables function that was commited last week spits our raw tables name for now. We wanted to parse the table names into it actual Table name that users of datajoint are use too. After digging around datajoint for possiable pre built implmentation, we decided to just go with a new function cause all the prexisting function we found had some issues one way or other.

**Comment by dimitri-yatsenko** [comment]
What is a use-case scenario? What are "actual Table names"?

**Comment by Synicix** [comment]
Use case will be when the user want to list all tables in a schema, currently it only return it as raw, which isn't exactly how a user typically use datajoint. Second use case that we need is for the DJGUI which to query what tables are there under the schema, and instead having the parsing code of the raw names outside of datajoint we opt it to be included inside the datajoint package as a util.

Actual table names is whatever datajoint class names are.
i.e #look_up_table = LookUpTable in typical datajoint python usage.

**Comment by dimitri-yatsenko** [comment]
This function already exists: `dj.utils.to_camel_case`.

**Comment by guzman-raphael** [comment]
@Synicix We have just introduced issue templates into the issue tracker now. Would you mind [reopening this issue](https://github.com/datajoint/datajoint-python/issues/new/choose) using the new `Feature request` template? Filling out the fields there should resolve the housekeeping points raised here. Will close this issue in lieu of the new one.
