### ISSUE TITLE
restriction does not work for some cases of query with proj computation.

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#894]
### Description
Under some conditions, restriction does not work as expected when restricting on some computed field out of proj.

### Reproducibility
dj python 0.12.7 and dj python 0.13.0

Here is a notebook that reproduce the behavior. Generated by Austin Hoag from Princeton running with dj 0.12.7 and I ran it and found the same thing in 0.13.0

https://github.com/PrincetonUniversity/lightsheet_helper_scripts/blob/master/datajoint/dj_proj_restrict_issue.ipynb

**Comment by jverswijver** [comment]
Issue is no longer reproduce-able with the attached jupyter notebook. When I use the notebook to reproduce the error the last line (ln47) where the restriction should not work actually does work for me. @guzman-raphael

**Comment by dimitri-yatsenko** [comment]
This was originally reported in DataJoint 0.12.*  whereas DataJoint 0.13.0 re-implemented the query transpilation module.

**Comment by jverswijver** [comment]
This issue was likely patched when addressing a related regression issue @shenshan, I will end up closing the issue in about a week if I don't hear back from you. Feel free to open the issue back up if occurs again.
