### ISSUE TITLE
explicit calls to dj.connection.Connection fail without providing 'host_input'

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#895]
### Description

explicit calls to dj.connection.Connection fail without providing 'host_input'
(seems to be a 0.13 regression)

### Expected Behavior

call dj.connection.Connection without host_input argument

### Additional Research and Context

dj.connection.Connection sets default host_input to None; this value is then passed to get_host_hook
where it is tested in the statement: `if '://' in connection_obj.conn_info['host_input']:` which raises: `TypeError: argument of type 'NoneType' is not iterable`

side note: seems like some duplicate & inconsistent logic in processing dj.config values between Connection, conn and get_host_hook; might make sense to refactor get_host_hook to simply take a raw host string which returns all needed parts (casually, among the 3: host, port). This would also remove the need for host_input in Connection.

also probably means that explicit dj.Connection tests need to be added

**Comment by guzman-raphael** [comment]
@ixcat The logic behind `conn` and `Connection` is quite old and clunky. For this, it is not advisable to call `Connection` directly. There is specific pre-processing in `conn` that is bypassed by calling `Connection` directly. We should optimize this to be more streamlined in the future but for now, I would say that we should discourage use of `dj.Connection` directly and perhaps not make it available by default. If you have a specific use-case on the need for using `dj.Connection` over `dj.conn` I would like to understand it a bit more.

**Comment by ixcat** [comment]
We use multiple connections in several places, so relying on dj.conn() is a no-go.
Above refactor description addresses all concerns & supports both methods AFAICT

**Comment by ixcat** [comment]
Didn't consider plugin usage in refactor proposal; that said I think the overall approach should be applicable & would simplify logic overall (haven't xchecked). A stopgap would be simply defaulting host_input in Connection to the empty string or adjusting the '://' test to support NoneType input (former seems preferable; Connection seems to be the only consumer passing None to the hook function so no need to layer hacks on hacks to support Connection)

**Comment by saumilpatel** [comment]
Yes, we have to be able to make multiple connections, need to fix this asap and also provide a mechanism to install older version via pip.
