### ISSUE TITLE
Unexpected Join product in 0.13.0

### ISSUE THREAD

**Issue by shenshan** [datajoint/datajoint-python#898]
## Bug Report

Join product is unexpected for dj 0.13.0, behavior was correct in dj 0.12.9

### Reproducibility
- OS (MACOS)
- Python Version 3.7.3
- MySQL Version 10.4.13-MariaDB 
- MySQL Deployment Strategy (local-native)
- DataJoint Version 0.13.0

Code to reproduce the error:
```
import datajoint as dj
schema = dj.schema('test')

@schema
class Subject(dj.Manual):
    definition = """
    subject_id: varchar(32)
    ---
    dob : date
    sex : enum('M', 'F', 'U')
    """

@schema
class Session(dj.Manual):
    definition = """
    -> Subject
    session_start_time: datetime
    ---
    session_dir=''  : varchar(32)
    """

@schema
class SessionStatus(dj.Manual):
    definition = """
    -> Session
    ---
    status: enum('in_training', 'trained_1a', 'trained_1b', 'ready4ephys')
    """

@schema
class SessionDate(dj.Manual):
    definition = """
    -> Subject
    session_date:  date
    """

Subject.insert([
    ('mouse1', '2020-09-01', 'M'),
    ('mouse2', '2020-03-19', 'F'),
    ('mouse3', '2020-08-23', 'F')
])

Session.insert([
    ('mouse1', '2020-12-01 12:32:34', ''),
    ('mouse1', '2020-12-02 12:32:34', ''),
    ('mouse1', '2020-12-03 12:32:34', ''),
    ('mouse1', '2020-12-04 12:32:34', '')
])

SessionStatus.insert([
    ('mouse1', '2020-12-01 12:32:34', 'in_training'),
    ('mouse1', '2020-12-02 12:32:34', 'trained_1a'),
    ('mouse1', '2020-12-03 12:32:34', 'trained_1b'),
    ('mouse1', '2020-12-04 12:32:34', 'ready4ephys'),
])

SessionDate.insert([
    ('mouse1', '2020-12-01'),
    ('mouse1', '2020-12-02'),
    ('mouse1', '2020-12-03'),
    ('mouse1', '2020-12-04')
])

subjects = Subject.aggr(
    SessionStatus & 'status="trained_1a" or status="trained_1b"', 
    date_trained='min(date(session_start_time))')
```

After the above commands, subjects is like this:
![image](https://user-images.githubusercontent.com/2539832/113460146-8b067600-93cc-11eb-97a4-825dc6962fa3.png)
 
SessionDate is like this:
![image](https://user-images.githubusercontent.com/2539832/113460203-b8532400-93cc-11eb-9ef0-d1ff171d2e6f.png)

In 0.12.9, their join product is correct:
![image](https://user-images.githubusercontent.com/2539832/113460237-d28d0200-93cc-11eb-85d8-7b67c6ccfdde.png)

In 0.13.0, their join product is not correct:
![image](https://user-images.githubusercontent.com/2539832/113460296-108a2600-93cd-11eb-8877-40baa4645d75.png)
It said total is 4 somehow.

**Comment by guzman-raphael** [comment]
Thanks for reporting this and providing a good example, @shenshan. This does appear to be a regression issue.

Reviewing the generated query in `0.13.0` for your example above, i.e. `(SessionDate * subjects).make_sql()`:

```sql
SELECT `subject_id`,`session_date`,min(date(session_start_time)) as `date_trained`
FROM `djtest_raphael`.`#session_date`
NATURAL JOIN `djtest_raphael`.`#subject`
NATURAL JOIN `djtest_raphael`.`#session_status`
```

It seems incorrect as the `WHERE` and `GROUP BY` were omitted. I would have expected it to be:

```sql
SELECT `subject_id`,`session_date`,min(date(session_start_time)) as `date_trained`
FROM `djtest_raphael`.`#session_date`
NATURAL JOIN `djtest_raphael`.`#subject`
NATURAL JOIN `djtest_raphael`.`#session_status`
WHERE `status` = 'trained_1a' or `status` = 'trained_1b'
GROUP BY `subject_id`, `session_date`
```

I'll look more into this to find why this happened, determine an appropriate fix and add a test for it.
