### ISSUE TITLE
13.2 fresh install dependency issues

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#922]
### Description

Installing 13.2 fresh on ubuntu 20.04/py3.8.5 yielded the following dependency errors:

        raise VersionConflict(dist, req).with_context(dependent_req)
        pkg_resources.ContextualVersionConflict: (cryptography 3.4.7 (/opt/ve/lib/python3.8/site-packages), Requirement.parse('cryptography<=3.3.2'), {'otumat'})

        raise VersionConflict(dist, req).with_context(dependent_req)
        pkg_resources.ContextualVersionConflict: (decorator 5.0.9 (/opt/ve/lib/python3.8/site-packages), Requirement.parse('decorator<5,>=4.3'), {'networkx'})

doing:
```
pip install 'cryptography<=3.3.2'
pip install 'decorator<5,>=4.3'
```
resolves in the envirionment.

Not sure best way to resolve the issue (could be issues for networkx or otumat), so filing here for tracking.

Should also find out why current CI tests are working - guessing our dev images are 'too good' and somehow sort this out up-front before DJ install, or maybe are out of date and we need to get them auto-building as well.

### Reproducibility

happens consistently in the following environment:

```
FROM ubuntu:20.04

# todo: mkdir home, proper group
RUN useradd dj && install -d -o dj -g dj /opt/ve

RUN apt-get update \
	&& apt-get upgrade \
	&& apt-get install -y ed nvi netcat-openbsd dnsutils net-tools \
	&& apt-get install -y python3 python3-pip python3-venv

USER dj

RUN python3 -mvenv /opt/ve \
	&& . /opt/ve/bin/activate \
	&& pip3 install datajoint datajoint-connection-hub
```
since the dependency tree appears to be pip or python version related, and the errors are coming from python module logic while checking installed versions, I'm guessing this not to be OS platform specific.

test was done against 'datajoint-connection-hub' but I did see both errors in another project recently; didn't dig further at the time since this was during a pending point release with dependency issues active (#910)

### Expected Behavior

direct install works without dependency modification.

**Comment by guzman-raphael** [comment]
This has been resolved by release [0.3.0](https://github.com/datajoint/otumat/releases/tag/v0.3.0) of otumat (see [here](https://github.com/datajoint/otumat/pull/4/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L32) for more details).

Verified by running: `docker run --rm -it python:latest pip install datajoint`.
