### ISSUE TITLE
graphviz install documentation coverage

### ISSUE THREAD

**Issue by ixcat** [datajoint/datajoint-python#925]
### Description

DataJoint for Python has a dependency on graphviz binaries. 
This is outlined clearly for the windows install steps, but not covered for other platforms, creating confusion
(see also: https://github.com/datajoint/datajoint-python/issues/924)

### Expected Behavior

Documentation of prerequizites for all platforms.

### Additional Research and Context

Relatedly, windows documentation on install has open issues related to similar topics; might make sense to rework 'as a set':

https://github.com/datajoint/datajoint-docs/issues/229
https://github.com/datajoint/datajoint-docs/issues/245

**Comment by dimitri-yatsenko** [comment]
Documented in #https://datajoint.com/docs/core/datajoint-python/latest/getting_started/#installation
