### ISSUE TITLE
Organize tests

### ISSUE THREAD

**Issue by eywalker** [datajoint/datajoint-python#93]
Currently the way the test case is written is quite chaotic, and rather difficult to understand. It would make sense to try to come up with a better organization for the tests, especially before we have too many test cases such that we all become very reluctant to make any changes.

**Comment by eywalker** [comment]
With a major upcoming change in the DataJoint schema handling as described in #96 , effectively all existing tests will have to be rewritten. The new implementation removes association of database `schema` and Python `module`, and thus should make testing much more straightforward, with less side effects to be worried about.

**Comment by fabiansinz** [comment]
All the previous tests that have been provided for `test_relation` should be put back into place instead of just being deleted.

**Comment by dimitri-yatsenko** [comment]
solved in e0aadc03
