### ISSUE TITLE
get_select_fields is gone in DJ 0.13.2

### ISSUE THREAD

**Issue by horsto** [datajoint/datajoint-python#935]
## Bug Report
I was previously able to call `some_dj_join_object.get_select_fields()`, but since updating to dj python 0.13.2 I can't access that attribute anymore. 

### Reproducibility
Include:
- MacOS 10.15.7
- Python 3.6
- DataJoint Version 0.13.2
- Create a join object and call `.get_select_fields()` 
- Error: `AttributeError: 'QueryExpression' object has no attribute 'get_select_fields'`

Is there an easy workaround for this?

**Comment by guzman-raphael** [comment]
@horsto Thanks for the report. Would you mind sharing the actual statement you are trying to run and the error that is returned?

**Comment by dimitri-yatsenko** [comment]
`get_select_fields()` was an internal method before 0.13.*, not part of the API. We will be sure to prefix all internal methods with underscores. If the intent was to extract the current header, then the `.heading` property provides that information.

**Comment by horsto** [comment]
Thanks. Replacing `.get_select_fields()` by `.heading.names` did the job for me.
