### ISSUE TITLE
remove_object failure should be exception, not error return value

### ISSUE THREAD

**Issue by chrisroat** [datajoint/datajoint-python#952]
Should this `return` be a `raise`?
https://github.com/datajoint/datajoint-python/blob/5b81247fdb5861ebef098a5d4cbfe26098143eda/datajoint/s3.py#L87

**Comment by guzman-raphael** [comment]
@chrisroat Thanks for reviewing this! It does appear that it would make more sense for this to raise an error. I'll mark it as a bug for now.
