### ISSUE TITLE
ExternalTable.delete should not remove row on error

### ISSUE THREAD

**Issue by chrisroat** [datajoint/datajoint-python#953]
### Description

When deleting from an `External` table with `delete_external_files=True`, the rows are deleted from the table followed by deleting files from the filesystem.  This behavior means an error in file deletion will leave excess data present with no record of it in the database.  For large pieces of data, this could be undesired.  And since an error is not raised, many clients won't realize there is a return value and check it (mosts/all tests do not even check this).

https://github.com/datajoint/datajoint-python/blob/5b81247fdb5861ebef098a5d4cbfe26098143eda/datajoint/external.py#L339-L350

### Expected Behavior

Instead of errors being returned, I suggest:
- an error be raised if there is a problem
- the rows should not be deleted from the external table

**Comment by guzman-raphael** [comment]
@chrisroat Excellent point and thanks for catching this! This certainly seems like a bug and we'll be sure to prioritize accordingly.
