### ISSUE TITLE
implement AutoPopulate.progress

### ISSUE THREAD

**Issue by dimitri-yatsenko** [datajoint/datajoint-python#98]
`AutoPopulate.progress` reports the number of tuples remaining to be populated.  See the MATLAB implementation.

**Comment by fabiansinz** [comment]
With print or via `log.info`?

**Comment by dimitri-yatsenko** [comment]
i think print.

**Comment by fabiansinz** [comment]
I think it would be nice if there was an option to switch it off. Something like a global VERBOSE setting.

**Comment by dimitri-yatsenko** [comment]
resolved in d547f83a
