### ISSUE TITLE
Change ~jobs.error_stack from blob to mediumblob

### ISSUE THREAD

**Issue by chrisroat** [datajoint/datajoint-python#984]
### Description

I recently hit the following exception during a job error, which I admit is likely to be rare.

```
(1406, "Data too long for column 'error_stack' at row 1")
```

I am mitigating by changing error_stack to mediumblob for our datajoint fork.

**Comment by dimitri-yatsenko** [comment]
Wow! A 64kB+ stack! Makes sense. Will change to medium blob. The change won't upgrade existing schemas, so users will need to drop the old jobs table:

**Comment by dimitri-yatsenko** [comment]
@chrisroat Would you like to PR your change?
