### ISSUE TITLE
Unable to unpack blob with `dj0 mYm` prefix

### ISSUE THREAD

**Issue by kabilar** [datajoint/datajoint-python#990]
### Problem
A bit of a corner case but perhaps it can be addressed at the same time as [datajoint/mym Issue #86](https://github.com/datajoint/mym/issues/86).

Have completed a database transfer from a source database (MySQL 5.1.73) to a target database (MariaDB 10.2.33).  Data in the source database was inserted with mym v1.36.  The database transfer was completed in python.  Data was fetched with pymysql (because datajoint-python cannot read blob data inserted with mym v1.36 [datajoint/mym Issue #86](https://github.com/datajoint/mym/issues/86)) and inserted with datajoint-python version >=0.13 (see [transfer script](https://github.com/Brody-Lab/bl_pipeline_python/blob/b67867b2b5bd98976a4332a52596cc5839db1dc7/scripts/transfer_data_oldDB.py#L169-L189)).  

The resulting blob fields in the target database have a `dj0 mYm` prefix and cannot be unpacked by datajoint-python.

Source database
- `mYm` prefix for the blob data
```
select 
protocol_data,
hex(protocol_data) from bdata.sessions 
where sessid = 822635
```

```
mYm S ....
6D596D005302000000010000
```

Target database
- `dj0 mYm` prefix for the blob data
```
select 
protocol_data ,
hex(protocol_data),
SUBSTRING(HEX(protocol_data), 27)
from bdatatest.sessions 
where sessid = 822635
```

```
dj0  ô       mYm S....
646A300006F4000000000
6D596D0053020000000100
```

Target database
- Fetched with datajoint, but unable to unpack.
```
In [1]: import datajoint as dj

In [2]: dj.__version__
Out[2]: '0.13.2'

In [3]: bdatatest=dj.create_virtual_module('bdatatest','bdatatest')

In [4]: (bdatatest.Sessions & 'sessid=822635').fetch1('protocol_data')
Out[4]: b'mYm\x00S\x02\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00hits\x00sides\x00tasks\x00stage\x00M\x00\x00\x00A\x02\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf8\xff\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf8\xff#\x00\x00\x00A\x02\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00l\x00l\x00l\x00l\x00r\x00r\x00l\x00#\x00\x00\x00A\x02\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00d\x00d\x00d\x00d\x00d\x00d\x00d\x00%\x00\x00\x00A\x02\x00\x00\x00\x01\x00\x00\x00\x08\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00S\x00t\x00a\x00g\x00e\x00 \x001\x000\x00'
```

From my understanding, datajoint-python could read the blob attribute if it started with the prefix `mYm` but cannot parse `dj0 mYm`.

Thanks!

**Comment by dimitri-yatsenko** [comment]
it looks like the data transfer was not performed correctly. The real bug is probably not in datajoint but in the data transfer process.

**Comment by kabilar** [comment]
Thank you @dimitri-yatsenko.  Will address this issue on the data transfer side.

**Comment by kabilar** [comment]
Instead of fetching with pymysql, once datajoint-python, datajoint-matlab, and mym are fixed for https://github.com/datajoint/mym/issues/86 then the database transfer can happen with a mysql utility and the 32-bit serialized blob data in the target database can be fetched with datajoint-python.
